ciao-project/ciao

ciao-controller/test.yaml, ciao-vendor/ciao-vendor.go
The password and chpasswd fields were upsetting clr-cloud-init.
The unnecessary quotes surrounding the password field have also
been removed.  The new configuration works on both Ubuntu 15.10
and clear-7490-cloud.img.
=> controller: test.yaml: Fix the test.yaml file

.travis.yml, test-cases/test-cases.go
The output from go test is really messy and verbose.  There's so much output that it's hard to tell which test is causing a build failure.  Test-cases on the other hand generates a nice tabular output.  Compare the output of this build using go test
https://travis-ci.org/01org/ciao/jobs/126794144
to this build using test-cases
https://travis-ci.org/markdryan/ciao/jobs/126948990
The test-cases build is almost 900 lines shorter.
A few changes were made to test-cases to get this to work.  I added the -text option which causes test-cases to output the test results in text rather than HTML and -tags and -short which are passed directly to go test.  Test-cases can also now accept multiple packages on the command line, and it exits with an error code if any of the tests it runs fails.
=> Travis: Use test-cases instead of go test to run unit tests

ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go
Rather than add instance information asynchronously to the cache,
update the cache synchronously and only update the database
asynchronously.  This change prevents the case where a user
may be able to request workload starts over their limit because
the cache isn't done updating.
=> ciao-controller: instances: update usage synchronously for cache

ciao-controller/compute.go, ciao-controller/types/types.go
Modify listServerDetails() to sort the instances it retrieves
from the datastore prior to sending to the user.  Modify types
to add a sorted instance type which implements a sort interface
to sort by instance ID.
=> ciao-controller: compute: sort instances by ID

.travis.yml
We need to add back in the go_import_path statement.  Otherwise forks of ciao
will fail to build in Travis CI.
=> travis: Fix travis builds for github forks

payloads/deletefailure.go, payloads/restartfailure.go, payloads/start.go, payloads/startfailure.go, payloads/stats.go, payloads/stop.go, payloads/stopfailure.go
All exported types and fields in the following files have now been
documented, thereby fixing the golint errors reported in these files.
- deletefailure.go
- restartfailure.go
- start.go
- startfailure.go
- stats.go
- stop.go
- stopfailure.go
=> payloads: Add documentation to fix golint errors

ciao-cli/main.go, ciao-controller/compute.go, ciao-controller/compute_test.go, payloads/assignpublicIP.go, payloads/cnciinstance.go, payloads/compute.go, payloads/concentratorinstanceadded.go, payloads/configure.go, payloads/configure_test.go, payloads/evacuate.go, payloads/instancedeleted.go, payloads/nodeconnected.go, payloads/publicIPassigned.go, payloads/ready.go, payloads/tenantadded.go, payloads/trace.go, test-cases/test-cases.go
Pretty much all of these errors were documentation errors.  One was a badly named variable.
Documentation has been added for all exported types.  Some types which have been added but are not yet really used have been documented, reserved for future use.
=> Fix all outstanding golint errors in payloads.

.travis.yml
go vet is run on all packages except for ciao-controller which currently
contains a go vet error.  Once this is fixed we'll update the travis.yml
file to vet this package as well.
The following packages are excluded from golint runs as they too contain
errors:
- github.com/01org/ciao/ciao-cli
- github.com/01org/ciao/ciao-controller/internal/datastore
- github.com/01org/ciao/ciao-controller/types
golint is disabled on tip for the time being.  It seems to be panicking.
=> travis: Fail build on go vet, golint or misspell errors

.travis.yml
Now that all the ciao code is go vet and golint clean we can execute
these commands using a wildcard, rather than by specifying individual
packages.
=> travis: Simplify go vet and golint commands

ciao-scheduler/scheduler.go
This is a series of cleanups found while looking at gocyclo's complaint about the scheduler's console heartbeat. Testing a refactor of the heartbeat highlighted that connect/disconnect races exist. Locking then became a part of what started as a much simpler refactor. Code runtime tests good manually, passes travis CI automation and gocyclo is now happier too.
This PR replaces PR #122.
=> scheduler locking (issue #120) fixes

networking/libsnnet/bridge_test.go, networking/libsnnet/cn_container_test.go, networking/libsnnet/cn_test.go, networking/libsnnet/cnci_test.go, networking/libsnnet/cncivnic_test.go, networking/libsnnet/dnsmasq_test.go, networking/libsnnet/firewall_test.go, networking/libsnnet/gre_test.go, networking/libsnnet/internal_test.go, networking/libsnnet/vnic_test.go
Using testify for unit test cases reduces the complexity of the unit test cases.
This reduces the cyclomatic complexity significantly.
=> Networking: Use Testify for all Networking Unit test cases

ciao-scheduler/scheduler.go
I apparently mismerged/misrebased a change.  The earlier code was supposed
to be leaving nodeStat's locked once picked for dispatching.  I left some
Unlock() calls in the code.  So the later code that's supposed to unlock
the locked node was unlocking an unlocked node, which nicely results in a
very obvious panic from golang.
Signed-off-by: Tim Pepper <timothy.c.pepper@intel.com>
=> ciao-scheduler: yet more lock fixing

networking/cnci_agent/scripts/generate_cnci_cloud_image.sh, networking/libsnnet/cn.go, networking/libsnnet/cn_container_test.go, networking/libsnnet/cnci.go, networking/libsnnet/tests/parallel/parallel_test.go, networking/libsnnet/utils.go, networking/libsnnet/vnic.go
The PR implements significant refactoring of the networking code base to reduce complexity.
However some unit tests and integration tests still have higher complexity.
Key changes included are
- Separating  the topology handling from the interface creation the case of CN and CNCI APIs
- Unification of the physical interface detection logic between CN and CNCI APIs
- Fixing of gometalinter flagged issues
=> Networking: Code refactoring to reduce complexity

.travis.yml, test-cases/test-cases.go
This should improve travis build times as we no longer need to compute the coverage data twice.  Previously coverage anaylsis was being done by both test-cases and gotestcover.  This change also allows us to generate coverage data for the unit tests that need to be run as root.
Some changes were required to test-cases to make this possible.  In short two new command line options, coverprofile and append-profile, were added to allow coverage data to be generated.
=> Use test-cases to generate coverage data

payloads/assignpublicIP_test.go, payloads/configure_test.go, payloads/deletefailure_test.go, payloads/restartfailure_test.go, payloads/start_test.go, payloads/startfailure_test.go, payloads/stopfailure_test.go, testutil/testutil.go, testutil/yaml.go
I needed practice making a table based test and the coverage report is
annoying in its outliers such as these couple little things in payloads.
I'm starting to move commonly used definitions to the testutil package,
so they can be used by multiple subcomponents' unit tests without
duplicating efforts.
Signed-off-by: Tim Pepper <timothy.c.pepper@intel.com>
=> payloads: finish off coverage

README.md
The scheduler is a pull scheduler more than a push scheduler, or now I'm
hearing people say "push/pull".  The scheduler does not simply push work,
looking for a place to land it.  Compute nodes check in and request work,
with the scheduler handing the work to a node that has requested work.
It's not strictly pull arguably because the compute nodes aren't checking
in and immediately bidding for or pulling work off a work queue.
Signed-off-by: Tim Pepper <timothy.c.pepper@intel.com>
=> documentation: push vs pull

ciao-controller/workloads/test.yaml, ciao-launcher/tests/examples/start_efi.yaml, ciao-launcher/tests/examples/start_legacy.yaml, ciao-launcher/tests/examples/stress/efi.sh, ciao-launcher/tests/examples/stress/legacy.sh, networking/cnci_agent/scripts/README.md, networking/cnci_agent/scripts/seed/openstack/latest/user_data
- ciao user already exist as a system user, this changes
renames it to demouser
- Update ciao-launchers examles to use demouser
- Update networking scripts to use demouser
- Update Documentation to use demouser/ciao to login
in vms
Closes https://github.com/01org/ciao/issues/131
=> ciao-controller: rename cloudinit user

.travis.yml, ciao-launcher/delete.go, ciao-launcher/instance.go, ciao-launcher/instance_test.go, ciao-launcher/main.go, ciao-launcher/network.go, ciao-launcher/overseer.go, ciao-launcher/restart.go, ciao-launcher/start.go, ciao-launcher/stop.go
These commits add some unit tests to the instanceLoop go routine.  The tests work by using channels and interfaces to fake the overseer and the connection to the SSNTP server, allowing us to fully test the instanceLoop.  A few small changes were needed to the launcher code to permit this.  The travis build file also needed to be changed to pre-create the /var/lib/ciao/instances directory.  Doing this in the travis files allows the launcher unit tests to run as non-root.
This commit should bring the test coverage of launcher up to 16.2%.
=> ciao-launcher:  Add unit tests for the instanceLoop

ciao-controller/README.md
The compute service and its corresponding endpoint needs to be created
in order to gain compatibility with openstack tools API calls for
novaclient which is used by tools as OpenStack client (cli), Rally
Benchmarking and others
=> Add documentation for creation of compute service and endpoint

data/systemd/ciao.conf
This file helps OSV to provide volatile directories by using
systemd tmpfiles[1]
[1] - https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html
=> add ciao tmpfiles.d configuration file

.travis.yml
Run gofmt -s, misspell, gocyclo and ineffassign as part of the travis
builds.  Any build that introduces an error detected by one of these
tools should now fail.  This should ensure that our goreportcard
score never falls below 100%.
Fixes #172
=> travis:  Enable gofmt, misspell, gocylco and ineffassign

ciao-vendor/ciao-vendor.go, test-cases/test-cases.go, vendor/github.com/rackspace/gophercloud/openstack/client.go, vendor/github.com/rackspace/gophercloud/pagination/pager.go
This commit updates gophercloud to 67139b9.  The ciao-vendor tool has also been enhanced.  A new command called 'uses' has been added.  This allows the user to determine which of ciao's dependencies, including ciao itself, uses a given package.  It's important to know this when updating a vendored package as there may be complications if that package is used by more than one of ciao's dependencies.
=> ciao-vendor: Add uses command and update gophercloud

ciao-controller/main.go, ciao-launcher/main.go, testutil/identity.go
This PR includes all the changes required in launcher, controller, fake keystone services required to run ciao in a single vm as described in https://github.com/01org/ciao/issues/125
However this PR does not includes the changes required in the scheduler. This should not cause any issues to existing functionality. How to completely implement the Single VM setup the scheduler code needs to support dual role launchers.
=> Topic/singlevm: Single VM Development and Test Environment Support

.travis.yml, ciao-vendor/ciao-vendor.go
This PR fixes two issues #197  and #198.  PR #194 managed to introduce a gocyclo error as the .travis.yml file was not running the static analysis tools on ciao-vendor.  This patch fixes the gocyclo error and the .travis.yml file.
=> Fix static analysis issues with ciao-vendor

ciao-cert/main.go, ciao-launcher/tests/ciao-launcher-server/server.go, ciao-scheduler/scheduler.go, networking/ciao-cnci-agent/test_cnci_server/server.go, ssntp/client.go, ssntp/example_server_test.go, ssntp/examples/server.go, ssntp/forward.go, ssntp/frame.go, ssntp/server.go, ssntp/session.go, ssntp/ssntp.go, ssntp/ssntp_test.go, testutil/server.go
The Role is a typedef'd bitmask of an enumeration of constant values.
But much of the code directly accessed the underlying integer, with a
variety of casting involved.  By removing all the integer typing and
adding some accessor/test functions, the casts go away and and some code
reads more succintly.  We get a more strongly typed object for "Role" that
can transparently change its underlying implementation in the future if
needed.
=> ssntp: make Role a more opaque type

ciao-controller/compute.go, ciao-controller/compute_test.go, payloads/compute.go
We need to allocate compute structure slices so that JSON
marshalling produces an empty slice and not a nil pointer
when they represent empty lists.
Fixes #166
=> ciao-controller: Use specific constructors for compute structures

ciao-scheduler/scheduler.go, ssntp/server.go
Split out a helper to update a nodeStat.
With StatusNotify() including a role parameter, the helper function can be
simply called for each relevant role, instead of having to check all maps
for the uuid passed in the already existing StatusNotify() parameter list.
=> ciao-scheduler: refactor StatusNotify() for combo role AGENT|NETAGENT

ssntp/example_server_test.go, ssntp/frame.go, ssntp/session.go, ssntp/ssntp_test.go
Origin tracks the first creator and sender of an SSNTP frame.
This allows for any frame receiver to track who the first sender is, even across SSNTP forwarding.
No significant throughput regressions were identified with this new field added to the SSNTP frames.
=> ssntp: Add SSNTP Frame Origin field

ciao-controller/main.go
In --single mode the controller records the dynamically generated
identity information in the log files. However this information is
not available to the user till the logs are flushed.
To ensure that test scripts and the user can retrieve this
information immediately after the ciao-controller is started
the log buffer needs to be flushed.
=> ciao-controller: Flush the indentity strings

.travis.yml, ciao-scheduler/scheduler.go, configuration/configuration.go, configuration/configuration_test.go, configuration/driver.go, configuration/etcd.go, configuration/file.go, configuration/file_test.go, ssntp/server.go, ssntp/ssntp.go
New configuration package is added in order to handle
the yaml cluster configuration provided to the
scheduler.
Implements part of issue #66 
=> configuration: Add config package to handle cluster configuration

testutil/singlevm/cleanup.sh, testutil/singlevm/run_controller.sh, testutil/singlevm/run_launcher.sh, testutil/singlevm/run_scheduler.sh, testutil/singlevm/setup.sh
This commit includes a simple set of scripts that can be used
to perform a quick sanity check to ensure that ciao is
fully functional in a single VM setup.
The scripts handle the following
- Generation of certificates
- Generation of the CNCI Image
- Starting the Controller, Launcher and Scheduler
- Launching of Clear Container and Docker workloads
- Checking for docker and clear container networking
Assumptions:
- Docker and Clear Cloud images are setup properly
- The VM is running with hairpin mode enabled
Future Changes:
- Error checking
- Obtaining user input for relevant parameters
- These scripts check ssh and docker network connectivity
but the caller needs to visually verify. This will need to
be automated
=> testutils: Simple automated single VM test scripts

configuration/configuration.go, configuration/configuration_test.go, configuration/file.go
Minor modification for API consistency sake:
- Payload takes a blob and returns a payload
- ExtractBlob return variable is called a blob
=> configuration: Consistency fixes

configuration/configuration.go, configuration/configuration_test.go, configuration/file_test.go, payloads/configure.go
Based on requirements for CIAO Minimal Config Package, we need
to have some default initial values:
https://github.com/01org/ciao/issues/66
Below are the config package related (In-Progress) PRs:
config_package PR:  https://github.com/01org/ciao/pull/149
config_launcher PR: https://github.com/01org/ciao/pull/168
=> configuration: Add Init method for Configure payload default values

configuration/configuration.go
On single physical interfaces, the network will autoconfigure
itself.
=> configuration: Compute and Mgmt subnets are not mandatory

ciao-launcher/README.md, ciao-launcher/instance_test.go, ciao-launcher/main.go
Add config package support for enabling Scheduler-provided cluster
configuration.
ciao-launcher start commands should look like:
```
$ ./ciao-launcher --cacert=/path/to/cacert --cert=/path/to/cert \
--server=<server-ip> --network=<cn|nn>
```
The options that were removed are:
```
--compute-net
--mgmt-net
--disk-limit
--mem-limit
```
Implements part of issue #66
Above configurations are provided by Scheduler at launch stage.
=> ciao-launcher: Add Config package support for  ciao-launcher

ciao-launcher/overseer.go, ciao-launcher/overseer_test.go, test-cases/test-cases.go
This commit adds some unit tests for ciao-launcher's overseer go routine.  This brings launcher's test coverage up to 30%.  The PR also contains a fix for #26.  The bug was easily reproducible with the new tests so it needed to be fixed to avoid these new tests failing periodically.  Finally, #184 is also fixed.  test-cases now prints out the contents of stderr, if one of the packages fails its unit tests.  This needed to be fixed to help debug the failing overseer test cases in travis.
=> Add overseer unit tests and fix two bugs

ciao-controller/README.md, ciao-controller/compute.go, ciao-controller/controller_test.go, ciao-controller/main.go
Add config package support for enabling Scheduler-provided cluster
configuration.
ciao-launcher start commands should look like:
```
$ ./ciao-controller --cacert=/etc/pki/ciao/CAcert-example.com.pem \
--cert=/etc/pki/ciao/cert-Controller-localhost.pem --url example.com
```
The options that were removed are:
```
-computeport
-httpscert
-httpskey
-identity
-password
-username
```
Implements part of issue #66
Above configurations are provided by Scheduler at launch stage.
=> ciao-controller: Add Config package support for ciao-controller

ciao-launcher/overseer_test.go
Add the ClusterConfiguration method to overseerTestState to fix the
ciao-launcher unit tests.
=> ciao-launcher: Fix unit tests

.travis.yml, configuration/configuration_test.go
Scheduler can/should run as non-root, but assumes then that packaging has
created its logdir.  In the case of CI our .travis.yml represents the
packaging and needs to create the directory.  This removes a number of
annoying warnings that pop in logs during test.
=> travis: make logdir for scheduler

configuration/configuration_test.go
An inverted condition in an expected-to-fail test case was resulting in
a t.Fatalf(nil) sometimes.  Obviously we shouldn't print a value that
was just verified to be nil.  While I'm at it, I also clarified the
comments around the conditions.
=> configuration: fix false failure bug

ciao-scheduler/scheduler.go, configuration/configuration_test.go
Workload starts fail if no compute nodes are connected.  Same for network
workloads if no network nodes are connected.  This is different than if
nodes are connected, but don't have sufficient resources.  But it did not
show clearly in logs.  These two glog messages should add debugging of
cluster config/setup/test.
=> ciao-scheduler: glog distinct messages for no cn/nn connected

data/systemd/ciao.conf
let systemd take care of the VMs data directory
(/var/lib/ciao/datastore) creation at boot time.
=> data: Add datastore directory for DB files.

ciao-controller/workloads/docker-ubuntu.yaml
The latest ubuntu image does not support python3. Change the cloud
init to a simple bash script which does an infinite loop so that
the container can be verified as running for test purposes.
Fixes: #246
=> ciao-controller: workloads: change docker ubuntu latest workload

README.md
This commit supersedes #218.  It contains the original automated commit from waffle plus a separate commit from me that moves the badge to the correct location in the README.md file.  I decided to leave the original waffle commit intact even though it doesn't have a signed-off by field.  I thought we might make an exception for bots.  If this isn't acceptable I'll squash the two commits and re-push.
=> README.md: Add Waffle badge

testutil/singlevm/setup.sh
It uses ciao-cli and the ciao-cli syntax has changed, see
PR #224 https://github.com/01org/ciao/pull/224.
=> testutil: Fix the singleVM setup script

ciao-cli/README.md
- No need to pass the user and password for unprivileged operations
- Add a missing '`' for proper formatting
=> ciao-cli: Fix README typos

CONTRIBUTING.md
Our backlog and workqueue are now officially in waffle.io.  We have the
front page badge to prove it.
=> documentation: note waffle.io connection

ciao-vendor/ciao-vendor.go, vendor/github.com/vishvananda/netlink/addr_linux.go, vendor/github.com/vishvananda/netlink/class_linux.go, vendor/github.com/vishvananda/netlink/filter.go, vendor/github.com/vishvananda/netlink/filter_linux.go, vendor/github.com/vishvananda/netlink/handle.go, vendor/github.com/vishvananda/netlink/link.go, vendor/github.com/vishvananda/netlink/link_linux.go, vendor/github.com/vishvananda/netlink/neigh_linux.go, vendor/github.com/vishvananda/netlink/nl/nl_linux.go, vendor/github.com/vishvananda/netlink/nl/tc_linux.go, vendor/github.com/vishvananda/netlink/nl/xfrm_linux.go, vendor/github.com/vishvananda/netlink/nl/xfrm_state_linux.go, vendor/github.com/vishvananda/netlink/protinfo_linux.go, vendor/github.com/vishvananda/netlink/qdisc_linux.go, vendor/github.com/vishvananda/netlink/route.go, vendor/github.com/vishvananda/netlink/route_linux.go, vendor/github.com/vishvananda/netlink/rule_linux.go, vendor/github.com/vishvananda/netlink/xfrm.go, vendor/github.com/vishvananda/netlink/xfrm_policy.go, vendor/github.com/vishvananda/netlink/xfrm_policy_linux.go, vendor/github.com/vishvananda/netlink/xfrm_state.go, vendor/github.com/vishvananda/netlink/xfrm_state_linux.go, vendor/github.com/vishvananda/netns/LICENSE, vendor/github.com/vishvananda/netns/README.md, vendor/github.com/vishvananda/netns/netns.go, vendor/github.com/vishvananda/netns/netns_linux.go, vendor/github.com/vishvananda/netns/netns_unspecified.go
Four changes here:
1. Update github.com/vishvananda/netlink to the latest version.  Fixes #256.
2. Vendor github.com/vishvananda/netns as required by the latest version of github.com/vishvananda/netlink.
3. Add a new command to ciao-vendor, updates, that identifies which vendored packages need to be updated.
4. Removed some unused code from ciao-vendor.go.
I've tested on the single-machine setup.  No obvious regressions.
=> 3rd Party: Update networking dependencies and add ciao-vendor improvements

.travis.yml
Travis will release to github if we have a deploy step. This patch
triggers a deployment whenever master is tagged. Prior to doing the
release, the tag message is output to a file so that it can be included
as a release artifact (attachment).
=> travis: add before_deploy and deploy steps

.travis.yml
The release notes artifact is not getting attached. Use an absolute
path to see if that solves the problem.
=> travis: use absolute path for release notes location

ssntp/ssntp_test.go
Travis misspell is flagging "emtpy".
=> misspell: trivial typo fix

testutil/singlevm/setup.sh
Don't break if/when reading the "latest" file and
https://download.clearlinux.org/image/ races against a publication
of changes to those two directories.
Switch to downloading from the releases location which should
be available
=> Single VM Dev: Fix race condition in image download

networking/libsnnet/utils.go
Exclude KVM bridges as valid management and compute interfaces.
This allows for seamless auto configuration on hosts where
kvm installation results in the creation of virtual networks
and their corresponding bridges.
This issue crops up because we recently allowed bridges to be used 
as valid network interfaces for compute and management traffic.
Longer term we should consider allowing any interface as a valid 
interface as long as it falls in the configured subnet.
This change allows ciao to be used with no configuration if all the
nodes are single homed.
Fixes issue https://github.com/01org/ciao/issues/272
=> networking: exclude kvm bridges as network interfaces

.travis.yml
We don't need to use GOPATH as travis should checkout our
repo into the root.
=> travis: get annotated tag from root

ciao-vendor/ciao-vendor.go
Ciao-vendor has a new test command that allows users to run the unit tests of a specific version of a given package.
=> ciao-vendor: Add test command

ciao-controller/command.go, ciao-controller/compute.go, payloads/compute.go
Add compatibility for CIAO Compute API for /v2.1/{tenant_id}/servers
for method POST, the calls and results should be in same format as
Nova to be fully compatible with OpenStack.
=> Add compatibility for Compute API /v2.1/{tenant_id}/servers POST

ciao-controller/internal/datastore/sqlite3db.go
When running ciao-cli instance add -workload not-a-workload the error
returned is not clear on the cause of it.
Fixes #292
=> ciao-controller: Return a meaningful error when workload does not exist

ciao-vendor/ciao-vendor.go, ciao-vendor/packages.json
Add some new commands to ciao-vendor to make it easy to use.  No longer do you need to manually edit the source code or remove directories from the vendor source tree.  This PR adds three new commands, vendornew for vendoring a new package, revendor for updating the version of an existing package and unvendor to unvendor a given package.
The database of vendored repositories has been moved from the source file to a separate json file stored in the ciao-vendor directory, called packages.json.  This file needs to be committed any time you vendor, unvendor or revendor anything.
=> ciao-vendor: Add vendornew, revendor, unvendor

test-cases/test-cases.go
test-cases was incorrectly treating skipped unit tests as tests that
had failed, or rather tests that had not run.  This resulted in skipped
unit tests failing the travis build, which is not really what we wanted.
Fixes #296
=> test-cases: Don't treat SKIP as an error

ciao-controller/compute_test.go, ciao-controller/controller_test.go, ciao-scheduler/scheduler.go, ciao-scheduler/scheduler_internal_test.go, testutil/README.md, testutil/agent.go, testutil/agent_test.go, testutil/client_server_test.go, testutil/controller.go, testutil/controller_test.go, testutil/payloads.go, testutil/server.go, testutil/server_test.go
This adds to scheduler's test coverage by leveraging the example in the testutil client-server test.  Scheduler coverage goes up from something like 63 to 75% percent.
Additionally some refactoring of testutil/ is done in response to bugs noted when I started using it for scheduler test coverage.
=> Unittests: use testutil in ciao-scheduler's testing

ciao-cli/instance.go
ciao-cli instance list output shows a detailed information for
each instance that is running taking 1 line per property making
the output difficult to digest by humans trying to seek fast the
instance of interest. For example:
```
Instance #1
UUID: 37089506-dfc4-411c-ae57-c261ef891a7f
Status: running
Private IP: 172.16.0.3
MAC Address: 02:00:ac:10:00:03
CN UUID: 1d1f0791-eb93-4947-893f-8b325433dea7
Image UUID: 73a86d7e-93c0-480e-9c41-ab42f69b7799
Tenant UUID: effa268c7350464797e2794b798658aa
SSH IP: 192.168.10.180
SSH Port: 33003
```
This commit makes instance list print a table with the most relevant
information of each instance as a field, taking 1 line per instance.
For Example:
```
1 37089506-dfc4-411c-ae57-c261ef891a7f running 172.16.0.3 192.168.10.180 33003
2 …
```
=> ciao-cli: reduce the output of ciao-cli instance list

_release/bat/release_test.py
ciao-cli instance list no longer show all instances details, we
need to call ciao-cli instance list -detail instead.
=> release: Adapt for ciao-cli instance list change

test-cases/test-cases.go
1. The first commit fixes #295.  Test-cases now collects the logs of failing tests cases and outputs them to standard err when all tests have been run.
2. The second fixes issue, #307, which is a hang that could occur if you specified the packages to test in a certain order.
=> test-cases: Fix two bugs

testutil/singlevm/setup.sh
We need to add the -detail option to get the legacy output
format.
=> testutil: Adapt singlevm setup script to new ciao-cli output

ciao-controller/compute.go
This pull requests is to set the proper http error return codes when something goes wrong in the controller.
Here we define the type errors 
- StatusNotFound
- StatusInternalServerError
- StatusUnauthorized
- StatusBadRequest
- StatusServiceUnavailable
A complete reference for net/http module can be found in https://golang.org/pkg/net/http/
This series of commits are split by entities handled by CIAO-CONTROLLER, same functionality but I prefer to keep them separated for each one :
- Servers
- Flavors
- Tenants
- Nodes
- Events
- CNCI
- Trace
=> ciao-controller: set proper http error return codes

ciao-controller/compute.go
When asking for a specific instance details or a list of instances
details, the status string for a running instance should be
consistent.
Then, for OpenStack compatibility sake, we want this string to
be 'active' and not 'running'.
Fixes #323
=> ciao-controller: All running instances status should be 'active'

ciao-controller/command.go, ciao-controller/compute.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-launcher/tests/ciaolc/ciaolc.go, payloads/compute.go, payloads/stats.go, testutil/payloads.go
- Align the STATS instance status strings with the compute API ones
- Only use the payloads defined constants for manipulating instance statuses
- Redefine ComputeStatusRunning to "active"
=> Fix instance status strings inconsistency

ciao-controller/controller_test.go, ciao-controller/main.go, ciao-launcher/main.go, ssntp/ssntp.go
This change adds value to our Zero Configuration approach in CIAO
project. It sets --cacert and --cert as optional parameters.
Examples:
- When starting ciao-launcher:
$ ciao-launcher
- When starting ciao-controller:
$ ciao-controller
That's all, no more args. SSNTP certificates are auto-discovered
from /etc/pki/ciao path. It's important to mention that, if we
have more than 1 SSNTP certificate, it will fail.
=> ssntp: Add smart default certificates finding

.travis.yml, test-cases/test-cases.go
The following two commits improve test-cases integration with travis in two ways:
1. An optional -v parameter is added.  When specified test-cases prints out the name of the package it is about to test.  Previously, test-cases didn't output anything until unit tests for all packages had finished.  But this mean that all tests needed to finish in under 10 minutes otherwise travis would cancel the build.  If you specify the -v option you give each package 10 minutes to complete it's tests.
2. The timeout option has been added which can be used to cancel the unit tests for a given package after a given amount of time.  The underlying go-test executable is terminated with a SIGABRT, which allows us to capture the stack trace.  This option is useful to cancel the unit tests for packages that …
=> test-cases: Deal with the travis time out and hung tests

ciao-launcher/docker.go, ciao-launcher/hard_reset.go, ciao-launcher/main.go, ciao-launcher/qemu.go
This commit consolidates all of the code for hard-reset
into one file.  Previously the code was spread throughout launcher
which wasn't ideal, particularly as the functions dockerKillInstance
and qemuKillInstance were stored in files reserved for the instance
go routine, even though these functions are called by the main
go routine.
Fixes #3
=> ciao-launcher: Move hard-reset code to own file

ciao-launcher/README.md, ciao-launcher/delete_instance.go, ciao-launcher/instance_test.go, ciao-launcher/main.go, ciao-launcher/restart_instance.go, ciao-launcher/start_instance.go, testutil/singlevm/run_launcher.sh
-network is now a bool parameter and it defaults to true.  Previously, it
was an emumerated type that accepted none, cn, nn, or dual.  But these
additional values are no longer needed as SSNTP can deduce the role
from its certificates.  Another important note is that -network defaults
to true.  Previously, if the networking flag was unspecified, networking
was disabled.  This default behaviour was left over from the early days
of ciao when we were integrating networking.  Networking on by default
is now the sensible choice.
Fixes #162
=> ciao-launcher: Update the -network parameter

_release/ciao-release/main.go
ciao-release is a small program which will generate the release
notes for ciao releases. It uses the github api to obtain
the list of pull requests closed on the master branch since
the time of the last tag, up to the release candidate sha. The rc
sha must be passed in as a string argument. It also gets the list of issue
events since the last tag and reports any closed issues.
Finally, it gets the list of all commits since the last tag.
The lists are output into a plain text file that is called
"release.txt". This file is used to create an annotated tag
for the next release.
=> release: add release notes generator to ciao tree

configuration/configuration.go, configuration/configuration_test.go
we don't support image service at this point, so it doesn't
make sense to enforce this value in the configuration setup.
This commit removes checking the ImageService URL from being
present in a minimal configuration yaml.
=> configuration: image service URL not mandatory

ciao-launcher/main.go
Removing unecessary asigment to chanel and also return, since
after the if the asigment to the chanel dialCh still is valid and
the return is not necessary cause the left asignment of dialCh is the
last instruction and the anonymous function ends.
=> ciao-launcher: remove unecessary asigment of chanel and return

ciao-controller/compute_test.go, ciao-controller/controller_test.go, ciao-scheduler/scheduler.go, ciao-scheduler/scheduler_internal_test.go, ciao-scheduler/scheduler_ssntp_test.go, ssntp/ssntp_test.go, testutil/agent.go, testutil/client_server_test.go, testutil/controller.go, testutil/identity.go, testutil/payloads.go, testutil/server.go
This series adds a bunch of bugfixing in test cases in ciao-controller, ciao-scheduler and testutil for issues observed will adding coverage for SSNTP ConcentratorInstanceAdded, TenantAdded, TenantRemoved and PublicIPAssigned event flows.
=> Unittests: more ssntp event flows

ciao-launcher/instance.go, ciao-launcher/main.go
This PR contains two commits that
1. Update the statistics reporting interval to 6 seconds, the value used in the demo branch.
2. Fixes the cpuprofiling in launcher by ensuring that pprof.StopCPUProfile is called.
=> ciao-launcher: Update statistics interval and fix profiling

ciao-controller/compute.go
tenantServerAction function was acting on instances when a list of
servers was provided, the function now validates that if a servers
list is provided then ensure it belongs to the tenant specified
before proceeding to the action.
Fixes #98
=> ciao-controller: check instances in list belong to tenant

ciao-controller/controller_test.go, ssntp/client.go
This PR is a partial response to issue 83.  That issue included 5 data race reports from go-race.  2 no longer reproduce with my earlier unit test cleaning.  2 are fixed here.  1 remains in discussion with @kaccardi 
The two races fixed here are fairly straight forward:  an anonymous function goroutine was sharing unprotected data with its parent in an actually safe fashion imho but easily resolved with a channel, and ssntp clients usage of waitgroups could theoretically race due to no exclusion of readers/writers.
=> Unittests: race fixes

ciao-launcher/qemu.go, ciao-launcher/qemu_test.go
This PR contains 3 commits that provide some unit testing for the code that manages qemu instances.  This code in itself is quite hard to test as we don't really want to launch qemu instances or create ISO or qcow images in our unit tests.  The tests then validate that that the go routines that manage qemu instances are working correctly, that ciao-launcher parses the result of qemu-img correctly and that it generates command line parameters for qemu as expected.
=> ciao-launcher: Add qemu_test.go

ciao-launcher/main.go, ciao-launcher/profile.go
This commit adds tracing support to ciao-launcher.  When built with the
profile tag a new flag is added called --trace.  This flag can be used
to provide a file into which trace data can be written.  The data can
be analysed at a later stage using go tool trace.
=> ciao-launcher: Enable tracing

ssntp/README.md, ssntp/ssntp.go, ssntp/ssntp_test.go
The AttachVolume and DetachVolume commands will be
typically sent by ciao-controller down to ciao-launcher
in order to respectively attach and detach storage
volumes to running instances.
=> ssntp: Add volumes attaching and detaching commands

ciao-cli/README.md, ciao-cli/main.go
When user is part of more than one project (tenant), it
allows to use environment variables for passing the proper
project name instead of using the ``tenant-name`` or ``tenant-id``
parameters in ``ciao-cli`` command. It would verify if the
``CIAO_TENANT_NAME`` environment variable exists, it would use it;
if not, everything would normally proceed.
=> ciao-cli: Add tenant name evironment variable

ciao-controller/controller_test.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/openstack_volume.go, ciao-controller/types/types.go, payloads/start.go
Add a definition of a storage resource that may be requested
as one of the RequestedResources in our start payload.
Modify ciao-controller workloads to include storage resources.
Modify ciao-controller to generate yaml for storage resources.
=> ciao-controller: modify payloads to include storage resource

ciao-cli/main.go, ciao-cli/volume.go, vendor/github.com/rackspace/gophercloud/openstack/blockstorage/v2/volumes/doc.go, vendor/github.com/rackspace/gophercloud/openstack/blockstorage/v2/volumes/fixtures.go, vendor/github.com/rackspace/gophercloud/openstack/blockstorage/v2/volumes/requests.go, vendor/github.com/rackspace/gophercloud/openstack/blockstorage/v2/volumes/results.go, vendor/github.com/rackspace/gophercloud/openstack/blockstorage/v2/volumes/urls.go, vendor/github.com/rackspace/gophercloud/openstack/blockstorage/v2/volumes/util.go
Cinder is a block storage service for OpenStack
Added commands are:
ciao-cli volume [add list show update delete]
Signed-off-by: Alberto Murillo alberto.murillo.silva@intel.com
=> ciao-cli: Add Cinder support

ciao-launcher/attachvolume_error.go, ciao-launcher/attachvolume_instance.go, ciao-launcher/detachvolume_error.go, ciao-launcher/detachvolume_instance.go, ciao-launcher/instance.go, ciao-launcher/instance_test.go, ciao-launcher/main.go, ciao-launcher/payload.go, ciao-launcher/payload_test.go, ciao-launcher/start_instance.go, ciao-launcher/vmconfig.go, payloads/attachvolumefailure.go, payloads/attachvolumefailure_test.go, payloads/detachvolumefailure.go, payloads/detachvolumefailure_test.go, testutil/payloads.go
The commit updates the original payload structures and errors added for the AttachVolume and DetachVolume commands.  It also adds contains the first storage commit for launcher.  This commit modifies launcher to accept the AttachVolume and DetachVolume commands and to update its internal instance state accordingly.
=> payloads, ciao-launcher: add storage plumbing

ciao-launcher/overseer.go, networking/libsnnet/cn_test.go
The misspell tool in travis has detected misspellings in the
ciao-launcher and networking code. Correct the spelling so that
travis will pass.
=> Fix misspell errors in ciao-launcher and networking.

testutil/client_server_test.go
Because this test code is using ssntp, which uses glog, you
must call flag.Parse prior to using ssntp.
=> testutil: call flag.Parse in TestMain

.travis.yml
This commit forces the docker version used in travis to be 1.11.2-0~trusty.
It seems that some of the network unit tests are not working with the
latest version of docker.
=> travis: Fix build by restricting docker version.

.travis.yml
In commit 33f421fa357563eecc6b3641cec7949caacdc008 I added a mkdir
in the travis yaml file for the scheduler logs.  It looks like I copy
pasted the line above and appended the log directory.  I should have
also changed /etc/pki to /var/lib.
=> travis: make logdir for scheduler in non-stupid location

networking/ciao-cnci-agent/scripts/README.md, networking/ciao-cnci-agent/scripts/generate_cnci_cloud_image.sh
Attempting to follow the README and run the script, I bumped into a couple
minor issues:
The image is downloaded by default, so describe how to download the image
and to where.  (Alternatively, could simplify the README by using the
"--download" option.)
Depending on OS specifics, the /dev/nbd0p* might not be created.  Running
'partprobe' is a fairly linux-OS-agnostic way to get them.  Given the
script currently only deals with raw format images, we could also simply do
a loopback mount and not deal with nbd and qemu-nbd, but I'm guessing
qemu-nbd is used to be better ready in the futue to handle qcow format
images in addition to raw?
=> ciao-cnci-agent: minor fixups

payloads/assignpublicIP.go, payloads/compute.go, payloads/configure.go, payloads/evacuate.go, payloads/publicIPassigned.go, payloads/start.go
In the past, some variables where added with a generic description
as "<variable> is reserved for future use". This commit contains all
new proper descriptions for the variables. With this change we ensure
our documentation is aligned to the development standard guideline
ciao is following.
Fixes #397
=> payloads: document all variables with missing proper description

ciao-image/main.go
Without the '/' ciao-image tries to GET https://localhost:35357v3/
which is obviously wrong.
=> storage: image server needs trailing '/' on its keystone url

.travis.yml, ciao-controller/compute_test.go, ciao-controller/controller_test.go, test-cases/test-cases.go, testutil/agent.go, testutil/agent_test.go, testutil/client_server_test.go, testutil/controller.go, testutil/controller_test.go, testutil/export_test.go, testutil/server.go, testutil/server_test.go
This PR enables -race in the test-utils helper and toggles it on for non-controller tests in travis (controller has known races).  Some observed bugs in testutil's results channels' locking is cleaned up.
Fixes Issue #235
=> Unittests: locking fixes and race hunting

ciao-cli/identity.go
When a tenant is not specified in the cli or environment variables,
ciao-cli uses getTenant function to fetch the tenantName and
tenantID the user belongs to.
getTenant was not handling the case where a user exists but does not
belong to any tenant resulting in an index out of range panic.
This commits handles this scenario and fails properly.
Fixes: #433
=> ciao-cli: Handle the case where a user does not belong to a tenant.

testutil/singlevm/configuration.yaml, testutil/singlevm/dnsmasq.conf.macvlan0, testutil/singlevm/setup.sh
This change adds the following features to Single VM:
- Auto macvlan interface creation with ``ip`` command
- DHCP Server setup with ``dnsmasq``
- When testing ssh connectivity, avoid fixed 7.2 openssh version.
This will help to accomplish #334
=> singlevm : Add networking automation (macvlan and DHCP Server)

ciao-launcher/main.go, ciao-launcher/network.go, ciao-launcher/tests/ciao-launcher-server/server.go, configuration/README.md, configuration/configuration_test.go, networking/libsnnet/utils.go, networking/libsnnet/utils_test.go, payloads/configure.go, payloads/configure_test.go, testutil/payloads.go
Both `compute_net` and `mgmt_net` can only represent one
subnet. This commit changes the configure scheme for
`compute_net` and `mgmt_net` to accept a list of subnets.
both values should be now a YAML list of subnets like:
```
launcher:
compute_net: [192.168.1.110]
mgmt_net: [192.168.1.0/24, 192.168.2.0/24]
```
or
```
launcher:
compute_net:
- 192.168.1.110
mgmt_net:
- 192.168.1.0/24
- 192.168.2.0/24
```
Fixes #232
=> configuration: fix configure scheme

networking/libsnnet/cn.go
When not passing compute or management subnets, one could
either use nil or empty slices.
Fixes #453
=> networking: Support both nil and empty subnet slices

.travis.yml
We suspect that the addition of this parameter has led to the instability
of our Travis builds over the last week or so.  Our code is simply not
yet ready to have race detection enabled on all tests.  Enabling race
detection also seems to mess up the line numbers in the stack traces,
making it difficult to pinpoint where code is panicing and hanging.
=> travis: Remove test-cases --race parameter

ciao-scheduler/scheduler_ssntp_test.go
The data race Kristen caught in https://travis-ci.org/kaccardi/ciao/jobs/151574113 is addressed here.
I've also got a patch for what is likely the test deadlock which appears very regularly these days "in" ciao-launcher.  The stack traces there show it's not really launcher's test, but really is due to the same old races in the testutil/ results channels that I've been chasing for a while.  A scheduler test was failing to fully shutdown a test instance of the ssntp server, which later caused issues when launcher's test tried to restart.
=> scheduler: more test code locking bugfixes

ciao-launcher/qemu.go
The commands to attach and detach a volume currently fail if the
UUID of that volume does not begin with a letter.  The UUIDs are
used in QMP device and drive names and the QMP commands to which
these names are passed can fail, if the UUIDs start with a number.
This patch fixes the issue by prepending, rather than appending,
drive_ or device_ to the volume UUIDs before that are used in QMP
ids.
=> ciao-launcher: Ensure qmp ids are valid ids

testutil/agent.go, testutil/client_server_test.go, testutil/controller.go, testutil/server.go
This PR has some more verbose output to aide debugging and a prospective deadlock fix in testutil agent/server shutdown.
=> testutil: race / deadlock hunting

ciao-launcher/instance_test.go
The code in instance_test.go that waited for the instance loop to close
down was incorrect.  There was a possibility of deadlock if the instance
loop was sending some stats down the overseer channel at the same time
as the test was trying to shut down the instance.  There is similar code
in the overseer which actually shuts down the instance loop correctly.
This commit simply ports the good overseer code over to instance_test.go.
Partial fix for #434
=> ciao-launcher: Fix unit test deadlocks

testutil/agent.go, testutil/controller.go, testutil/server.go
Some of our hangs look like they're in ssntp.Stop().  I stop the server
after disconnecting clients in tests, but I wonder if they still have
threads hanging around because the channel closing hasn't yet finished
because it wasn't actually started.  If the channel close happens before
the ssntp sessions are Close()/Stop()'d, then if the ssntp Close()/Stop()
were waiting for something to finish then that something has at least
been unblocked to finish.
=> testutil: close result channels before ending ssntp session

testutil/server.go
There's an event result write to the events channel in both the
EventNotify() and in the ConnectNotify()/DisconnectNotify() code paths,
but there will only be one read.  These writers will block and leak
goroutines.
=> testutil: connect/disconnect make 1 result on event channel

ciao-scheduler/scheduler_ssntp_test.go, testutil/agent.go, testutil/client_server_test.go, testutil/controller.go, testutil/server.go
This PR includes a patch that is a subset of a patch in the storage topic branch that's useful for debugging our odd test races.  The races now seem nearly gone but I'm still seeing a rare one where node disconnect event result senders appear to be blocked on a never read channel at server shutdown.  The print's help see which part of the series of disconnect/reconnects is failing.
And an additional patch which calls ssntp Stop() as a goroutine from a scheduler test case.
=> more test race / deadlock hunting

ciao-scheduler/scheduler_ssntp_test.go
The tests propagate event results through channels.  Writers to channels
block until a reader reads.  The reader of a node disconnect event result
doesn't start to read untils the reader code (after the server stop call)
actually runs, which it wont do if the server stop is not a go routine.  If
the stop code is blocked on sending to the channel and the reader only runs
when the stop code is complete (ie: because it is not stopping in a
goroutine) there's going to be a deadlock.
=> scheduler: goroutine ssntp Stop() in test case

ciao-controller/openstack_volume.go
Go vet was complaining about "composite literal uses unkeyed fields", so I
keyed the fields.
=> ciao-controller: fix trivial go vet warning

ciao-launcher/instance.go
This is just a temporary work around for testing the end to
end attach and detach commands.  The credentials need to be
retrieved in a different way going forward.
=> ciao-launcher: Add ceph credentials to the storage driver.

ciao-controller/client.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/openstack_volume.go, ciao-controller/types/types.go, openstack/block/api.go
Implement the block api interface for detaching a volume from
a running instance.
=> ciao-controller: add support for detach

openstack/block/api.go
The attachment var is probably frequently (especially today) empty so I
can't var.(string) in that case.
=> openstack block: don't cast nil

.travis.yml
This commit will spawn an additional build for each PR and commit to
ensure that ciao can be built with Go 1.7 and that the resulting binaries
pass their unit tests.
=> travis: Enable Go 1.7 builds.

ciao-controller/main.go, ciao-launcher/instance.go, ciao-launcher/main.go, ciao-launcher/tests/ciao-launcher-server/server.go, configuration/README.md, configuration/configuration.go, configuration/configuration_test.go, payloads/configure.go, payloads/configure_test.go, testutil/payloads.go
Add storage cluster configuration module that adds CephDriver fields for the storage url and cephx secrets to be passed from the ssntp configuration frame.
This address #462 and partially #388.
=> Storage cluster config handling

_release/bat/release_test.py, _release/bat/requirements.txt
Update BAT testing with proper ``tap`` package import and requirements file was added to easy install with ``pip2``
Dependencies can be easily installed with:
```
pip2 install -f requirements.txt
```
=> bat: Fix tap package import and requirements

openstack/block/api.go, openstack/block/api_test.go
update the openstack api unit tests to include one for the os-detach action.
=> add unit test for block api os-detach action

ciao-controller/internal/datastore/datastore_test.go
In all cases, if a test fails a check we should terminate the test
instead of continuing. Replace use of Error() with Fatal() in unit
tests. Also do not use Fatalf if we are not using a format string.
=> ciao-controller: datastore: use Fatal() for test errors

ciao-launcher/tests/ciao-launcher-server/server.go
This small patch allows launcher's test server, ciao-launcher-server, to be
used by launcher instances that have networking enabled, which is now the
default.
Fixes: #502
=> ciao-launcher: Fix ciao-launcher-server usage with --network

ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/openstack_volume.go, ciao-controller/types/types.go
Support storage of a name and description field with block data.
=> ciao-controller: add name and description to block_data

ciao-controller/controller_test.go
If we don't add the tenant limit correctly, do not proceed
with the test.
=> ciao-controller: check error on tenant out of bounds test.

.travis.yml, ciao-controller/compute.go, ciao-controller/main.go
Automation of API Documentation.
CIAO-Controller has a API that exposes CIAO methods through HTTPS, documentation will be changing frequently due to the changes and new features in CIAO. 
Swagger will  allow us to automate the process of Docs generations. When we nave a new release the documentation will be updated, and every new PR needs to be validated it does not break the documentation.
This PR is to validate no issues with new integrations and the generation of docs for the API.
=> ciao-controller: validate API docs with Travis

testutil/singlevm/setup.sh
This commit fixes the issue with hard coded SSH version validation
on Single VM.
```
if [[ "$ssh_check" == *SSH-2.0-OpenSSH_7.2* ]]
```
Now, it will validate against ``"*SSH-2.0-OpenSSH_*"`` which will be
more generic for future SSH versions.
Fixes #493 
=> singlevm: Fix hardcoded SSH version

ciao-controller/internal/datastore/datastore.go
Do not delete attachments based on stats without first checking
the instance ID.  This fixes a bug which caused the attachment
list to get deleted whenever a node with no volumes attached sent
stats. Remember to delete attachments from the persistent datastore
when it's time to remove them.
=> ciao-controller: datastore: update attachments correctly

ssntp/ssntp.go
We are not using an ioutil error:
ssntp.go:1252:11: ineffectual assignment to err
We should check for a non nil error instead.
=> ssntp: Fix ineffassign error

ciao-controller/controller_test.go, ciao-controller/openstack_volume.go
Prior to doing any work in the openstack_volume interface, make
sure that we have confirmed the tenant. If this is a tenant we
don't know about, we need to add them to our tenant list and
start up a cnci for them. This is permissible because they have
passed authentication already.
=> ciao-controller: confirm tenant in openstack volume interface

.travis.yml
The Go 1.6 builds are currently failing as the swagger documentation checks
require the latest version of ciao's dependencies to be downloaded to the
GOPATH and built.  Sadly, some of the latest versions of our dependencies,
notably docker, no longer compile with 1.6, and so the build fails.  This
commit simply disables the swagger checks on 1.6 builds.
=> travis: Fix Go 1.6 builds

ciao-controller/openstack_volume.go
OpenStack blockstorage v2 api state that the return value
for /v2/tenant/volumes/detail should be a list of volumes,
however, ciao was returning {"volumes":null}.
With this fix ciao now returns the correct response as
{"volumes": []}
=> ciao-controller: Return an empty volumes list

ciao-storage/ceph.go, ciao-storage/ceph_test.go
This is a trivial implementation of the missing delete function in our ceph
driver and addition of a simple test case.
=> storage: implement ceph block delete

ciao-cli/image.go, ciao-image/service/service.go, openstack/image/api.go
Image Upload was failing due a missing ``GetImage`` method that was required as the final request in the image upload process. New ``GetImage`` handler was added to ``ciao-image`` service.
Image Upload operation requires a final ``GetImage`` request in order to verify that new image is created.
=> ciao-image: Fix image upload operation

ciao-launcher/deps.go
The 'docker' package is being installed as a dependency to
get docker insalled in Ubuntu, however, the package needed
is 'docker-engine'
From apt-cache search docker
- docker - System tray for KDE3/GNOME2 docklet applications
- docker-engine - Docker: the open-source application container engine
Fixes #508
=> ciao-launcher: Fix docker dependency in ubuntu

ciao-cli/README.md, ciao-cli/identity.go, ciao-cli/main.go
With this change the CA certificate file used for communicating with
keystone and the controller can be specified:
a.) either on the command line with -ca-file,
b.) or with an envionment variable, CIAO_CA_CERT_FILE,
thus avoiding the need to import the certificate into you local store.
This change required switching from openstack.AuthenticatedClient() to
the lower level API in order to override the transport options on the
HTTP client.
Fixes #180
=> ciao-cli: Support specifying CA file in environment or command line

qemu/qemu.go
Or else LaunchQemu() ends up dereferencing a nil pointer and panic'ing.
=> qemu: Use null QMP logger when the logger parameter is nil

ciao-launcher/docker.go, ciao-launcher/instance.go, ciao-launcher/instance_test.go, ciao-launcher/payload.go, ciao-launcher/qemu.go, ciao-launcher/qemu_test.go, ciao-launcher/restart_instance.go, ciao-launcher/simulation.go, ciao-launcher/start_instance.go, ciao-launcher/tests/examples/start_legacy_volume.yaml, ciao-launcher/virtualizer.go, ciao-storage/block.go, ciao-storage/noop.go
This PR fixes some storage related issues in launcher.  The main change is provided by 70c4da3 which adds support to attaching volumes to launcher instances when they are started, i.e., when the instance is specified in the start workload.  Such instances can be live detached at a later stage if required.  Attaching the volumes on boot should be faster than live attaching as we do not need to rbd map the volume first.
The other commits rename a poorly named parameter in an interface that was inconsistently named among the types that implement that interface and also fix a gocyclo issue introduced by 70c4da3.
=> ciao-launcher: Support volume attach on start

.travis.yml
This should have been done when the qemu package was first submitted.
=> Travis: Enable qemu tests in travis

ciao-controller/main.go, ciao-launcher/main.go, ciao-scheduler/scheduler.go
osprepare.Bootstrap function was designed to install
dependencies required in all ciao cluster nodes but
was unused.
This change makes use of osprepare.Bootstrap() function
to install ceph cli on all nodes.
=> ciao-launcher: install bootstrap dependencies

ciao-launcher/docker.go
When there were multiple processes running inside the container the
reported memory and CPU usage values were incorrect as they only
reflected the first process created in the container.
This change makes use of the Docker ContainerStats API to obtain the
memory and CPU usage for a container.
This was tested by comparing the results from "ciaolc istats" with
"docker stats".
Fixes: #17
=> ciao-launcher: Use docker ContainerStats api to get memory and CPU usage

ciao-launcher/qemu.go
- Enable vhost support for instances
- Unify the qemu invocation between macvtap and tap
=> Networking: Enable vhost for instances

ciao-launcher/attachvolume_instance.go, ciao-launcher/detachvolume_instance.go, ciao-launcher/instance.go, ciao-launcher/instance_test.go, ciao-launcher/payload.go, ciao-launcher/qemu.go, ciao-launcher/qemu_test.go, ciao-launcher/start_instance.go, ciao-launcher/tests/ciao-launcher-server/server.go, ciao-launcher/tests/examples/start_legacy_volume_boot.yaml, ciao-launcher/vmconfig.go
This PR implements boot from volume in ciao-launcher.  When booting from volume, the ciao-launcher expects the image_uuid to be absent from the workload and for there to be at least one volume marked as bootable.  Instances booted from a ceph volume report 0MB disk usage in their statistics.
=> ciao-launcher: Implement boot from volume

.travis.yml
Modify our travis yaml to run openstack/block unit tests.
=> travis: enable testing for openstack block api package.

.travis.yml
Modify our travis.yml file to run test-cases on the openstack/identity
package.
=> travis: enable testing for openstack/identity

ciao-launcher/qemu.go, qemu/examples_test.go, qemu/qemu.go, qemu/qemu_test.go
LaunchQemu() now takes a Config structure that contains more
descriptive fields than raw qemu parameters.
LaunchQemu is now simpler to call and more extensible as supporting more
qemu parameters would mean expanding Config instead of changing the API.
=> qemu: Build qemu parameters from a configuration structure

ssntp/README.md
Added a link to the ciao-cert repo in the ssntp README to provided
instructions on certificate generation for ssntp.
Signed-off-by: John Andersen <john.s.andersen@intel.com>
=> Updated ssntp/README.md added link to ciao-cert

ssntp/examples/client.go, ssntp/examples/server.go
Examples in ssntp needed to be updated to work properly with the
latest version of the ssntp package. This patch brings the examples up
to date on the naming of the certificates from ciao_ca_cert to ca_cert
and usage of the Role struct needing to be changed to ssntp.Role.
Signed-off-by: John Andersen <john.s.andersen@intel.com>
=> Bring ssntp/examples up to date with latest API

ciao-controller/main.go, ciao-launcher/main.go, ciao-scheduler/scheduler.go, osprepare/distro.go, osprepare/distro_test.go, osprepare/main.go, osprepare/versions.go, osprepare/versions_test.go
Instead of writing to stdout/stderr directly, adopt the use of a glog
using abstraction similar to the qemu component.
Signed-off-by: William Douglas <william.r.douglas@gmail.com>
Address #504
=> osprepare: Add logging abstraction

testutil/singlevm/cleanup.sh, testutil/singlevm/setup.sh
This PR updates the singlevm scripts so that they can be used as a development environment.  In short:
1. The cluster is no longer torn down when the setup.sh exits.  Instead all we do is to delete the test instances created by setup.sh.  The cluster remains up and functional.
2. Some information is printed out when the script ends informing the user that he needs to source a file containing some environment variables needed to communicate with ciao and also to teardown the cluster.
3. The cleanup.sh script has been updated to correctly teardown the cluster.
The PR also fixes #518 which left bridges and tap devices hanging around.
=> Single VM: Fix dev environment

ciao-cli/main.go, testutil/singlevm/setup.sh
This PR fixes "singlevm" test mode to have valid certificates between cli and controller - a prerequisite for enabling TLS verification.
It then goes ahead and enables TLS verification between ciao-cli and ciao-controller.
=> Enable TLS verification between cli and controller

ciao-launcher/docker.go
This change uses the memory and CPU limits extracted from the START
payload and after converting to the units Docker requires updates the
Docker HostConfig.
Fixes: #16
=> ciao-launcher: Send memory and CPU limits to Docker

ciao-launcher/docker.go
PR #590 broke launching of docker containers by specifying an invalid cpu
period.  It was specifying the period in nanoseconds.  Unfortunately, docker
was expecting milliseconds.
=> ciao-launcher: Fix launching of docker containers.

qemu/qemu.go, qemu/qemu_test.go
The right qemu parameter is "security_model", not "security-model".
=> qemu: Fix security model typo

.travis.yml
Swagger is a tool used to generate documentation based on
declarative comments in the code, the problem with it was that it
had an issue with vendoring. We have fixed that issue in
https://github.com/yvasiyarov/swagger/pull/120
and now we can use our vendor directory. This fix was need because
we were bringing dependencies with 'go get' which in some PRs were
causing to fail for time outs, an issue aside of the PRs.
In this change we add the required argument to enforce to check for
vendor directory and remove the 'go get'.
=> documentation: enable swagger to use vendoring

ciao-storage/ceph.go
rbd image format 1 is deprecated but image
format 2 provides different image features
that are not compatible with the kernel rbd client.
This change uses image-format 2 and the layering
image feature which is the only image feature supported
by the rbd kernel client.
Fixes #528
=> ciao-storage: Use image-format 2

ciao-cli/README.md, ciao-cli/identity.go, ciao-cli/main.go
When enabling TLS, which this PR also does, this should allow configurations where keystone and controller cert are different (with one being in system store and the other on the command line.)
Tested against singlevm and against CNW cluster.
=> Merge supplied command line CA file with system pool

ciao-cli/main.go, ssntp/ssntp.go
Using the *Depth variants of the glog functions makes the log messages through the wrapper have the line number they were called at, not the line number inside the wrapper.
=> Fix logging wrappers to give correct source information

ciao-image/datastore/cache.go, ciao-image/datastore/datastore.go, ciao-image/service/service.go, openstack/image/api.go, openstack/image/api_test.go
This commit adds support for deleting images. Now, you will be able to
delete images with the command:
```
ciao-cli image delete -image 78306709-9720-417e-97c6-7b941cb5565b
```
If the operation was successful, you will get a 204 HTTP return code.
If not, it may return the proper error, for example a 404 error could
come when the image does not exist.
=> ciao-image: Add delete image support

ciao-launcher/README.md, ciao-launcher/attachvolume_instance.go, ciao-launcher/detachvolume_instance.go, ciao-launcher/docker.go, ciao-launcher/docker_test.go, ciao-launcher/instance.go, payloads/attachvolumefailure.go, payloads/attachvolumefailure_test.go, payloads/detachvolumefailure.go, payloads/detachvolumefailure_test.go
This PR adds storage support to docker containers.  It allows clients to attach ceph volumes to docker containers when the containers are created.  All containers are currently mounted as RW to the path /volumes/UUID where UUID is the uuid of the ceph volume.  It is not possible to Attach or Detach a volume to a container after it has been created.
Fixes: #527
=> Add storage support to docker containers

testutil/identity.go, testutil/singlevm/setup.sh
A series of basic acceptance tests are run on each CIAO release before it is tagged.  These tests were not passing inside the single VM for a number of reasons.
1. The testutil identify service was missing an endpoint.
2. The env variables needed by the BAT tests were not included in demo.sh
3. Some images were missing in /var/lib/ciao/images which mean that instance creation for certain workloads failed randomly.
The commits in this PR address these issues.  Note that the BAT tests have some python dependencies that need to be installed in your VM before the tests will run.  This is not currently done by the setup.sh script.
=> Single VM: Allow BAT tests to run inside the SingleVM

ciao-controller/main.go, ciao-controller/openstack_compute.go
The code to start the compute API service was using the const
defined in the openstack package for the compute service and not
allowing the value to be overriden via the configuration command.
Set the default value of ciao-controller's computeAPI port to be
that const from the openstack package and use this value for
starting the service.
=> ciao-controller: Honor compute API port override

ciao-storage/ceph.go
imageFeatures was appended as an argument when creating block
devices, however, it was incorrectly done as a single string
rather than an array so it caused failures when executing.
=> ciao-storage: correct args for CreateBlockDevice

ciao-controller/internal/datastore/sqlite3db.go
When getting tenants using getTenants make sure to get the
any block devices for those tenants.
=> ciao-controller: datastore: intialize tenant devices correctly

testutil/singlevm/cleanup.sh, testutil/singlevm/configuration.yaml, testutil/singlevm/run_launcher.sh, testutil/singlevm/setup.sh, testutil/singlevm/verify.sh
This PR makes some changes to the Single VM scripts.  The first set of changes focus on tidying up the scripts:
1. The cleanup code is now in one place.
2. Misleading instructions from the controller logs are no longer written to the screen
3. The code to remove all docker containers has been removed as it's not needed.
4. Fixed some other bugs related to cleanup
5. The standard tests run by setup.sh have been moved to a new script, verify.sh and are now optional.  This is desirable when using Single VM for development as you don't want to run these scripts each time you run ./setup.sh.
The second set of changes enable ceph inside Single VM.
Fixes PR #536
=> Single VM: Enable Ceph and script refactor

ciao-cli/authenticate.go, ciao-cli/identity.go, ciao-cli/image.go, ciao-cli/volume.go
The volume and image service were not passing the CA certificate,
specified either on the command line or via an environment
variable, down to gophercloud.  This meant that these services
could not work inside the Single VM.  As we now have three different
gophercloud services requiring the same authentication code, the
original code that implemented this feature for the identity service,
has been moved to a new function.
=> ciao-cli: Make volume and image service work with -ca-file

ciao-controller/main.go, ciao-controller/openstack_volume.go, configuration/configuration_test.go, payloads/configure.go, payloads/configure_test.go, testutil/identity.go, testutil/payloads.go
This commit does three things:
1. It adds the port of the volume service API to the ciao-configuration file.
2. It modifies controller so that it passes the cluster configured port number
to the identity service.
3. It updates the identity service so that it advertises the volume service.
=> controller, payloads, configuration, testutil: Enable volume service

openstack/image/api_test.go
Add the test case for uploading an Image. Basically, adds the new
HTTP PUT request to the list of image API tests.
This fixes #575
=> ciao-image: Add unit testing for uploadImage function

testutil/singlevm/setup.sh
Ensure that the $HOME/local directory used to cache the
images and scripts is always created if it does not already
exist
=> Single VM: Bug fix. Ensure local cache directory exists

testutil/singlevm/cleanup.sh
The ceph-demo docker container creates a new volume each time the container
is started.  This volume needs to be explicitly deleted.  It does not get
deleted when the container is deleted.  Overtime, this can lead to a
substantial waste of disk space.  This commit tells docker to delete the
volume created by the ceph-demo container when it itself is deleted.
=> Single VM: Fix a ceph related disk space leak

testutil/singlevm/setup.sh
Don't duplicate the mkdir of the ciao_bin directory, and instead
move the call to make the directory to the top of the script.
=> single-vm: move creation of ciao_bin directory

qemu/qemu.go, qemu/qemu_test.go
The QMP socket implementation does not support multiple clients sending
and receiving QMP commands. As a consequence we need to be able to
create multiple QMP sockets from the qemu package, so that at least we
can support a fixed number of QMP clients.
=> qemu: Support creating multiple QMP sockets

ciao-controller/internal/datastore/sqlite3db.go
The sqlite3 datastore currently makes fake storage requests for
every workload. this causes us to create a volume on every workload
start and impacts performance for workloads that did not want
a volume.
=> ciao-controller: datastore: do not make fake volumes for every workload

ciao-controller/types/types.go
This issue was identified by a new version of "go vet":
https://github.com/golang/go/commit/4940a8379096
=> ciao-controller: Fix duplicated json identifier in NodeStats

qemu/qemu.go, qemu/qemu_test.go
We add a new device driver, and also a name to the CharDev structure
this is needed for qemu to actually create the serial port on
the guest.
=> qemu: Add support for serial port addition

ciao-cert/README.md, ciao-cert/main.go
This PR adds a -dump to ciao-cert for obtaining useful details from the certificate
Fixes: #255
=> ciao-cert: Add -dump parameter

ciao-cli/image.go, ciao-controller/main.go, ciao-image/service/service.go, openstack/image/api.go, testutil/identity.go, testutil/singlevm/cleanup.sh, testutil/singlevm/run_image.sh, testutil/singlevm/setup.sh
This commit enables the image service in Single VM.  It also modifies Single VM to use the image service to manages the example images that it downloads.  Changes to the fake identity service, ciao-cli and the image service itself were required to enable this.
=> Single VM: Enable the image service

networking/ciao-cnci-agent/scripts/generate_cnci_cloud_image.sh, testutil/singlevm/setup.sh
Support specifing the location from which to download the CNCI.
This allows the user to specify any CNCI image location.
Usage:
./setup.sh -d -c https://download.clearlinux.org/demos/ciao/ -i clear-cnci-image.img
Note:
This needs to be done only for the first time as -d will blow
out the local image cache and download _all_ the images.
If the user has a cached images, the user can manually download the image
cd ~/local
curl -O https://download.clearlinux.org/demos/ciao/clear-cnci-image.img
./setup.sh -i clear-cnci-image.img
Invoking ./setup.sh will pick the default CNCI image
=> Single VM: Enhance single VM to support custom CNCI

networking/libsnnet/database.go, networking/libsnnet/docker_database.go, networking/libsnnet/docker_plugin.go
Make the networking database implementation generic so that it can be used to store data for any component in Ciao. This database implementation can be used to persist any table map, array, slice to a database backed by boltDB+gob.
We may want to consider moving this to a generic util package for ciao.
**Note: As the table name internally has changed, this will break
any in place update of the CN launcher. For a proper update
of the CN, it has to be hard reset to remove all instances
and the database cleaned up.**
=> Provide a generic database implementation.

.travis.yml, openstack/image/api.go, test-cases/test-cases.go
This commit adds test-cases support for the generation of TAP reports. It also takes
the oppurtunity to rationalize the options for specifying the output format.  There
is now one format option, --format, which accepts a number of different values;
html, tap, colour-text and text.  The default is colour-text.
This change requires a modification to the travis script that executes test-cases,
as the old formatting option used by travis.yml no longer exists.
=> test-cases, travis: Add support for TAP reports

openstack/compute/api.go, openstack/compute/api_test.go
Fixes #698 Set limit value when a pager is being used on servers/detail endpoint.
Returns correct number of instances in order for the pager feature to work on
ciao-webui.
Signed-off-by: Jorge Villalobos <jorge.villalobos.gutierrez@intel.com>
=> ciao-controller: api: Set 'limit' value properly for instances

ciao-cli/README.md, ciao-cli/event.go, ciao-cli/image.go, ciao-cli/instance.go, ciao-cli/node.go, ciao-cli/template.go, ciao-cli/tenant.go, ciao-cli/trace.go, ciao-cli/volume.go, ciao-cli/workload.go
This commit adds a -f parameter that accepts a go template to the following
commands:
- event list
- image list
- tenant list
- instance list
- instance show
- node list
- node show
- tenant list
- tenant show
- volume list
- volume show
- workload list
As an example, to print the name of the workload with an ID of
ca957444-fa46-11e5-94f9-38607786d9ec on might type
ciao-cli workload list -f '
{{- range .}}
{{- if eq .ID "ca957444-fa46-11e5-94f9-38607786d9ec" }}
{{- .Name | printf -}}
{{end -}}
{{end }}
'
The output would be
Docker Debian latest
Fixes: #690
=> ciao-cli: Make ciao-cli scriptable

ciao-cert/main.go, ssntp/ssntp.go
This should improve the readability of logging and error reporting. This
change also updates all the places which expected the trailing "-" and
adds it explicitly.
Fixes: #671
=> ssntp: Remove the trailing "-" from ouput from the Stringer

qemu/qemu.go
When creating a CharDevice, we need to add a "bus" parameter so that it can match the serial pci device previously created.
=> Add missing bus parameter for a CharDevice

ciao-cli/instance.go
The commits that sorted the result of the instance list command and
added template support for this command conflicted.  The automerge
done by github was insufficient and resulted in an unsorted slice
being passed to the user supplied template.  This commit simply
re-arranges the code a little bit to ensure that the instances processed
by the user template are sorted.
=> ciao-cli: Fix instance list template ordering

ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/types/types.go
Begin fixing some storage bugs with this first in a series of PRs. In this PR we simply replace the old no-op getWorkloadStorage with something real. No test workloads are added in this PR because there are other fixes needed to really get storage working.
=> ciao-controller: datastore: implement workload_storage table

ciao-cli/instance.go, ciao-controller/openstack_compute.go
Allow ciao-cli to report the attached volumes when displaying instance details.
Fixes #654
=> send volume attachments with server info

ciao-controller/internal/datastore/datastore.go
When we delete an instance, we should update the attachments list
to make sure any attachments are deleted and the volume state
is reset to available.
Possibly Fixes: #645
=> ciao-controller: datastore: update attachments when deleting instance

ciao-controller/instance.go
Rather than continuing on as if nothing had happened, let newConfig
fail when we fail to get storage information for the requested
workload.
=> ciao-controller: return error if getStorage fails

ciao-storage/ceph.go
Instead of using rbd import to create volumes from images,
use qemu-img convert.
=> ciao-storage: do not use rbd import

ciao-cli/instance.go
The api for deleting a server response with 204 in the case
of success, not 200.
Fixes: #652
=> ciao-cli: expect NoContent from instance delete

ciao-cli/main.go
This change moves the execution of common code that talks to keystone
and validates the tenant setup to after the subcommand arguments are
parsed but before the command itself is run.
This means you can get instant feedback of command line parsing errors
without any network induced delay.
Fixes: #747
=> ciao-cli: Parse the subcommand before identifying with keystone

ciao-launcher/qemu.go
Boot from volume only worked properly when launcher was run with the
--with-ui spice option.  Without this option, boot from volume instances
start, appear to be active, but don't actually boot.  The problem
was caused by the use of an incorrect PCI address for the rootfs.  The
PCI address for the rootfs is influenced by the --with-ui parameter
and launcher was not taking this fact into account.
Fixes: 751
=> ciao-launcher: Fix boot from volume

_release/bat/README.md
Update the README.md file to mention that the BAT tests can be run
with Single VM and that if you are using Single VM you can initialise
all the necessary environment variables by sourcing ~/local/demo.sh
=> bat: Mention Single VM in the README

ciao-controller/internal/datastore/datastore.go
The controller was incorrectly storing the instance ID in the tenant ID
field of the log table for instance deleted events.  This meant that it
was not possible for the user to view these events using ciao-cli event
list as events are filtered by tenant ID, and the IDs stored did not
correspond to any tenants.
Fixes #776
=> ciao-controller: Store correct tenant ID for instance deleted events

ciao-controller/client.go, ciao-controller/controller_test.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/types/types.go, payloads/start.go
This is some early enabling work for the "Images as Volumes" project. With this change volumes created from an image specified in a storage workload will be deleted when the instance itself is deleted.
=> Ephemeral boot from volume

networking/ciao-cnci-agent/scripts/generate_cnci_cloud_image.sh
We have a race potentially between losetup and partition existance.  This
probably is what the retry loop managed to kind of work around in the past.
The udevadm settle was in the wrong location previously.  It needs to come
after creation and before use.  It would have coincidentally in the past,
IF you were retrying.
We can simplify by not looping and rather create, wait, use as a simple
series of commands.
If we find subsequent issues that need more logic in this flow, I suggest
we remove the losetup and udevadm settle, and instead do "kpartx -sav
$img" followed by the mount.  Then also on exit do "kpartx -sdv $img".
=> ciao-networking: simplify cnci image preparation mount

openstack/image/api.go
This commit fixes broken web links to OpenStack Image service API references.
Fixes #543
=> openstack: Update image API broken web references

ciao-cli/image.go, ciao-image/service/service.go
This PR adds the missing ciao-cli image show command.  The functionality was already supported by the image service but there was no corresponding ciao-cli command.  Now there is.  In adding this command, a small problem with the image service was also fixed, in which an empty image was returned, instead of an error, the ID of a requested image did not exist.
The second commit adds a -f option to the ciao-cli image add command.  This will allow one to easily determine the IDs of newly created images.
Fixes #794
=> Add ciao-cli image show and templates to ciao-cli image add

_release/bat/README.md, _release/bat/base_bat/base_bat.go, _release/bat/base_bat/base_bat_test.go, _release/bat/image_bat/image_bat.go, _release/bat/image_bat/image_bat_test.go, bat/bat.go, bat/bat_test.go, ciao-cli/image.go
This PR adds a set of BAT tests for the image service that test:
1. Image add
2. Image upload
3. Image list
4. Image show
5. Image delete
There's a mix of positive and negative test cases.
Fixes #683
=> bat: Add image BAT tests

testutil/singlevm/setup.sh
The ciao-cli was not fully qualified in some cases.
Using fully qualified paths ensures we are testing against
what was built vs what is installed on the system.
=> Single VM: Fully qualify ciao-cli

_DeploymentAndDistroPackaging/ansible/roles/keystone/tasks/access.yml
The keystone role has a task to wait for port 5000 to be open before
trying to send request to create services, projects, etc. But there
is an issue with clearcontainers [1] where the port is reported to be
open even if the application has not been started inside the container.
This change adds a workaround to retry the Create custom project task
to avoid the scripts from failing when running in clearlinux with
clearcontainers.
[1] https://github.com/01org/cc-oci-runtime/issues/349
Fixes #788
=> ansible: Retry Create custom projects task

_DeploymentAndDistroPackaging/ansible/README.md
Previous to this commit, the instructions stated to install
Ansible, Go and other tools needed to deploy CIAO successfully.
This commit changes the deployment instructions to make use
of the `clearlinux/ciao-deploy` container instead, removing
all the depdendencies install steps.
=> ansible: update deployment instructions to use container

_DeploymentAndDistroPackaging/ansible/roles/ciao-common/tasks/main.yml
Add a separate task in order to create the /etc/systemd/system
directory and make sure it belongs to root.
Fixes https://github.com/01org/ciao/issues/820
=> ciao-deployment: Fix ownership of /etc/systemd/system

_DeploymentAndDistroPackaging/ansible/doc/development.md, _DeploymentAndDistroPackaging/ansible/roles/ciao-common/README.md, _DeploymentAndDistroPackaging/ansible/roles/ciao-common/defaults/main.yml, _DeploymentAndDistroPackaging/ansible/roles/ciao-common/tasks/main.yml
Ciao requires a ceph cluster to be available for all ciao nodes.
The deployment playbook requires that the systadmin provides ceph
configuration and secret files in order to configure ceph on all
ciao nodes.
This changes introduces `skip_ceph` variable which allows the deployment
to skip ceph configuration and leave that step to be performed manually
by the sysadmin.
Fixes #782
=> ansible: Optionally skip ceph configuration on ciao nodes

_release/bat/base_bat/base_bat_test.go, ciao-launcher/docker.go, ciao-launcher/instance.go, ciao-launcher/main.go, ciao-launcher/overseer.go
The BAT tests were failing consistently for me on a newly set up SingleVM.  There turned out to be three separate problems:
1. The DeleteAllInstances BAT tests was erroring out too early if instances were detected after the ciao-cli instance delete -all had been called.
2. #808 was causing launch failures.
3. The docker method client.ContainerStats was hanging sometimes.  This seems to be reproducible on a newer version of docker, 1.12.3.
The PR fixes all the issues above and the BAT tests are now working consistently in my SingleVM environment.
=> Fix a number of BAT test blocking bugs

_release/bat/README.md, _release/bat/image_bat/image_bat_test.go, _release/bat/storage_bat/ceph_test.go, _release/bat/storage_bat/storage_bat.go, bat/bat.go
Migrate ceph_test.go from ciao-storage to the BAT tests as this test requires a working ceph setup in order to be able to function.
More tests will be added when the ceph driver changes for images as volumes are added.
=> BAT testing for ceph storage backend

ciao-cli/README.md
There's been some confusion about how to use the new -f parameter
recently added to the ciao-cli command that accepts a Go template.  This
commit updates the README.md file of ciao-cli to provide more
information about how templates are used with this tool.  Numerous
examples have also been added.
=> ciao-cli: Add more template examples to the README.md

_DeploymentAndDistroPackaging/ansible/README.md, _DeploymentAndDistroPackaging/ansible/group_vars/all, _DeploymentAndDistroPackaging/ansible/roles/ciao-controller/README.md, _DeploymentAndDistroPackaging/ansible/roles/ciao-controller/defaults/main.yml, _DeploymentAndDistroPackaging/ansible/roles/ciao-controller/templates/workloads/test.yaml.j2
`ciao_guest_key` variable in
`_DeploymentAndDistroPackaging/ansible/group_vars/all`
points to a public ssh key file (default is ~/.id_rsa.pub)
which is used to access the VMs that ciao creates.
This commit changes the content of `ciao_guest_key` var
to actually contain the public ssh key instead of the key
path.
Fixes: #814
=> ansible: `ciao_guest_key` var to contain workload pubkey

_DeploymentAndDistroPackaging/ansible/roles/docker/tasks/install_fedora.yml
docker-py is required to interact with docker from python.
Ubuntu installs the package as dependency of docker-engine
but fedora doesn't
This change installs docker-py on fedora from the docker role.
=> ansible: Install docker-py on fedora from docker role

testutil/singlevm/cleanup.sh, testutil/singlevm/tables/workload_template.csv
The ubuntu container image on dockerhub has been slimmed down.
This break the automated tests as the network tools required for
testing are no longer found within the image.
Switching the test image to debian which has the required tools.
This fixes issue #844
=> Single VM: Switch the container test image to debian from ubuntu

ciao-cli/event.go, ciao-cli/image.go, ciao-cli/instance.go, ciao-cli/node.go, ciao-cli/template.go, ciao-cli/tenant.go, ciao-cli/trace.go, ciao-cli/volume.go, ciao-cli/workload.go
This PR adds two new functions to the template language understood
by ciao-cli:
- tojson outputs the specified object in json format, e.g., {{tojson .}}
- filter operates on an slice or array of structures.  It allows the caller
to filter the input array based on the value of a single field.
The function returns a slice containing only the objects that satisfy the
filter, e.g.
- select operates on a slice of structs.  It outputs the value of a specified
field for each struct on a new line , e.g.,
{{select . "Name"}}
ciao-cli image list -f '{{$x := filter . "Protected" "true"}}{{len $x}}'
outputs the number of protected images maintained by the image service.
The image list command was also modified to called the template utility
functions in template.go.  This was necessary to ensure that …
=> ciao-cli: Improve template functionality

_DeploymentAndDistroPackaging/ansible/ciao_computes.yml
While osprepare tells the compute node to install docker-engine, it does
not setup the docker repository.
This change runs the docker role on compute nodes to install docker properly
from the docker repository.
=> ansible: Install docker on compute nodes

.travis.yml, _DeploymentAndDistroPackaging/ansible/roles/ciao-controller/tasks/certificates.yml, ciao-cert/README.md, ciao-cert/main.go, ssntp/certs/certs.go, ssntp/certs/certs_test.go, testutil/singlevm/setup.sh
Previously the -server and -server-cert flag were used to indicate that
the certificate being generated would be either the signing certificate
or signed by the signing certificate. This change updates the flags to
be -anchor and -anchor-cert to separate the ssntp.SERVER role term from
the trust anchor term used in the same command and APIs.
---
The motivation for this is that I was incredibly confused by the term server when talking about the certificate and I thought there was some sort of relation between that and the ssntp role that was embedded in the certificate. Based on existing tests and my own findings that does not appear to be the case and I do not find other documents which contradict these. That being the case, simply renaming the options and a few functions/documentation …
=> ciao-cert: Rename signer flag for clarity

ciao-controller/deps.go
qemu-img is required by ciao-image to convert images into
rbd block devices in ceph.
Fixes #861
=> ciao-controller: Add qemu-img as dependency

ciao-controller/internal/datastore/datastore.go
Ensure that the volume status is marked as "in-use" by setting the status when the attachment was created.
A previous version also updated as part of the instance stats command but that would override any detaching state (found via unit tests.)
=> Ensure volumes are marked as in-use

ciao-controller/instance.go
Refactor the instance launching code to make storage for the CNCI
ephemeral so that it will be cleaned up when the CNCI is deleted.
Fixes: #851
=> ciao-controller: Make CNCI storage ephemeral

ciao-cli/identity.go
When using an unscoped token, you need to use a different
endpoint to list projects than when you have a scoped token.
Fixes: #864 
=> ciao-cli: use correct identity endpoint for unscoped token

ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/openstack_volume.go, ciao-controller/types/types.go
Add a flag to indicate whether the attachment is for a boot volume.
If a user requests a detach of an attachment that is a boot device,
send a 403 to indicate this is a forbidden operation.
Fixes: #870
=> ciao-controller: Add boot flag to attachment

ciao-scheduler/scheduler.go, testutil/server.go
A series of SSNTP Error type frames are mis-identified in comments in
the ciao-scheduler and testutil ssntp servers.  They are referred to as
"event", which is a specific ssntp frame type distinct from "error".  This
mis-identification can lead to confusion regarding what must be explicitly
forwarded by an ssntp server versus is automatically propagated.
=> fix comments on ssntp error versus event

ciao-controller/openstack_volume.go
Create an attachment struct when the attachment is first created, rather
than waiting for a stats update.
Fixes: #867
=> ciao-controller: create attachment at request time

ciao-scheduler/scheduler.go
Modify the scheduler forwarding rules to forward attach/detach errors
to controller.
Fixes: #871
=> ciao-scheduler: add forwarding rules for attach/detach volume failure

ciao-launcher/instance.go, ciao-launcher/instance_test.go
Launcher was not sending updated volume information for exitted instances.  This
led to a situation where volumes attached to exiting instances remained permanently
stuck in the attaching state until the instance was restarted.
Fixes #872
=> ciao-launcher: Always update stats when volumes change

ciao-controller/openstack_image.go
GET /v2/images should always return a list according to OpenStack
image api V2
This change creates an empty list of image.DefaultResponse from the
begining of ListImages() rather than when the first append
to the list is done.
Fixes #892
=> ciao-image: Return an empty list when there are no images

ciao-cli/instance.go
The usage printout for "ciao-cli instance delete" claimed it "Deltes" an
instance, when in fact it "Deletes" an instance.
=> ciao-cli: fix typo

ciao-controller/controller_test.go, ciao-scheduler/scheduler_ssntp_test.go, testutil/agent.go, testutil/client_server_test.go, testutil/controller.go, testutil/server.go
Mark Ryan noted in https://github.com/01org/ciao/pull/877 that
channels are reference type.  That means there's no need for the
reference/deference/address-of operators in the result channels in
testutil.
=> testutil: channels are a reference type

ciao-image/datastore/ceph.go, ciao-image/datastore/datastore.go, ciao-image/datastore/posix.go, ciao-image/datastore/store.go
When writing a new image on posix backend, we open a new file
and drop all image data there, this opened file needs to be
closed before ending the function.
Fixes #661
=> ciao-image: Fix open file issue on posix write ops

ciao-controller/client.go, ciao-controller/client_wrapper.go, ciao-controller/controller_test.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/main.go, testutil/agent.go
This PR contains a few changes to reduce the flakiness and errors seen from the ciao-controller unit test.
The main change removes the sleeps from the test cases in controller_test.go replacing them with a mechanism that wraps ciao-contoller's client with code that uses channels to signal that commands/errors/events have been received.
=> ciao-controller unit test improvements

.travis.yml, _DeploymentAndDistroPackaging/ansible/roles/ciao-controller/tasks/main.yml, _DeploymentAndDistroPackaging/ansible/roles/ciao-controller/tasks/startservices.yml, _DeploymentAndDistroPackaging/ansible/roles/ciao-controller/templates/ciao-controller.service.j2, ciao-controller/README.md, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/main.go
In favor of cleaner deployment, we're changing default paths
for persistent data file of ciao-controller and ``ciao-image`` to
``/var/lib/ciao/data`` directory.
It will create the directories in case that they don't exists.
In case of a diferent path is desired, ``ciao-controller`` command
will require the proper parameters to configure the paths.
=> ciao-controller: Change persistent data paths

ciao-controller/client.go, ciao-controller/client_wrapper.go
The controller unit test improvements and external IP PRs conflicted
when new functions were added to ssntpClient but were missing from the
newly added interface.
This PR adds those missing mapExternalIP/unMapExternalIP methods to the
interface and implements them in ssntpClientWrapper
=> ciao-controller: Fix build errors from patch merges

testutil/singlevm/README.rst
I thought we'd already done this, but maybe only the wiki was updated to
refer to the new page.  There's no point reading a minimal readme that
refers to a page that refers to another page, when you could just straight
refer to the target page.
=> singlevm: update wiki link

ciao-controller/instance.go
I caused myself an error in dev/test and had to look for
sources of "Not implemented yet".  That generic phrase encouraged me to
make the error print more verbose in order to ease future searches.
=> ciao-controller: more verbose error message

ciao-image/datastore/datastore.go, ciao-image/datastore/store.go
In case of failure on image rawDs writting from upload operation,
it will automatically set image status to Killed.
Fixes #663
=> ciao-image: Set status to 'Killed' when upload fails

ciao-controller/command.go, ciao-controller/types/types.go
If an instance has an external IP associated with it, refuse
to delete it. In this case, the user must explicitly unmap first.
Fixes: #898 
=> ciao-controller: prevent deletion of instances with mapped IPs

.travis.yml, testutil/singlevm/setup.sh
The cloud-init configuration was not being updated with the updated
ssh key.
Fixes https://github.com/01org/ciao/issues/913
=> Single VM: Fix SSH Key provisioning issue

ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go
We no longer need to prevent overlapping subnets for internal IP
addresses between tenants. Modify the algorithm to allocate
internal IPs to allow tenants to have overlapping/duplicate IPs.
Remove the test for overlapping IPs since we don't need it anymore.
Fixes: #712
=> ciao-controller: allow overlapping subnets for tenant internal IPs

_release/bat/README.md, _release/bat/storage_bat/storage_bat_test.go, bat/bat.go, bat/compute.go, bat/image.go, bat/storage.go
bat: Add storage bat tests
This PR adds the following storage BAT tests
- Test bootable volumes are created and deleted correctly
- Check bootable volumes of stopped instances are in-use
- Check that in-use volumes cannot be deleted
- Check that the rootfs volumes cannot be detached
- Check that volumes can be added, listed and deleted
- Check attaching volumes become available when deleting their instance.
- Check that a deleting a detaching volume fails
- Check that we can attach and detach volumes
- Check that we cannot attach to a running container
- Check that we cannot attach a volume to two instances
- Check we can attach a volume to a stopped instance
As we now have multiple BAT tests that create and delete instances in the same tenant the BAT tests should be run with test-cases, …
=> Add Storage bat tests

.travis.yml
This PR fixes #911.
In short it
- Adds go1.8beta1 as a build target
- Removes an unused call to misspell
- Re-enables golint on tip.
=> Travis: Add go 1.8 support, fix go lint on tip and delete unused misspell invocation

ciao-cli/instance.go
The message from ciao-cli for instance creation implied that the
instance was available immediately. Update the reported message to make
it clear that the instance is pending.
Fixes: #674
=> ciao-cli: Indicate that newly created instance is pending

testutil/ssntp_test_certs.go, testutil/ssntp_test_certs_test.go
In order to run tests, cert files may need to be available outside of
the /etc/pki/ciao folder. This patch makes use of ssntp/certs to
generate certificates for the scheduler, controller, agent, cnci agent,
and net agent roles in a testutil function.
Test components can use testutil.MakeTestCerts() and if no error is
returned be reasonbly confident a valid set of certs can be found in the
paths returned by testutil.RoleToTestCertPath(role) which returns the ca
file path, the cert path for the given role and a potential error. Test
components should cleanup certs with RemoveTestCerts().
For example:
import "github.com/01org/ciao/testutil"
func TestMain(m *testing.M) {
if err := testutil.MakeTestCerts(); err != nil {
// Inform of error/run tests not using certs/etc
os.Exit(1)
}
result := …
=> testutil: Add temporary test cert file generation

ciao-image/datastore/store.go, openstack/image/api.go, ssntp/uuid/uuid.go
It implements a regex validator for UUIDs in ciao-image service HTTP requests. It will respond with a ``Not Found`` (404) HTTP Error for all those requests that contain a malformed UUID.
It also fixes an issue with images getting from meta datastore. Errors handling needs to return a valid error when we have diferent than ``Not Found`` errors.
Fixes #563 and #566
=> ciao-image: Add regex pattern for validating UUID

networking/libsnnet/bridge.go, networking/libsnnet/bridge_test.go, networking/libsnnet/cn.go, networking/libsnnet/cn_test.go, networking/libsnnet/cnci.go, networking/libsnnet/cnci_test.go, networking/libsnnet/dnsmasq.go, networking/libsnnet/dnsmasq_test.go, networking/libsnnet/fuzz_test.go, networking/libsnnet/gre_test.go, networking/libsnnet/internal_test.go, networking/libsnnet/vnic_test.go
Methods from bridge.go can be reused by some other projects such as
virtcontainers, that's the reason why we export them to make them
accessible.
=> networking: libsnnet: Export bridge API

networking/libsnnet/cn.go, networking/libsnnet/cn_container_test.go, networking/libsnnet/cn_test.go, networking/libsnnet/cnci.go, networking/libsnnet/docker_plugin.go, networking/libsnnet/fuzz_test.go, networking/libsnnet/internal_test.go, networking/libsnnet/vnic.go, networking/libsnnet/vnic_test.go
Methods from vnic.go can be reused by some other projects such as
virtcontainers, that's the reason why we export them to make them
accessible.
=> networking: libsnnet: Export Vnic API

ciao-controller/main.go, ciao-launcher/main.go, ciao-scheduler/scheduler.go, clogger/README.md, clogger/gloginterface/interface.go, clogger/logger.go, osprepare/distro.go, osprepare/osprepare.go, osprepare/versions.go
Instead of having osprepare attempt to provide all the logging interface
components, add a new ciao module for logging that provides by default
only a no log implementation.
Also add a separate module that provides an interface implementation
that uses glog.
This change is done to avoid any interface implementor getting glog
flags added to their messages (since previously osprepare always
required glog).
Addresses #919.
=> Refactor logging interface used in osprepare

_release/bat/README.md
Bat test requires access to a ciao cluster and for storage
tests it requires qemu-img and access to the ceph cluster.
This change updates _relase/bat/README.md to
- Instruct the user to run the tests from the controller
- Fix typo in 'wildcard'
- Fix hyperlink to singlevm
=> bat: Specify where to run bat tests from

testutil/singlevm/setup.sh
setup.sh was cleaning up but not exiting after the user had pressed CTRL-C,
which created a weird situation in which setup.sh would pause the ciao
bring up, delete all the work it had done, and then resume the bring up from
an inconsistent state.
Fixes #953
=> Single VM : Exit on cleanup

ciao-image/datastore/datastore_test.go, ciao-image/datastore/store.go
This commit fixes the loss of ceph error when an image upload operation
is performed. Now, Ceph errors are properly returned and Metadata errors
are separately handled.
Fixes #905
=> ciao-image: Fix raw datastore error handling on ciao-image service

_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/tasks/build.yml, _DeploymentAndDistroPackaging/ansible/roles/ciao-controller/tasks/upload_images.yml
If ciao is installed from packages, the ciao-cli binary will be retrieved from
the controller node. Otherwise, the ciao-cli from the local GOPATH will be used.
Fixes https://github.com/01org/ciao/issues/943
=> ansible: Make sure the deployment node is using the correct ciao-cli

ciao-controller/main.go, ciao-image/datastore/store.go, ciao-launcher/main.go, database/boltdb.go, database/logger.go, networking/ciao-cnci-agent/client.go, networking/libsnnet/docker_plugin.go, networking/libsnnet/logger.go, networking/libsnnet/tests/cncicli/cncicli.go, networking/libsnnet/tests/cncli/cncli.go, networking/libsnnet/tests/docker/plugin/plugin.go, networking/libsnnet/tests/parallel/parallel_test.go
glog is a very useful library used by many projects. Because libsnnet package (and database implicitly) is intended to be used from external packages, we cannot rely on a vendored version of glog. This PR allows the calling package define its own clogger, and pass it to imported packages. In case nothing is defined, nothing will be printed because the default implementation of clogger is CiaoNullLogger, generating nothing.
=> Fix glog dependencies

testutil/singlevm/verify.sh
Use templates to retrieve the SSH IP vs bash command pipeline. This enables more efficient execution.
This change moves all of verify.sh to use templates in all places where it is possible to do so.
=> SingleVM: Use templates to get SSH IP

ciao-cli/image.go
Add an image validation in the imageAddCommand function.
If the image/path does not exists it will exit right after, preventing
image creation in the image service.
Fixes https://github.com/01org/ciao/issues/874
=> ciao-cli: Validate image file exists when adding a new image.

_release/bat/storage_bat/ceph_test.go, ciao-controller/openstack_image.go, ciao-image/datastore/ceph.go, ciao-image/datastore/datastore.go, ciao-image/datastore/noop.go, ciao-image/datastore/posix.go, ciao-image/datastore/store.go, ciao-launcher/docker_test.go, ciao-storage/block.go, ciao-storage/ceph.go, ciao-storage/noop.go
Query the image size from rbd and populate that into the datastore. From the datastore populate the openstack image API datastructures.
Fixes: #959
=> Populate the image size based off of ceph

ciao-launcher/image.go, ciao-launcher/image_test.go, ciao-launcher/instance.go, ciao-launcher/instance_test.go, ciao-launcher/main.go, ciao-launcher/payload_test.go, ciao-launcher/port_grabber_test.go, ciao-launcher/process_stats.go, ciao-launcher/process_stats_test.go, ciao-launcher/ssntp.go, ciao-launcher/ssntp_test.go, ciao-launcher/vmconfig.go
Tests have been added for
- image.go
- ssntp.go
- port_grabber.go
- payload.go
- process_stats.go
A bug has also been fixed that led to some of the existing unit tests failing if launcher was not run as root and the /var/lib/ciao/instances directory did not exist.
=> Add some more unit tests for launcher

_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/tasks/main.yml
Creating images from ansible leads to invalid uuid assigment
due to wrong names.
fixes https://github.com/01org/ciao/issues/968
=> ansible: Fix image uuids

ciao-launcher/container_manager.go, ciao-launcher/docker.go, ciao-launcher/docker_test.go
This PR adds the following new unit tests for docker
- TestDockerCheckBackingImage
- TestDockerDownloadBackingImage
- TestDockerDeleteImage
- TestDockerCreateImage
A new interface, containerManager was added to facilitate these new tests.  It allows us to replace the docker client object with an object of our choosing.
=> ciao-launcher: Add some more docker unit tests

ciao-cli/examples/README.md, ciao-cli/examples/docker-ubuntu.yaml, ciao-cli/examples/fedora_cloud.yaml, ciao-cli/examples/fedora_cloud_disk.yaml, ciao-cli/examples/fedora_vm.yaml, ciao-cli/examples/ubuntu_latest.yaml, ciao-cli/workload.go, ciao-controller/api/api.go, ciao-controller/api/api_test.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/memorydb.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/types/types.go, ciao-controller/workload.go
This set of commits adds support for creating custom workloads in ciao. At the moment because there is no tenant separation for workloads, **this command must be run with admin privileges**. 
There was a lot of complexity around creating the workloads, so I felt it was much simpler to have the user create a text file which describes it and then import that text into cli. I included some examples for workloads in a new directory in cli called "examples". I will add support for specifying entirely on the ciao-cli command line (with the exception of the cloud-config.yaml) in a follow on PR.
A README was included in the examples subdirectory to describe the format required for the workload
definition yaml files.
Fixes: #931 
Fixes: #932
=> Add support for creating custom workloads

networking/libsnnet/cn.go, networking/libsnnet/vnic.go, networking/libsnnet/vnic_test.go
libsnnet API lets us get an existing VNIC device only from its alias. Because this
API is used externally by other project such as virtcontainers, there are cases where
no alias is set for an existing interface, and we want to be able to retrieve a VNIC
object from this existing interface.
This PR duplicates the existing GetDevice() to provide a new GetDeviceByName, relying
on netlink LinkByName function. It builds a VNIC object according to the information found
for the related link name.
The API SetHardwareAddr() was implicitely creating a Vnic peer related
to the current Vnic, and it was setting the hardware address for this peer.
It was a very specific case for Ciao but we want more explicit things now
that libsnnet is used externally from other projects.
This PR simplifies …
=> networking: libsnnet: Make API more explicit and get existing VNIC device by name

_DeploymentAndDistroPackaging/ansible/README.md, _DeploymentAndDistroPackaging/ansible/doc/firewall.md
User/Operator must be aware of the firewall configuration
when deploying a Ciao cluster. This commit adds a reference
of the firewall configuration that must be done in order to have
an operational Ciao cluster.
Fixes https://github.com/01org/ciao/issues/822
With this settings, running an all-fedora-24 Ciao cluster, I'm able to launch instances, reach them via SSH ~~but not able to get instances reach internet(WIP, maybe proxies)~~ and able to reach the Internet within the instances.
=> [RFC] ansible: Add Firewall documentation

ciao-launcher/container_manager.go, ciao-launcher/docker.go, ciao-launcher/docker_test.go
This commit adds the following new docker unit tests:
- TestDockerCreateImageFail
- TestDockerCreateImageWithVolumes
- TestDockerCreateImageWithResources
- TestDockerMonitorVM
- TestDockerMonitorVMClose
- TestDockerStats
It improves launcher's unit test coverage to 52.6%.
Partial fix for issue #1
=> ciao-launcher: Add more docker unit tests

ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/memorydb.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go
In #921 I mention a few areas where the database code can be tidied-up from my previous digs into that code. This PR addresses some of the easiest changes via automated renames.
=> Minor datastore/database cleanups

ciao-controller/instance.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/openstack_volume.go, ciao-controller/types/types.go, ciao-storage/block.go, ciao-storage/ceph.go, ciao-storage/noop.go
Populate the volume size in GiB when creating volumes via all mechanisms. Push the responsibility for setting the size on storage.BlockDevice to the backend.
=> Populate volume size

_release/bat/image_bat/image_bat_test.go, _release/bat/storage_bat/storage_bat_test.go, bat/image.go, bat/storage.go, ciao-controller/openstack_volume.go
This PR adds some new BAT tests for storage that test the different source types whilst also testing the new size reporting and calculation.
This identified some issues also fixed by this PR.
@kaccardi to review ciao-controller change as owner
@markdryan to review bat changes as owner
=> BAT enhancements for storage

.travis.yml, _release/bat/base_bat/base_bat.go, _release/bat/base_bat/base_bat_test.go, _release/bat/image_bat/image_bat.go, _release/bat/image_bat/image_bat_test.go, _release/bat/storage_bat/ceph_test.go, _release/bat/storage_bat/storage_bat.go, _release/bat/storage_bat/storage_bat_test.go
The static analysis tools were not executed on the BAT tests as they
are stored in the _release folder.  This commit ensures that the tests
do get run on the BAT test code.
Enabling the tools revealed some errors.  This commit also adresses these
failures.
=> bat: Enable static analysis on BAT tests

.gitignore
Previous to this commit, `git status` shows vim swap files (*.swp) as
untracked files, which can lead to being added accidentally in commits.
This commit makes git to ignore those files, reducing the changes of add
them by accident.
=> .gitignore: ignore vim swap files

openstack/identity/identity.go, openstack/identity/identity_test.go
when validating token, tenant is obtained from mux.Vars of the
request, on certain cases (such as the image service) the tenant
variable it's absent due to not being specified in the endpoint URI,
this makes ciao to believe we're requesting operation as an admin when
that's not true.
This commit tries to get tenant from token if no tenant is obtained from
mux.Vars
Closes #866 
=> openstack: retrieve tenant from token when absent from mux

ciao-cli/template.go
ciao-cli: Add support for substring matching
Add support for new filter capabilities. This allows the selection
of list elements based on substring, prefix, suffix matching etc
which will be useful for test automation.
=> ciao-cli: Add support for generic string matching in templates

ciao-cli/workload.go, ciao-controller/controller_test.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/memorydb.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/types/types.go, ciao-controller/workload.go
A prerequisite of converting a running instance to a workload is being
able to support multiple types.StorageResource per workload.  This
change enables that.
Creating a workload from fedora_cloud_disk.yaml and then creating an
instance from that now shows two volumes created.
Fixes: #945
=> ciao-controller: Support multiple storage resources per workload

ciao-launcher/docker_network.go, testutil/ciao-down/README.md, testutil/ciao-down/ciao_down.go, testutil/ciao-down/cloudinit.go, testutil/ciao-down/prepare.go, testutil/ciao-down/vm.go, testutil/singlevm/setup.sh
This PR adds ciao-webui support to ciao-down and Single VM.   In short ciao-down installs and configures node and downloads the ciao-webui repo into a directory shared with the host.  Single VM creates a configuration file that contains all the information the webui needs to talk to the Single VM ciao instance.
We also fix a bug which causes a launcher crash when container creation fails due to a network error.
=> Add ciao-webui support to ciao-down and Single VM

ciao-launcher/instance.go, ciao-launcher/instance_test.go
After requesting that the virtualizer (e.g. qemu) to stop wait on the
channel monitoring the domain socket used to communicate with the
virtualizer.  This allows us to identify when the virtualizer has
finished and the next step of the cleanup can begin.
This addresses #1009 by not trying to unmap volumes that are still in
use by the running qemu process.
Fixes: #1009
=> ciao-launcher: Wait for virtualizer to terminate

ciao-launcher/docker.go, ciao-launcher/docker_test.go, ciao-launcher/qemu.go, ciao-launcher/qemu_test.go
This makes us more consistent with the rest of ciao and general industry
expectations.
Fixes: #990
=> ciao-launcher: Use MiB in the launcher storage code

ciao-cli/examples/fedora_cloud.yaml, ciao-cli/examples/fedora_cloud_disk.yaml, ciao-cli/workload.go
Fix the parsing of workload storage specified in the .yaml file. When then transition from yaml to json happened the disks struct was omitted resulting the yaml files being incorrectly parsed.
This PR fixes the tags on the struct and updates the examples to explicitly use the source type.
A further PR will remove the image_id functionality as per #988
=> Fix #1027 - workload yaml parsing

ciao-controller/client.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/openstack_compute.go
Where we are able to return an error, wrap the error so that there is some useful context available for debugging.
Where we are not able to return an error (or on paths with multiple potential errors) ensure that the errors that do occur are logged in a consistent manner.
Also modify the prototype of GetStorageAttachments not to return an error as it cannot do so.
=> Improve error reporting in controller

ciao-cli/workload.go, ciao-controller/workload.go
Enhance the verification code used to verify storage specification in the workload definition at both a ciao-cli and ciao-controller level.
As part of this PR ciao-controller now expects and explicit source type which ciao-cli will now provide.
Fixes: #1026
=> Enhance workload storage verification

networking/ciao-cnci-agent/client.go, networking/ciao-cnci-agent/database.go, networking/ciao-cnci-agent/network.go, testutil/singlevm/verify.sh
Add support to the CNCI agent to save the state of the CNCI
network setup to the boot disk. The network state is recovered
by replaying the commands. This allows for potential migration
to a new implemenation of the command if the cnci agent is
upgraded.
This allows the CNCI agent to recover its state if the CNCI
is rebooted or migrated to a different network node.
Includes a test case where the CNCI is rebooted by sshing into it
as a stand in for migration, and the network setup is re validated.
Also added a commit to use the errors package.
=> Networking: cnci-agent: Persist network state across reboots/migration

ciao-controller/workload.go
Fix a bug in the workload validation that improperly returned
BadRequest when Storage.ID == "" and Storage.SourceType != Empty.
What we really wanted to do was check if Storage.SourceID was "".
=> ciao-controller: fix bug in workload validation

ciao-controller/command.go, ciao-controller/controller_test.go, ciao-controller/main.go
This commit ensures that confirmTenant is only successfully called once
for each tenant during any invocation of controller.  The problem is
that confirmTenant is not re-entrant and yet was called by multiple
go routines simulataneously.  This mean that a ciao cluster could be
broken by two commands issued simultaneously on a new tenant.
The tricky thing about fixing this bug is that we cannot really protect
the whole function with a mutex.  The function is potentially very slow
as it optionally needs to wait for a CNCI to launch.  Using a critical
section for the entire function would result in commands for existing
tenants being blocked while a CNCI was launched for a new tenant, which
wouldn't be great.
The fix works by introducing tenant specific channels that provide
synchronisation …
=> controller: Fix race condition in confirmTenant

networking/libsnnet/cn.go, testutil/singlevm/cleanup.sh, testutil/singlevm/setup.sh
Latest version of docker (1.13+) adds a default deny rule
for all forwarded traffic if docker enables ip forwarding.
If docker already finds ip forwarding enabled on the system
it will leave the firewall setup untouched and only append
rules at the very top.
The ciao traffic that traverses the bridges gets impacted by
this as the bridge traffic is also subject to iptables rules
as the following rules are enabled
bridge-nf-call-arptables
bridge-nf-call-iptables
bridge-nf-call-ip6tables
To fix this 
- Add explicit allow rules for Single VM Ciao Traffic
- Add explicit allow rules for Ciao traffic on compute nodes.
This also fixes the TLS issues observed in the bare metal single machine setup
Fixes #1064 #1065 
=> Networking: Add explicit allow rules for Ciao Traffic

ciao-cli/image.go
CIAO image service is not currently supporting image ``download``
and ``modify``. We may enable it later. For now, we need to remove
these options in order to avoid confusion.
=> ciao-cli: Remove non-supported image download and modify

testutil/ciao-down/ciao_down.go, testutil/ciao-down/cloudinit.go, testutil/ciao-down/prepare.go, testutil/ciao-down/vm.go
There are two updates:
1. Fix a couple of race conditions that prevent the prepare command from removing an instance in case of error or cancellation.
2. Add a new option, -runcmd, that can be used to provide an additional set of instructions for cloud-init to run when setting up the vm.  These instructions augment the setup work that ciao-down does to setup ciao itself.
=> Updates to ciao-down

ciao-cli/examples/README.md, ciao-cli/examples/fedora_cloud.yaml, ciao-cli/examples/fedora_cloud_disk.yaml, ciao-cli/examples/ubuntu_latest.yaml, ciao-cli/workload.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/tables/resources.csv, ciao-launcher/README.md, ciao-launcher/payload.go, ciao-launcher/payload_test.go, ciao-launcher/start_test.go, ciao-launcher/tests/examples/start_efi.yaml, ciao-launcher/tests/examples/start_legacy.yaml, ciao-launcher/tests/examples/start_legacy_volume.yaml, ciao-launcher/tests/examples/start_legacy_volume_boot.yaml, ciao-launcher/tests/examples/start_nn.yaml, ciao-launcher/tests/examples/stress/efi.sh, ciao-launcher/tests/examples/stress/legacy.sh, ciao-scheduler/scheduler_internal_test.go, payloads/restart_test.go, payloads/start.go, payloads/start_test.go, testutil/payloads.go
Now that VM storage is ceph backed and we currently have no implementation plan for local storage for VMs this payload/workload member has no meaning.
For containers we also do not currently use this value.
There for clarity for users remove this from the workload specification and for consistency remove from the payload specification too
=> Remove (unused) local disk specification

_DeploymentAndDistroPackaging/ansible/README.md
This commit fixes two errors with the README.md file that prevent one
from installing ciao via ansible.
=> ansible: Fix some issues with the README.md

ciao-cli/event.go, ciao-cli/external-ips.go, ciao-cli/image.go, ciao-cli/instance.go, ciao-cli/node.go, ciao-cli/template.go, ciao-cli/template_test.go, ciao-cli/tenant.go, ciao-cli/trace.go, ciao-cli/volume.go, ciao-cli/workload.go
This PR adds some functions that can be used to auto-generate the documentation that describes how templates may be used for ciao-cli commands.  As, an example, to generate the template usage documentation for a command that operates on slices of  CiaoCNCIs you might call
```    
generateUsageUndecorated([]types.CiaoCNCI{})
```
and you would receive a string that looks something like this.
```    
[]struct {
ID        string `json:"id"`
TenantID  string `json:"tenant_id"`
IPv4      string `json:"IPv4"`
Geography string `json:"geography"`
Subnets   []struct {
Subnet string `json:"subnet_cidr"`
} `json:"subnets"`
}
```
There's another function, generateUsageDecorated that also includes information about all the additional functions ciao-cli provides for use in templates.
The PR also updates …
=> ciao-cli: auto-generate template documentation

CONTRIBUTING.md
Our contributing document is a good place to referernce our unit tests,
CI and BAT, which can help guide new contributors to higher initial
quality and higher likelihood of success in a pull request.
=> documentation: add quality section to CONTRIBUTING.md

testutil/ciao-down/README.md, testutil/ciao-down/ciao_down.go, testutil/ciao-down/cloudinit.go, testutil/ciao-down/prepare.go, testutil/ciao-down/vm.go
First step in making ciao-down a generic dev-test VM launcher.
Adding support for a clear containers development environment.
To use ciao-down to setup a clear containers development environment 
the prepare command has been enhanced to add vmtype parameter
-vmtype string
Type of VM to launch. ciao or clearcontainers (default "ciao")
This is backwards compatible with VM's created prior to this update.
=> ciao-down: Add support for clearcontainers development enviornment

ciao-launcher/overseer.go, ciao-scheduler/export_test.go, ciao-scheduler/scheduler.go, ciao-scheduler/scheduler_internal_test.go, ciao-scheduler/scheduler_ssntp_test.go, payloads/ready.go, payloads/ready_test.go, payloads/start.go, testutil/agent.go, testutil/client_server_test.go, testutil/payloads.go
This PR allows scheduling of a workload to a network node that satisfies a workload's request for specific network connectivity.
Partially addresses #1044, but completely closing that issue depends on addressing issue #912.  When controller is able to restart a CNCI, it will need to add a network resource request, which scheduler can honor as of this PR.
=> Enable node networks based scheduling

_DeploymentAndDistroPackaging/ansible/roles/docker/meta/main.yml, _DeploymentAndDistroPackaging/ansible/roles/docker/tasks/install_fedora.yml, _DeploymentAndDistroPackaging/ansible/roles/docker/tasks/install_ubuntu.yml
This two commits adds support for Fedora25, Yakkety in addition to the current supported Fedora24 and Xenial.
Fixes #1110
=> ansible: add fedora25 and ubuntu yakkety support for docker role

.travis.yml
The go tip builds are currently failing due to a compiler error, i.e.,
a crash in the compiler.  This commit will allow ciao builds to continue
to pass even if go tip builds fail.  This is reasonable enough as there
are likely to be build breakages on go tip from time to time.
=> travis: Allow go tip builds to fail

ciao-launcher/virtualizer.go, testutil/agent_test.go, testutil/controller_test.go, testutil/server.go, testutil/server_test.go
This PR cobbles together a few small fixes based on code inspection:  a misnamed variable which is less clear than it should be, a simple comment typo, and a bug in normally-not-run (due to "-short") testutil results channel timeout unit tests.
=> small fixes

_DeploymentAndDistroPackaging/ansible/ciao_prepare.yml, _DeploymentAndDistroPackaging/ansible/roles/keystone/tasks/main.yml
Use clearlinux/keystone:stable container rather than
clearlinux/keystone:latest
=> ansible: Use keystone:stable container

testutil/ciao-down/cloudinit.go
There seems to be a race condition that causes the mounting of the
shared folders via 9p to fail.  This in turn causes the ciao-down
VM boot to fail.  This commit switches to using the system.d
automount facility ( which may fix the mount problem ) and allows the
boot to continue even if the mounts fail.  This is preferable to the
current status in which ciao-down connect seems to hang from time
to time on some machines.  If automatic mounting fails it should
still be possible to manually mount the shared folders from the command
line.
=> ciao-down: Allow qemu boot to continue even if 9p mounts fail

configuration/README.md
The compute_fqdn option is currently undocumented.  A user needs to know
to set it to match the name for which their compute_cert is valid.
=> configuration: add compute_fqdn example

test-cases/test-cases.go
This change modifies test-cases so it treats skipped tests as
'ok'.  This is needed to ensure that our release builds pass.  Currently,
some of the BAT tests are skipped due to missing functionality.
Fixes #1145
=> test-cases: Treat SKIPped tests as ok

_DeploymentAndDistroPackaging/ansible/roles/ciao-common/tasks/main.yml
Some distributions do not have the folder already created by default.
This change ensures the directory is present and owned by root.
Fixes #1140
=> ansible: Create /usr/local/bin

testutil/ciao-down/cloudinit.go
The cloudinit file has a dedicated section for configuring apt but
we weren't using it.  Instead we were executing all of the apt
commands in the runcmd and write_files section of the cloud-init file.
This commit moves the instructions that set up the apt proxies and
initiate the apt-get upgrade to the apt section.  The other commands
such as setting up sources and installing packages can not be used
as these sections do not handle proxies correctly.
Fixes #1131
=> ciao-down: Use apt section of cloudinit file

_DeploymentAndDistroPackaging/ansible/roles/ciao-common/tasks/main.yml
Use {{ item }} as an argument to a task with
`with_items` clause
=> ansible: Fix bug introduced at 27cdcb9

_release/bat/README.md, _release/bat/quotas_bat/quotas_bat.go, _release/bat/quotas_bat/quotas_bat_test.go, bat/compute.go, bat/quotas.go, ciao-cli/main.go, ciao-cli/quotas.go, ciao-controller/api/api.go, ciao-controller/api/api_test.go, ciao-controller/client.go, ciao-controller/controller_test.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/memorydb.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/internal/quotas/quotas.go, ciao-controller/internal/quotas/quotas_test.go, ciao-controller/main.go, ciao-controller/openstack_volume.go, ciao-controller/quotas.go, ciao-controller/types/types.go, payloads/start.go
Here is a working prototype for quotas and limits (the only thing i've not published here is the ciao-cli support as i'm still tidying that up)
The core of my design for this feature is based around a Quota Service (QS) that handles the in-memory storing of quotas/limits and the appropriate usage.
The main entry points to the API that the QS provides to other parts of controller is to Consume() or to Release() sets of payloads.RequestedResource structs.
An example of how this works can be seen in the "ciao-controller: Add quota checking for shared storage" commit.
The QS is designed so that it is safe to be accessed from multiple goroutines without using mutexes and also the API for consuming is asynchronous around a channel to allow e.g. instances to be started and then shutdown later if …
=> Quotas and Limits Phase 1

testutil/singlevm/setup.sh
The service user "csr" is for the controller service. We should use a non-service
user for testing.
=> singlevm: do not use service user "csr" in singlevm

.travis.yml
We've been tracking 1.8 development for a while, switch to the stable
release. \o/
=> travis: Enable go 1.8 builds on travis

qemu/qmp.go, qemu/qmp_test.go
This PR fixes three issues:
1. Cancelling of QMP commands did not work properly.  The commands could be cancelled but commands issued after a cancelled command did not work correctly.  Rather than executing the new command the old cancelled command was re-executed.
2. The word Command was incorrectly spelt in the qmp_test.go file.
3. The code that handles cancelling is a little complicated and needed documenting.
=> Fix Cancelling of QMP commands and some spelling mistakes

_DeploymentAndDistroPackaging/ansible/roles/keystone/tasks/access.yml, _DeploymentAndDistroPackaging/ansible/roles/keystone/tasks/main.yml, _DeploymentAndDistroPackaging/ansible/roles/keystone/tasks/startservices.yml
Make the keystone role more readable by grouping related tasks
together
* Move tasks to create openrc and clouds.yml files into access.yml
* Group tasks to start the keystone service in startservices.yml
=> ansible: Refactor keystone role

ciao-cli/quotas.go
This change switches the error messages to use fatalf() and terminate
execution if there is a problem with the user privileges.
It also works to ensure that if the user is an admin then they must
specify a tenant id to check as the Ciao API url creation never embeds
the url for the the admin tenant and so the unprivileged path does not
work the admin user.
=> ciao-cli: Fix privilege related error reporting for quotas command

ciao-scheduler/export_test.go, ciao-scheduler/scheduler_internal_test.go
There's a small amount of test code that was originally intended to
support some test coverage, but that didn't end up being used.  Remove
it for cleanliness.
=> ciao-scheduler: remove unused code

_DeploymentAndDistroPackaging/ansible/roles/ciao-launcher/tasks/install.yml
OVMF.fd is already shipped in the kvm-host bundle in ClearLinux
Fixes #1167
=> ansible: Do not install OVMF.fd on ClearLinux

.travis.yml
Travis's documentation:
https://docs.travis-ci.com/user/installing-dependencies/ says that you
should run apt-get update before trying to install packages. We weren't
doing this and although our builds worked something has changed in
Travis that makes this required.
This change follows their recommendation and calls apt-get update.
=> travis: Fix travis builds

_DeploymentAndDistroPackaging/ansible/cleanup/ciao.yml
This PR Improves the cleanup scripts by 
- Removing the certificates and `images/.cnci_ready` files to ensure new certs and a new cnci image is generated on the next run.
- Run `ciao-launcher -hard-reset` on compute and network nodes to stop qemu instances
- Remove rbd devices from ceph
Fixes https://github.com/01org/ciao/issues/1169
Fixes https://github.com/01org/ciao/issues/1171
Fixes https://github.com/01org/ciao/issues/1172
=> ansible: Improve cleanup script

_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/templates/ciao-controller.service.j2, _DeploymentAndDistroPackaging/ansible/roles/ciao-controller/templates/ciao-scheduler.service.j2, _DeploymentAndDistroPackaging/ansible/roles/ciao-launcher/templates/ciao-launcher.service.j2
Fix systemd units for ciao-launcher, ciao-scheduler and ciao-controller
to log to the default location instead of stderr.
=> ansible: Fix logging on systemd units

testutil/ciao-down/cloudinit.go
This commit updates the version of Go used in ciao-down ciao VMs from
1.7.4 to 1.8.  The version used in the creation of clearcontainer vms
has not been changed.
=> ciao-down: Update Go to 1.8

ciao-controller/client.go, ciao-controller/internal/datastore/datastore.go, payloads/startfailure.go
If the instance start fails due to e.g. the cloud being full then the
ephemeral volume needs to be deleted. This change makes controller
delete the ephemeral volume if it receives a start failure messagef from
scheduler.
Tested by starting 60 instances on a small cluster and then observing
that without the patches the volumes for the rejected instances remain
after deleting all; with the patch no residual volumes remain.
Fixes: #1173
Signed-off-by: Rob Bradford robert.bradford@intel.com
=> ciao-controller: Delete ephemeral volumes on start failure

_DeploymentAndDistroPackaging/ansible/cleanup/ciao.yml
Remove childrens of a snapshot before attempting to remove the snapshot
itself
Fixes #1172
=> ansible: Remove rbd devices

ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go
This PR addresses #1114 and switches the workload_resources table, used to store the resources needed for a workload to not store the resource type as an integer but as a string. Removing conversion to & fro.
=> Workload defaults refactor

ciao-controller/controller_test.go, ciao-controller/openstack_volume.go
* Record that volumes created via the API from an ImageRef are marked bootable as per spec
* Report out volume bootable status via API
* Unit testing of the above
Fixes: #1191
=> Fix bootable volume handling in Open Stack API

_DeploymentAndDistroPackaging/ansible/roles/ciao-common/tasks/ceph.yml, _DeploymentAndDistroPackaging/ansible/roles/ciao-controller/tasks/install.yml, _DeploymentAndDistroPackaging/ansible/roles/ciao-controller/tasks/startservices.yml, _DeploymentAndDistroPackaging/ansible/roles/ciao-launcher/tasks/install.yml
This set of patches aim to fix the file modes used when setting file permissions, as Ansible documentation for both the `file`[[1](http://docs.ansible.com/ansible/file_module.html#options)] and `copy`[[2](http://docs.ansible.com/ansible/copy_module.html#options)] modules says:
> Leaving off the leading zero will likely have unexpected results
=> ansible: fix files modes

_release/bat/workload_bat/workload_bat_test.go, bat/workload.go, ciao-cli/workload.go, ciao-controller/api/api.go, ciao-controller/api/api_test.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/memorydb.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/types/types.go, ciao-controller/workload.go
Create the API and ciao-cli support for deleting unused public or private workloads. Modify BAT tests to delete the test workload.
Fixes: #949, #950, #951, #952, #1135
=> Add support for deleting workloads

_DeploymentAndDistroPackaging/ansible/cleanup/ciao.yml, _DeploymentAndDistroPackaging/ansible/roles/ciao-common/tasks/ceph.yml, _DeploymentAndDistroPackaging/ansible/roles/ciao-controller/templates/ciao-controller.service.j2
ciao-controller was run as root to allow it to run ceph commands.
By changing the ownership of /etc/ceph and its content to be owned by
ciao, ciao-controller can be run without root privileges.
=> ansible: Run ciao-controller as ciao user

ciao-cli/instance.go, ciao-controller/command.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/openstack_compute.go
If launching some instances out of the request fail then we can end up in situating with unexpected "dangling" instances where an error is returned but also some instances started.
With this change if some instances did get launched correctly then report then out and asynchronously send an event. If only one instance was started if or no instances got launched correctly then return the error directly
With a quota volume limit:
```
rob@singlevm:~/go/src/github.com/01org/ciao/testutil/singlevm$ ciao-cli instance add -workload ed39a2c3-19f2-48ee-a650-483426d44760 --instances 8
Some instances failed to start - check the event log for details.
Created new (pending) instance: 08b78ca4-4fd1-445e-bce6-dd91ff5d9408
Created new (pending) instance: 804abebd-c112-45c7-9c74-3d27ed137922
Created new …
```
=> Improve partial instance launching

bat/bat_test.go, bat/compute.go, ciao-cli/instance.go
Add templating to ciao-cli instance add and then use that in the BAT tests for obtaining the list of launched instances.
Fixes: #1209
=> Add templating to ciao-cli instance add

_release/bat/quotas_bat/quotas_bat_test.go, ciao-controller/client.go, ciao-controller/instance.go, ciao-controller/quotas.go
This PR adds quota tracking for instances. When instances are created the resources specified in the workload are consumed. When the instance is deleted (or fails to start) then the resources are released.
On controller startup any existing instances also have their resources consumed.
=> Add instance tracking to quotas

ciao-cli/instance.go, ciao-controller/api/api.go, ciao-controller/api/api_test.go, ciao-controller/legacy_api.go, openstack/compute/api.go, openstack/identity/identity.go, service/service.go, testutil/singlevm/verify.sh
Let the identity middleware communicate privilege to the service handlers via context. Modify the ciao API and the legacy ciao API to specify whether routes should be for privileged users only, and send http status Unauthorized if the user doesn't have sufficient privilege.
Fixes: #1158
=> Add ability for http services to check for user privilege

testutil/ciao-down/ciao_down.go, testutil/ciao-down/cloudinit.go, testutil/ciao-down/download.go, testutil/ciao-down/prepare.go, testutil/ciao-down/vm.go
This commit adds a new function that can be used when creating
ciao down cloud init files.  The function called download
instructs ciao-down to download and cache the downloaded files on
the host.  The next time a VM requests the same file ciao-down will
serve the file from its cache rather than downloading it
from the Internet.  This speeds up the creation of ciao VMs by 5.5
minutes and clear container VMs by about 20 seconds.
Fixes #957
=> ciao-down: cache large files

_DeploymentAndDistroPackaging/ansible/README.md
We used to provide a docker container with ansible and the dependencies
required by the playbooks already installed on it.
This commit updates the documentation to instruct the user to install
ansible and the required packages on the deployment host since using
the container proved to be more cumbersome than installing the few
depdendencies.
=> ansible: Update documentation to run ansible on the deployment host

ciao-cli/image.go
ciao-cli image list was not handling templates correctly.  It was
calling the template function once for each page rather than once
for the entire list.  This breaks scripts such as {{len .}} which
attempt to compute the total number of images.
=> ciao-cli: Fix template handling of ciao-cli image list

_DeploymentAndDistroPackaging/ansible/ciao_controllers.yml, _DeploymentAndDistroPackaging/ansible/ciao_networks.yml, _DeploymentAndDistroPackaging/ansible/cleanup/ciao.yml, _DeploymentAndDistroPackaging/ansible/doc/development.md, _DeploymentAndDistroPackaging/ansible/group_vars/all, _DeploymentAndDistroPackaging/ansible/roles/ceph/README.md, _DeploymentAndDistroPackaging/ansible/roles/ceph/defaults/main.yml, _DeploymentAndDistroPackaging/ansible/roles/ceph/tasks/container.yml, _DeploymentAndDistroPackaging/ansible/roles/ceph/tasks/main.yml, _DeploymentAndDistroPackaging/ansible/roles/ceph/vars/Clear.yml, _DeploymentAndDistroPackaging/ansible/roles/ceph/vars/Debian.yml, _DeploymentAndDistroPackaging/ansible/roles/ceph/vars/RedHat.yml, _DeploymentAndDistroPackaging/ansible/roles/ciao-common/README.md, _DeploymentAndDistroPackaging/ansible/roles/ciao-common/defaults/main.yml, _DeploymentAndDistroPackaging/ansible/roles/ciao-common/tasks/main.yml
Introduce ceph_config variable which behaves acordingly to the
following values.
- none: Ceph is already configured and ansible will not setup ceph
- container: Ansible will deploy ceph/demo container on the controller
node and configure the rest of the nodes to use it.
- files: An existing ceph cluster exists and ansible will configure all
nodes using the existing ceph configuratino and authentication
files found in ceph_config_dir variable.
Fixes #1084
=> ansible: Install ceph container

ciao-controller/client.go, ciao-controller/command.go, ciao-controller/instance.go
If an instance fails to get added early in the process (possibly due to a quota based rejection) then the ephemeral volumes for it need to be cleaned up.
Fixes: #1206
=> Cleanup ephemeral volumes if instance fails early

ciao-controller/api.go, ciao-controller/command.go, ciao-controller/compute_test.go, ciao-controller/controller_test.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/memorydb.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/types/types.go
Migrate users of the older limit and resources infrastructure to the new quota service and delete the old code.
Fixes: #1115 
Fixes: #1116
=> Migrate away from "legacy" quota checking code

testutil/ciao-down/cloudinit.go
Fix the docker version to 1.12.1 for now.
Note: docker-engine is now docker-ce
The cloud-init performs the setup needed for docker-ce but
currently keeps using the older docker-engine.
=> ciao-down: clearcontainers : fix docker version to 1.12.1

qemu/qemu.go, qemu/qemu_test.go
The existing NetDevice relies on virtio-net driver, but there is a
useful PCI variant which was not available: virtio-net-pci.
This patch adds this new driver and adds two parameters specific to
this: "bus" and "addr".
=> qemu: Add PCI option to the NetDevice

_release/bat/image_bat/image_bat_test.go, ciao-cli/image.go, ciao-controller/openstack_image.go, ciao-image/datastore/datastore.go, ciao-image/datastore/datastore_test.go, ciao-image/datastore/metads.go, ciao-image/datastore/noop.go, ciao-image/datastore/store.go, database/boltdb.go, openstack/identity/identity.go, openstack/image/api.go, openstack/image/api_test.go, service/service.go, testutil/singlevm/setup.sh
It's using a new metadata field called ``visibility`` which defines the access
restrictions that users and CIAO inself have when trying to access the images
catalog. Below are the 3 main types of visibility that are supported:
- Internal
- CIAO cluster's internal images (e.g. cnci)
- Only created by members of admin tenant/project
- Private
- Default visibility for any created image
- Only available in the tenant/project where it was created
- Public
- Only created/deleted by members of admin tenant/project
- Available in all tenants/projects
=> ciao-image: Add support for private, public and internal images

_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/tasks/main.yml, _DeploymentAndDistroPackaging/ansible/roles/ciao-controller/tasks/upload_images.yml
This commit add support for defining visibility on initial images
that are created by ansible. CNCI image will be kept as internal
image and for the rest of images, they will remain as public images.
=> ansible: Add visibility support for sample images

_DeploymentAndDistroPackaging/ansible/roles/ciao-common/vars/Clear.yml
This bundle contains docker-py which is required on the controller
node by ansible in order to launch containers
=> ansible: Add sysadmin-remote bundle as dependency for ClearLinux

testutil/ciao-down/deps.go
This commit updates the deps.go file to ensure that qemu-img is installed on
Ubuntu and Fedora.  It is not part of the qemu-system-x86 package on these
distributions and so we cannot assume that it is installed by virtue of installing
qemu itself.
=> ciao-down: Ensure qemu-img is installed

ciao-controller/client.go, ciao-controller/external_ip.go
When an external IP is mapped for a tenant consume the resource and
release when IP unmapped.
Fixes: #1234
=> ciao-controller: Track external IP map/unmap in quota system

ciao-controller/api/api.go
The route for {tenant_id}/pools GET was not being exposed. Correct
the route to allow unprivileged GET calls to work for pools.
=> ciao-controller: api: fix route for tenant pools list

bat/workload.go, ciao-cli/workload.go, ciao-controller/api/api.go, ciao-controller/api/api_test.go, ciao-controller/workload.go
Modify controller and ciao-cli to support a "workload show" command. This command will display a workload definition and config in yaml format.
Fixes: #1012 #1013 #1134
=> Add support for workload show

ciao-controller/openstack_volume.go, openstack/block/api.go
With this change the user gets clear feedback that the error came from
an over quota situation.
In order to facilitate this change it was necessary to report the
error's message to the user in the HTTP error message.
Fixes: #1088
=> ciao-controller: Ensure quota errors are flagged as such

ciao-controller/client.go, ciao-controller/internal/datastore/datastore.go, ciao-launcher/instance.go, ciao-launcher/instance_test.go, ciao-launcher/main.go, ciao-launcher/payload.go, ciao-launcher/payload_test.go, ciao-launcher/ssntp.go, ciao-launcher/start_error.go, ciao-launcher/start_instance.go, ciao-launcher/tests/ciaolc/ciaolc.go, ciao-launcher/vmconfig.go, ciao-scheduler/scheduler.go, ciao-scheduler/scheduler_internal_test.go, payloads/start.go, payloads/startfailure.go, payloads/stop.go, testutil/payloads.go
This PR addresses some of the comments made on PR #1226.  It renames some variables, factorizes some code, adds comment to some confusing parts of launcher and fixes a nasty bug in scheduler that could have lead to restarted instances being deleted if the attempt to restart them failed in scheduler.
=> Instance migration refinements

ciao-cli/node.go, ciao-cli/tenant.go, ciao-cli/volume.go
These command were broken by the PR that moved the template code into
a separate package, templateutils.  The old implementation of createTemplate
returned nil, nil if the template script was an empty string and the commands
listed above relied on this behaviour.  The templateutils version of
CreateTemplate returns an error if the template string is "" and this is what
was causing those commands to fail.  This commit adds a check to each of these
commands to ensure that the template script is not empty before caling
templateutils.CreateTemplate.
=> ciao-cli: Fix node, tenant and volume list commands

testutil/ciao-down/ciao_down.go, testutil/ciao-down/vm.go
This commit modifies the ciao-down connect command to only use the
identity key generated by ciao-down.  We've had some reports that
users with a lot of keys in their .ssh directories are unable to
connect to a ciao-down VM, as ssh seems to be trying these keys
in preference to the key supplied by ciao-down, and is giving
up after a number of connection attempts have failed.
=> ciao-down: Only use ciao-down ssh key

networking/libsnnet/cn.go, testutil/singlevm/cleanup.sh, testutil/singlevm/setup.sh
The firewall rules within a ciao-down virtual machine prevent traffic
from instances launched within ciao-down using ciao from gaining
external connectivity. This is due to the absence for iptables rules
that allow connectivity between the physical network and the ciao
network.
Explicitly enable packet forwarding between the external network and
the logical ciao-down network by adding firewall rules.
However do not allow forwarding between the external network and ciao
network in the case of a bare metal deployment. This ensures that
user defined firewall rules are not violated. The user in this case
needs to explicitly enable forwarding of traffic from the external
network.
Fixes https://github.com/01org/ciao/issues/1258
=> ciao-down: single vm: Provide external network access for ciao instances

_release/bat/storage_bat/storage_bat_test.go, _release/bat/workload_bat/workload_bat_test.go, ciao-cli/workload.go, ciao-controller/instance.go, ciao-controller/openstack_volume.go, ciao-controller/workload.go, ciao-launcher/docker_test.go, ciao-storage/block.go, ciao-storage/ceph.go, ciao-storage/noop.go
Add support for resizing volumes via the Open Stack API (ciao-cli volume add) and via workload definitions when the source for the volume is either another volume or an image.
=> Volume resizing at creation time

ciao-cli/instance.go, ciao-controller/client.go, ciao-controller/command.go, ciao-controller/controller_test.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/openstack_compute.go, ciao-controller/types/types.go, openstack/compute/api.go, openstack/compute/api_test.go
This PR implements some basic support for names for instances. These names must be tenant unique and will be used for the hostname inside the instance (and thus the DHCP created DNS entry.)
=> Support naming instances

bat/compute.go, ciao-cli/node.go, ciao-controller/api.go, ciao-controller/client.go, ciao-controller/compute_test.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/legacy_api.go, ciao-controller/types/types.go, ciao-scheduler/scheduler.go
Currently controller doesn't track connected nodes' node type (ie: compute
or network) and then in response to a "nodes" listing query via api (eg:
"ciao-cli node list --compute") the controller will report all nodes
with a running launcher sending stats frames. To support listing just
compute nodes, I add a NodeType into the datastore's node type which is
used for the in-memory ephemeral info cache. Upon node connection
this information is stored. Node listing can then disregard any nodes
which aren't compute nodes.
Fixes #1187
Signed-off-by: Tim Pepper timothy.c.pepper@linux.intel.com
( replaces Pull #1193 )
=> ciao-controller: differentiate compute / network nodes

bat/compute.go, ciao-cli/workload.go, ciao-controller/compute_test.go, ciao-controller/openstack_compute.go, openstack/compute/api.go, openstack/compute/api_test.go
This commit fixes OpenStack's compatibility for Disk variable, it's not the Image ID, it refers to the primary disk's size according to OpenStack [Flavor Details API method](https://developer.openstack.org/api-ref/compute/?expanded=list-flavors-with-details-detail#list-flavors-with-details).
A new CIAO specific API will be required in order to show image and storage details. This should be addressed in a separate PR.
Addresses part of #1232
=> ciao-controller: Fix workload's image ID reference in ciao-cli output

ciao-controller/command.go, ciao-controller/workload.go
This PR addresses a bug found when creating non-public workloads before the CNCI has been activated. This is caused by:
- CreateWorkload() creates a tenant without starting a CNCI
- confirmTenant() checked if the tenant was there or didn't have an IP address. In either case it would call addTenant() which would try and call AddTenant() on the database which after 06085307c8e7b3670c88d712177daca0f6f021b4 will return an error on the duplicate tenant being added.
The solution in this PR is to avoid calling AddTenant() twice.
=> Fix tenant CNCI/workload raciness

_release/bat/workload_bat/workload_bat_test.go, bat/external_ip.go, bat/workload.go, k8s/kubicle/cloudinit.go, k8s/kubicle/create.go, k8s/kubicle/delete.go, k8s/kubicle/kubicle.go, k8s/kubicle/workloads.go, testutil/ciao-down/cloudinit.go, testutil/singlevm/setup.sh, testutil/singlevm/verify.sh
kubicle is a small command line tool that makes it easy to set up k8s clusters in ciao.  You need simply to provide a base image, which must be some version of Ubuntu server, and kubicle will do the rest.  In short it creates workloads for k8s master and worker nodes, creates instances from these workloads and joins these instances together to form a k8s cluster.  The tool accepts a number of options, such as the number of worker nodes to create, configuration information for those nodes and the user accounts to create on those nodes.
=> kubicle: A tool for installing kubernetes clusters on ciao

k8s/kubicle/README.md
This commit adds the missing documentation for kubicle.  The README file
explains how to start up and teardown a k8s cluster on ciao.
=> kubicle: Add a README.md file

_release/bat/storage_bat/storage_bat_test.go, ciao-launcher/qemu.go
By disabling the Fedora workload by default, I inadvertently disabled
some of the storage BAT tests.  The tests were skipped as the fedora
workload could not be found.  This commit updates the storage tests
to use the Ubuntu workload which is always present on SingleVM builds.
=> storage_bat: Re-enable storage tests

_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/templates/configuration.yaml.j2, ciao-launcher/tests/ciao-launcher-server/server.go, configuration/README.md, configuration/configuration.go, configuration/configuration_test.go, configuration/file_test.go, payloads/configure.go, payloads/configure_test.go, testutil/payloads.go, testutil/singlevm/setup.sh
The ImageService struct, part of the Configuration payload, is never read
from. The client obtains the image service details via the openstack
endpoints.
=> configuration: Remove unused image service section from configuration

testutil/singlevm/run_launcher.sh
In the past it was necessary to tell launcher network configuration
details. However this is no longer necessary so this change removes the
unused variables.
=> singlevm: Drop unused network lookup from run_launcher.sh

testutil/singlevm/run_controller.sh, testutil/singlevm/setup.sh, testutil/singlevm/setup_images.sh, testutil/singlevm/setup_keystone.sh, testutil/singlevm/setup_webui.sh, testutil/singlevm/setup_workloads.sh
This PR is in preparation for my work on bringing a new deployment tool into ciao. It splits out many of the steps singlevm does into scripts that are then separately sourced moving functionality around to improve legibility but also throughput.
It also addresses some minor bugs around certificate handling and removes some extraneous steps.
=> singlevm: Split up and clean up legacy parts

ciao-controller/main.go, payloads/configure.go
Move the default values for CNCI resources from controller to the
configuration defaults. This allows code that uses InitDefaults() to get
sane defaults for these values.
=> configuration: Move default CNCI configuration values

testutil/ciao-down/README.md, testutil/ciao-down/ciao_down.go, testutil/ciao-down/cloudinit.go, testutil/ciao-down/prepare.go, testutil/ciao-down/vm.go
The commit makes three main changes to ciao-down.
- The settings, e.g., memory, cpu usage and mounts, specified when VMs are created using prepare or started using start, are now persisted.  These settings are re-used when the VM is started at a later date.
- Users can specify which directories they would like to see mounted in the guest VM and the 9p security model used to mount them.  Multiple mounts can be specified.
- Users can specify which ports can be mapped from the host's localhost to the guest VM.
The two vm types currently supported by ciao include one mounted directory by default, the GOPATH.  It is not possible to remove this mount entirely via the command line, although this can be done by editing the ~/.ciao-down/instance/state.yaml.  However, it is possible to change the …
=> Allow ciao-down VMs mounts and mapped ports to be controlled

.travis.yml
This change enables support for building with go 1.9beta2. For now this
is marked as an allowable failure and will not prevent a PR from being
merged.
=> travis: Add 1.9 (beta) builds

.travis.yml
Switch to a tagged version of gometalinter to avoid an issue currently
present in the master version of the tool. This issue has been reported
upstream as alecthomas/gometalinter#307
=> travis: Use tagged gometalinter

ciao-controller/internal/datastore/sqlite3db.go
This PR removes some residual database code that is no longer used after the removal of default workload population from CSV files.
=> sqlite3db: Remove old database population code

networking/libsnnet/cn_container_test.go
Replace the use of go func to launch containers with docker run "-itd"
This should eliminate any potential flakes in networking tests.
=> networking: Eliminate go func's from test cases

ciao-controller/main.go
Fatally log if controller HTTP services return an error. These are run
inside a goroutine as ListenAndServeTLS blocks so it is necessary to
report these errors inside an anonymous function run via a goroutine.
=> ciao-controller: add fatal logging for controller HTTP services

ciao-controller/command.go
The tenant with ID "public" exists in the database to satisfy the
requirement that workloads are associated with a tenant. This
pseudo tenant is thus used to signify that this workload is public.
However as no instances are going to be created with this tenant it is
not necessary to launch a CNCI for the tenant.
Fixes: #1324
=> ciao-controller: Don't start a CNCI for "public" tenant

ciao-cli/external-ips.go, ciao-controller/api/api.go, ciao-controller/types/types.go
Previously this was only exposed to admin users but there is no harm in exposing it to all users (and potential benefits)
Fixes: #1303
=> Expose instance ID to all users of external-ip list

ciao-controller/main.go
For performance controller has separate databases for frequently updated
statistics that are not critical for operation and for state that needs
to be persisted long term. The former being stored in /tmp to avoid
filesystem performance issues. However /tmp is not guaranteed to be
tmpfs (and on Ubuntu 16.04 is not) instead this change switches
controller to use the memory backend to sqlite.
Fixes: #1330
=> ciao-controller: Use memory backend for transient database

.travis.yml, ciao-controller/api.go, ciao-controller/compute_test.go, ciao-controller/legacy_api.go, ciao-controller/main.go, ciao-controller/types/types.go, openstack/compute/api.go
The current swagger instrumentation for the APIs are outdated and unhelpful so we made a decision to remove them from the source tree. This change removes the swagger entries from the source code and disables the documentation generation on travis.
Fixes: #1292
=> Remove swagger instrumentation from Ciao

ciao-cert/main.go, ssntp/certs/certs.go
This PR moves the setting of the bit needed for anchor certificates
from the convenience function that generates a template to the caller.
With this fix every certificate we generate is no longer a CA.
Fixes: #1294
=> ciao-cert: Only set x509.KeyUsageCertSign on anchor certificate

.travis.yml, DeveloperQuickStart.md, _DeploymentAndDistroPackaging/ansible/README.md, ciao-controller/controller_test.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/main.go, ciao-controller/openstack_compute.go, ciao-controller/openstack_image.go, ciao-controller/openstack_volume.go, ciao-image/datastore/ceph.go, ciao-image/datastore/datastore.go, ciao-image/datastore/metads.go, ciao-image/datastore/noop.go, ciao-image/datastore/posix.go, ciao-image/datastore/store.go, testutil/ciao-down/README.md
This PR modifies controller to handle SIGINT and SIGTERM starting a shutdown process when they are received. To do this the new http.Server.Shutdown() added in Go 1.8 is used. This requires bumping the Go requirement to 1.8 which this PR does.
=> Enable graceful shutdown of controller 

k8s/kubicle/README.md, k8s/kubicle/cloudinit.go, k8s/kubicle/create.go, k8s/kubicle/kubicle.go, testutil/ciao-down/workloads/ciao.yaml
This PR contains a number of small improvements to kubicle.
1. kubicle now installs version 1.6.7, a version known to work.  There is currently a race condition in kubicle 1.7.0 which can result in failed k8s installations using kubicle.  The worker nodes are unable to join the cluster.
2. kubectl tool is now installed by ciao-down
3. Some help and documentation updates.
=> Fix kubicle

testutil/ciao-down/workloads/ciao-fedora25.yaml
The workload arranges for some paths to be initialised in the .profile
file, but this file is not read when logging in via an interactive shell.
This commit updates the workload to ensure that the newly created .profile
is read from .bashrc.
=> ciao-down: Fix paths in ciao-fedora25 workload

deviceinfo/deviceinfo.go
It wasn't obvious reading code that was using this function. Documenting
it avoid having to dig around.
Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>
=> deviceinfo: Document that GetMemoryInfo() returns results in MiB

README.md
The ciao README.md contains a link to the old very outdated cluster installation
instructions.  To make matters worse, the link doesn't even exist any more.
This commit simply removes the reference to the broken link.  We can add a new
link once we have a document describing how to set up a cluster using ciao-deploy.
I've also modified the SingleVM link so that it points directly to the main
SingleVM page.
Fixes #1335
=> docs: Remove broken link from the README.md

deviceinfo/deviceinfo.go
GetMemoryInfo needs to return -1, -1 on error. At the moment, failing to
open /proc/meminfo would return the zero values for total and available.
Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>
=> deviceinfo: Return -1 when failing to open /proc/meminfo

testutil/ciao-down/ciao_down.go
We want to able to access the help at any point, so defer the nested VM check until after the flag parsing.
Today, ciao-down can print the nested VM error and exit before it has the change to print the help.
=> Ensure help can be printed at any time

testutil/singlevm/cleanup.sh, testutil/singlevm/setup.sh
The single VM script had a hard coded ubuntu specific interface
naming convention. Now that ciao-down supports all types of
linux distributions, remove this assumption and discover the
primary outgoing interface name dynamically.
=> SingleVM: Setup the NAT rules dynamically within ciao-down

_release/bat/base_bat/base_bat_test.go, bat/compute.go, ciao-cli/examples/README.md, ciao-cli/workload.go, ciao-controller/api/api_test.go, ciao-controller/controller_test.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/openstack_compute.go, ciao-controller/types/types.go, ciao-controller/workload.go, ciao-scheduler/scheduler_internal_test.go, payloads/restart_test.go, payloads/start.go, payloads/start_test.go, testutil/payloads.go
The image ID in the workload has been non-functional since we moved to specifying the image ID as source for a disk in the workload. This PR cleans up the remaining references to image ID by removing the field from the database, payloads and the ciao-cli reporting.
Fixes: #988 
Fixes: #1232
=> Complete removal of workload Image ID

ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go
Although adding IP addresses to the pool checks for duplicates in the IP
addresses already added it does not check for duplicates in the set to
be added.
This change checks that you can't add duplicates that are specified in
the same request.
=> datastore: Don't allow duplicate IPs to be added

ciao-cli/external_ips.go
These commands are privileged so check in ciao-cli and fatal out if the
user is not privileged. This also avoids the problem of trying to reach
non-existant API entry points generated by the automatic url generation
based on privilege.
Fixes: #1288
=> ciao-cli: Pool creation/deletion/addition/removal are privileged

DeveloperQuickStart.md, testutil/ciao-down/README.md, testutil/ciao-down/ciao_down.go, testutil/ciao-down/vm.go, testutil/ciao-down/workload.go
As discussed with Mark and Rob, sadly offline, `ciao-down create` would be a nicer name. Also we want to detach ciao-down from ciao a bit and have explicit workload names instead of defaulting to the ciao workload.
=> ciao-down prepare

testutil/ciao-down/README.md
I failed to grep for --vmtype and so we had a few paragraphs still
mentioning it.
Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>
=> ciao-down: Remove the last mentions of --vmtype

testutil/ciao-down/README.md, testutil/ciao-down/ciao_down.go, testutil/ciao-down/workload.go
With this patch create command is able to create instances from
workload files specified as workload argument.
The custom workload file can be provided using 3 different schemas:
* http
* https
* file
or throght its absolute or relative path
* ../../relative/path
* /absolute/path
for example to create an instance from a file hosted in a remote server:
```
$ ciao-down create https://raw.githubusercontent.com/01org/ciao/master/testutil/ciao-down/workloads/fedora25.yaml
```
fixes #1366
Signed-off-by: Julio Montes <julio.montes@intel.com>
=> ciao-down: add support to specify a workload file as workload 

testutil/ciao-down/ciao_down.go, testutil/ciao-down/instance.go, testutil/ciao-down/mock_test.go, testutil/ciao-down/vm.go, testutil/ciao-down/workload.go, testutil/ciao-down/workload_test.go, testutil/ciao-down/workloads/ciao-fedora25.yaml, testutil/ciao-down/workloads/ciao.yaml, testutil/ciao-down/workloads/clearcontainers.yaml, testutil/ciao-down/workloads/fedora25.yaml, testutil/ciao-down/workloads/xenial.yaml
A bit of simplification in how workloads are written by folding the second document into a `vm` object in the workload description (1st document).
I kept compatibility with the current (and past) workloads by being able to load 1, 2 and 3 YAML documents description and state files. A "migration" happens when saving the state file.
The 2 first commits are part of PR https://github.com/01org/ciao/pull/1372 that should be merged first, but included them here so the two PRs don't conflict.
=> ciao-down: Make workload and state files be only 2 YAML documents 

docs/kubicle_tutorial.md
This commit adds a tutorial on basic ciao usage.  It explains how to set
up ciao in the Single Machine ciao development environment and how to
deploy Kubernetes inside this new ciao cluster.
=> docs: Add kubicle tutorial

ciao-controller/client.go, ciao-controller/controller_test.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go
This PR works to try and ensure that the cache maintained by datastore is consistent with the database. It also works towards being able to enable errcheck for controller.
CNCI / IP related code is not touched to avoid too badly conflicting with #1333
=> ciao-controller: Improve error handling in datastore

ciao-controller/client.go
Correctly use glog.Warningf when reporting errors.
=> ciao-controller: fix warnings in client code

ciao-controller/command.go, ciao-controller/controller_test.go, ciao-controller/main.go
We are no longer going to support the noNetwork option.
Also clean up a unit test which relied on noNetwork.
=> ciao-controller: remove noNetwork support

ciao-controller/cnci_test.go, ciao-controller/controller_test.go
The unit tests for launching CNCIs were dropped along the way.
Add them back in.
=> ciao-controller: add unit tests for launching of CNCI.

qemu/qmp.go, qemu/qmp_test.go
With qemu 2.9, the qmp block-dev command was updated  from:
{ "execute": "blockdev-add", "arguments": { "options": { ... } } }
to:
{ "execute": "blockdev-add", "arguments": { ... } }
Also, instead of id, blockdev-add now requires a node-name for the
root node(https://wiki.qemu.org/index.php/ChangeLog/2.9)
Store the version information with QMPStart and use that to issue
qmp command for adding block devices in the correct format.
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>
=> qemu: Update blockdev-add qmp command to support newer qemu versions

ciao-controller/command.go, ciao-controller/instance.go
The complexity of newConfig is so high, that just about any change
pushes it over the edge of our gocyclo limit of 15. Refactor
newConfig a little bit to make it easier to read and reduce
complexity.
=> ciao-controller: reduce complexity of newConfig

k8s/kubicle/cloudinit.go, k8s/kubicle/create.go
This commit makes two changes to kubicle:
1. It modifies the cloud-init file of both the workers and the master
to retry certain commands that are known to be a little flaky.
This should improve the success rate of setting up a k8s cluster
with kubicle.
2. Kubicle now detects whether the commands that setup the master
node in the cloud-init file fail or not.  If they fail kubicle
reports the error to the user and downloads the
cloud-init-output.log file.
Fixes https://github.com/01org/ciao/issues/1384
=> kubicle: Detect failure to setup master node

ciao-controller/api.go, ciao-controller/client.go, ciao-controller/command.go, ciao-controller/compute_test.go, ciao-controller/controller_test.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/memorydb.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/types/types.go, ciao-controller/utils/utils.go, ciao-controller/utils/utils_test.go
Start storing CNCI instances in the datastore, and treat CNCI
as a special tenant instance. This will allow us to use normal
controller commands (such as restart and delete) in the future to
operate on the CNCI.
=> ciao-controller: store CNCI instance with tenant instances

qemu/qemu.go, qemu/qemu_test.go
In case of a network device, and specifically virtio-net-pci, we need
to update to what is expected by qemu. In this case, the driver name
should be prefixed with "driver=".
=> qemu: Update virtio-net-pci command line

qemu/qemu.go, qemu/qemu_test.go
For some cases, we need to disable the fast MMIO support, by disabling
virtio 1.0. The reason for this is that we want to be able to nest our
qemu VM inside a VM run by an hypervisor with no support for fast MMIO.
=> qemu: Add disable-modern option for all devices

ciao-controller/api/api_test.go
When testing use the router and the HTTP handler that is used in the
live code when testing. This allows for more advanced testing by
supporting the handling of HTTP context variables for e.g. privilege and
by allowing the matching of url parts.
The bulk of this change is substituting valid UUIDs into the test data.
=> ciao-controller: Use routes and handler from the real API for testing

ciao-controller/api/api.go, ciao-controller/legacy_api.go, openstack/block/api.go, openstack/compute/api.go, openstack/image/api.go, openstack/image/api_test.go
http.Error() documentation says "Error replies to the request with the
specified error message and HTTP code. It does not otherwise end the
request; the caller should ensure no further writes are done to w. The
error message should be plain text."
This change ensures that in all codepaths where http.Error() is used
nothing else is written to the the http.ResponseWriter. In all cases
this is achieved by returning early.
=> ciao-controller: Respect http.Error()s requirements

ciao-cli/README.md, ciao-cli/external_ips.go, ciao-cli/identity.go, ciao-cli/image.go, ciao-cli/main.go, ciao-cli/quotas.go, ciao-cli/volume.go, ciao-cli/workload.go, ciao-controller/api/api.go, ciao-controller/api/api_test.go, ciao-controller/controller_test.go, ciao-controller/main.go, ciao-controller/openstack_compute.go, ciao-controller/openstack_image.go, ciao-controller/openstack_volume.go, configuration/configuration_test.go, openstack/block/api.go, openstack/block/api_test.go, openstack/compute/api.go, openstack/compute/api_test.go, openstack/image/api.go, openstack/image/api_test.go, payloads/configure.go, payloads/configure_test.go, testutil/identity.go, testutil/payloads.go
Move all API serving and and requests to use Ciao API port rather than the separate openstack block, image and compute ports.
Follow this change with a cleanup of now unused variables.
=> Put all HTTP services on Ciao port

ciao-launcher/qemu.go, ciao-launcher/qemu_test.go
Enable virto-rng to expose the host's randomness to the guest so that it
has some randomness available for doing any crypto it needs.
=> ciao-launcher: Expose host /dev/random to instances

ciao-controller/main.go, ciao-controller/openstack_compute.go, ciao-controller/openstack_image.go, ciao-controller/openstack_volume.go
In 10a927a379e4834866b32b7d6580107f89959aef an inefficiency was
introduced where HTTP handlers would get wrapped in the openstack
identity handler multiple times. This change removes that excessive
wrapping by expanding the list of services acceptable for the ciao
end point to be the union of all the others allowing all the others to
be removed.
=> ciao-controller: Only setup openstack identity handler once

ciao-controller/client.go, ciao-controller/cnci.go, ciao-controller/cnci_test.go, ciao-controller/command.go, ciao-controller/controller_test.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/main.go, ciao-controller/types/types.go, payloads/stats.go
This commit adds a CNCI controller to help manage the CNCI lifecyle,
and allows for multiple CNCIs per tenant (1 per subnet).
Create and implement CNCI controller interface which supports starting
a CNCI per tenant subnet. When the subnet is no longer in use (the last
host IP is deleted from this subnet), delete the CNCI after a 5 minute
delay.
=> ciao-controller: add a CNCI controller to manage CNCI lifecycle

ciao-scheduler/scheduler.go, networking/ciao-cnci-agent/client.go, networking/ciao-cnci-agent/rand_linux.go, ssntp/ssntp.go, testutil/ciao-down/vm.go, testutil/ciao-down/workloads/ciao-fedora25.yaml, testutil/ciao-down/workloads/ciao.yaml, testutil/singlevm/verify.sh
This PR fixes the slow CNCI startup times and verify.sh failures seen when compiling ciao with Go 1.9. Changes in Go 1.9 meant that the cnci_agent was unable to connect to the scheduler for up to 1 minute after it had started.  The agent's TLS session was blocking waiting for /dev/urandom's entropy pool to be initialsed.  Inside a newly created VM booting for the first time this could take up to a minute, even when using virtio-rng-pci.  The issue is fixed by specifying that the cnci_agent's ssntp's tls session should read from /dev/urandom directly, rather than calling getrandom.
There are a couple of other fixes here including enabling SSNTP logging in the scheduler and increasing the ping time out in verify.sh for the CNCI.
virtio-rng-pci is also enabled for ciao-down
=> Make ciao work with Go 1.9 and enable Go 1.9 in ciao ciao-down workloads

ciao-launcher/qemu.go, qemu/qmp.go, qemu/qmp_test.go
blockdev-del command has been added in qemu 2.9 to replace
x-blockdev-del command used earlier for deleting block devices.
Update ExecuteXBlockdevDel() to use this updated qmp command.
Rename ExecuteXBlockdevDel to ExecuteBlockdevDel as this no longer
executes x-block-del command for qemu>=2.9.
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>
=> qmp: Update block device deletion for newer versions of qemu

ciao-launcher/qemu.go, ciao-launcher/qemu_test.go
Reverts 01org/ciao#1409
My observations are that with this this change our CNCI reboot time varies substantially, from 9s to over 2 minutes. With this change reverted it's sub 10s.
Fixes: #1414
=> Revert "ciao-launcher: Expose host /dev/random to instances"

ciao-controller/client.go, ciao-controller/cnci.go, ciao-controller/types/types.go
Here's a first attempt at implementing migration of the CNCIs.  It's pretty basic but it does improve on what we currently  have.  The PR makes the following changes.
1. The CNCI manager will now restart a CNCI instance that exits or crashes.
2. It is now possible to restart failed CNCIs.
=> Restart cnci and allows failed CNCIs to be restarted

.travis.yml
=> travis: Enable 1.9 release build

ciao-controller/internal/datastore/datastore.go, ciao-controller/openstack_compute.go, ciao-controller/types/types.go
This member is not really needed and is not always up to date.  For up
to date information about an instance's volumes, one should call
GetStorageAttachments.
=> ciao-controller: Remove Instance.Attachments

ciao-cert/README.md, ciao-cert/main.go, ciao-deploy/deploy/setup.go, ciao-deploy/deploy/utils.go, ssntp/certs/certs.go, ssntp/certs/certs_test.go, testutil/ssntp_test_certs.go
Having the ability to choose different certificate types makes the
ability to programmatic creation of certificates, e.g. ciao-deploy
problematic as the type of signing key must be known to to manage these
keys. Instead remove the option to simplify the certificate workflow.
Fixes: #1295
=> ciao-cert: Drop option to choose elliptic curve certs

ciao-cli/instance.go
Ensure that if supplied to ciao-cli instance add, --instances is a
positive number greater than 0.
Fixes: #889
=> ciao-cli: Validate that requested number of instances is positive

ciao-cli/node.go
Make "ciao-cli node show" work when given a node-id and also fix the error message for when --cnci is provided but no --node-id is given.
Fixes: #660
=> ciao-cli node show fix

ciao-controller/command.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/openstack_volume.go, ciao-controller/quotas.go, ciao-controller/types/types.go
Hide the CNCI volume from the output of "ciao-cli volume list" and also make sure that it is not included in the quotas for the user. Do this by establishing an Internal field on types.BlockData that is populated from types.StorageResource (which is statically specified for the CNCI) which can be tested in conditional statements.
Fixes: #1202
=> Hide CNCI volume from user and quotas

.travis.yml
We've made quite a few improvements to the unit tests so we should now
try and run with race detection turned on.
Fixes: #235
=> travis: Enable race detection for unit tests

testutil/ciao-down/README.md, testutil/ciao-down/ciao_down.go, testutil/ciao-down/instance.go, testutil/ciao-down/vm.go
--drive can be used to make a resource acessible on the host
available to the guest as a block device.  Currently, the only
type of resource that is supported is file backed storage stored
on the host, e.g., a qcow2 file.
=> ciao-down: Add the --drive parameter

qemu/qemu.go, qemu/qemu_test.go
Add support for pre-allocating all of the RAM.
This increases the memory footprint of QEMU and should be used
only when needed.
=> qemu: Add support for memory pre-allocation

qemu/qemu.go, qemu/qemu_test.go
Enable realtime options in QEMU. Also add support to control memory
locking. Turning realtime on with memory locking disabled allows
memory to be swapped out, potentially increasing density of VMs.
=> QEMU: Enable realtime options

ciao-launcher/README.md, ciao-launcher/docker_network.go, ciao-launcher/hard_reset.go, ciao-launcher/main.go, ciao-launcher/network.go, networking/libsnnet/docker_plugin.go, testutil/singlevm/cleanup.sh
--hard-reset in launcher was not working very well for a number of reasons.
1. There was a long standing bug about the fact that it could hang.
2. It didn't wipe the docker plugin DB.  This caused problems with ciao-deploy installed clusters.
3. It was unable to cleanly destroy docker containers as the docker plugin DB initialization code was broken.
4. It was unable to cleanly destroy docker containers as it was not passed information about the management and compute nets.
All of these issues are addressed by this PR.  Issues 3 and 4 meant that running a ./cleanup.sh on singlevm was really slow if there were some container instances up and running.
=> Fix a number issues with --hard-reset

qemu/qemu.go, qemu/qemu_test.go
The Mlock knob is unfortunately tied to realtime. Now enable Mlock knob to implicitly enable realtime to get the desired swapping behavior.
=> Knobs: Modify the behaviour of the Mlock knob.

ciao-cli/tenant.go, ciao-controller/api/api.go, ciao-controller/api/api_test.go, ciao-controller/controller_test.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/memorydb.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/tenants.go, ciao-controller/types/types.go
This PR makes the number of bits in the subnet mask a configurable attribute of the tenant. It also allows the tenant name to be configurable.
Fixes: #1407
=> make subnet bits configurable

ciao-cli/tenant.go
Remove print of merge patch from tenant update.
=> ciao-cli: remove stray debug print

testutil/singlevm/setup.sh
Update the ciao_src var to point to the new repo path.
=> singlevm: fix ciao src path

README.md
This commit updates the badges in the README.md file to reflect the change
of the project repo.  It also removes the waffle badge as we aren't currently
using waffle.
=> README: Update badges

CONTRIBUTING.md, _release/ciao-release/main.go, ciao-vendor/ciao-vendor.go
This commit removes the last few references to 01org/ciao.
=> ciao-project: Cleanup all remaining references to 01org/ciao

qemu/qemu.go, qemu/qemu_test.go
VFIO is meant for exposing exposing direct device access
to the virtual machine.
Add ability to append VFIO devices to qemu command line.
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>
=> vfio: Add ability to pass VFIO devices to qemu

_release/bat/base_bat/base_bat_test.go, _release/bat/tenant_bat/tenant_bat.go, _release/bat/tenant_bat/tenant_bat_test.go, bat/compute.go, bat/tenant.go, ciao-cli/tenant.go, ciao-controller/api/api.go, ciao-controller/api/api_test.go, ciao-controller/client.go, ciao-controller/client_wrapper_test.go, ciao-controller/command.go, ciao-controller/controller_test.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/memorydb.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/tenants.go, ciao-controller/types/types.go, payloads/stats.go
Add tenant create and delete support. Tenant create will create a new tenant with a given config. Tenant delete will remove a tenant and all it's associated objects, including instances, workloads, images, storage, and external IPs.
add some BAT tests to exercise our new tenant APIs. 
Fixes: #1435
=> Add tenant create/delete and BAT tests

ciao-controller/internal/datastore/datastore.go
When a CNCI is deleted the volume should not be leaked.
Fixes: #1446
=> ciao-controller: Make CNCI volume ephemeral

ciao-controller/command.go, ciao-controller/controller_test.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/types/types.go
Change the instance StateLock to be a struct rather than a pointer.
This way it is initialized at Instance creation.
Fixes: #1467
=> ciao-controller: do not use a pointer for instance state lock

ciao-deploy/cmd/setup.go, ciao-deploy/deploy/setup.go, ciao-deploy/deploy/utils.go
When the HTTPS certificate uses a FQDN it is necessary to let the user of ciao-deploy specify the name the controller's certificate specifies so that the invocations of ciao-cli will work.
Fixes: #1459
=> ciao-deploy: Allow overriding name controller is reachable with

ciao-cli/image.go, ciao-image/datastore/store.go
When an image upload fails it should be reported to the user and the database correctly updated.
Fixes: #1469
=> Handle image upload failures

ciao-deploy/deploy/nodes.go
Use the absolute path for launcher when resetting because /usr/local/bin
isn't always in the default system PATH.
=> ciao-deploy: use absolute path for launcher when resetting

ciao-cli/node.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/types/types.go
Modify types.CiaoNode to contain a Hostname value. Populate
this value when stats are received from a node. Modify ciao-cli
to dump the Hostname value.
Fixes: #1462 
=> report Node Hostname information with node list/show

ciao-launcher/attachvolume_error.go, ciao-launcher/delete_error.go, ciao-launcher/detachvolume_error.go, ciao-launcher/payload.go, ciao-launcher/start_error.go, payloads/attachvolumefailure.go, payloads/attachvolumefailure_test.go, payloads/deletefailure.go, payloads/deletefailure_test.go, payloads/detachvolumefailure.go, payloads/detachvolumefailure_test.go, payloads/startfailure.go, payloads/startfailure_test.go, testutil/payloads.go
This PR modifies the error payloads sent by launcher and launcher itself, so that these errors contain the node id of the node that generated the error.
=> Report NodeID in launcher error payloads

_release/bat/storage_bat/storage_bat_test.go, ciao-controller/controller_test.go, ciao-controller/openstack_volume.go
Reject requests to detach volumes from instances that are not exited as live detach is flaky due to relying on guest OS support. Update the BAT tests to stop the instances prior to trying to detach.
Fixes: #1315
=> Disable live detach in controller

ciao-cli/node.go, ciao-controller/client.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/memorydb.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/types/types.go
If we have node information for a failure, store and increment
stats per node and report via CiaoNode. Note that these stats
are not persistent - they will be cleared when the node is
removed or when the controller is restarted.
=> Add failure stats to ciao nodes

testutil/singlevm/cleanup.sh, testutil/singlevm/setup.sh
Use "go env GOPATH" to get the desired $GOPATH if needing to use a
fallback.
Fixes: #1323
=> singlevm: Do not access $GOPATH directly

ciao-controller/main.go, configuration/README.md, configuration/configuration_test.go, payloads/configure.go, testutil/payloads.go
ciao-deploy doesn't currently set this field in the configuration but for the HTTP entry points that use absolute URLs we need to something better than os.Hostname() for when controller is being reached via a FQDN.
=> Remove compute_fqdn

ciao-deploy/deploy/utils.go
When an SSH command generates an error (e.g. non-zero exit code) embed
the output containing the command's stdout and stderr into the error
returned. This will then be printed out as part of the detailed error
message.
=> ciao-deploy: When an SSH command fails report stdout/stderr

testutil/singlevm/cleanup.sh, testutil/singlevm/setup.sh
There were a number of issues with the ceph storage tests on singlevm.
1. They were not being run on new installs as /etc/ciao/configuration.yaml is
not world readable when created by ciao-deploy.
2. cleanup.sh did not delete this file.
3. The ceph id in /etc/ciao/configuration.yaml was incorrect.  It was set to
admin instead of ciao.
=> singlevm: Fix storage tests

_release/bat/image_bat/image_bat_test.go, _release/bat/storage_bat/storage_bat_test.go, _release/bat/workload_bat/workload_bat_test.go, bat/image.go, ciao-deploy/deploy/cnci.go, ciao-deploy/deploy/workloads.go
Previously only the admin user could create images however that is no
longer the case and the BAT tests have not been updated to reflect that.
The change in the bat package to support this added a new boolean
parameter to all bat image functions to indicate whether to run as admin
or not. This necessitated changes to the bat tests but also to
ciao-deploy that uses the bat package to upload images.
Fixes: #1520
=> bat: Run some image BAT tests as non-admin user

ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-launcher/attachvolume_instance.go, ciao-launcher/qemu.go
This PR addresses storage related issues in ciao
1. Data volumes cannot be live attached to instances in qemu 2.10
2. Launcher did not always cleanup properly when a live attach failed.
3. Controller was incorrectly unattaching volumes from instances if a stats command was received from that instance while an attach command was outstanding.
=> Qemu 2.10 and general storage fixes

qemu/qemu.go, qemu/qemu_test.go
Add support for macvtap interfaces. This also brings in support
for generic multiqueue support in virt containers.
=> Networking: Add support for handling macvtap interfaces

ciao-controller/internal/quotas/quotas.go, ciao-controller/internal/quotas/quotas_test.go, ciao-controller/tenants.go
Although the quota data was being deleted from the database it was not being deleted from the quota service. If the tenant was recreated then the quota service would have inconsistent data compared to the database.
Fixes: #1468
=>  ciao-controller: when deleting tenant also delete from quota service

ciao-controller/internal/datastore/sqlite3db.go
initialize the StateChange condition variable when creating
instance structs.
Fixes: #1547
=> ciao-controller: sqlitedb: initialize Instance StateChange

ciao-controller/controller_test.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go
A tenant network may not contained mixed networks with variable subnet bits.
Do not allow update to tenant if there are any active instances at all,
including cncis.
Fixes: #1535
=> ciao-controller: do not allow subnet bits to be modified if active instances

ciao-deploy/cmd/setup.go, ciao-deploy/deploy/setup.go
Enable memory limit checking by launcher by default,
and only disable if --disable-limits is passed to ciao-deploy setup.
Fixes: #1539 
=> ciao-deploy: enable memory limits by default

_release/bat/tenant_bat/tenant_bat_test.go, bat/tenant.go, ciao-cli/tenant.go, ciao-controller/tenants.go
Due to the private IP address block that is used for ciao tenant
networks, the subnet bits value must be a value between 12 and 30.
Fixes: #1497 
=> Restrict subnet-bits value to a range between 12-30

ciao-controller/main.go
If logDirFlag fails to set, we should report the error and exit.
If it does not fail to set, we should not report an error.
Fixes: #1552
=> ciao-controller: report errors properly when setting logDirFlag value

ciao-deploy/deploy/setup.go
In newer kernels, systemd's TasksMax is set too low for ciao
when launching thousands of instances. Set TasksMax to infinity
for the service file to allow ciao to spawn larger numbers of
pthreads.
Fixes: #1556
=> ciao-deploy: set TasksMax in systemd service file

ciao-controller/cnci.go, ciao-controller/cnci_test.go, ciao-controller/command.go, ciao-controller/controller_test.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/memorydb.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/tenants.go, ciao-controller/types/types.go
The existing tenant IP allocation algorithm doesn't work unless you
have a /24 network. Rework the algorithm so that it will work with
any valid network. Also add the ability to allocate more than one
IP addresses at a time.
Fixes: #1491 
=> ciao-controller: rework tenant IP allocation

ciao-deploy/deploy/auth.go
When reusing the existing admin certificate the message reported did not
have a trailing newline.
=> ciao-deploy: Fix missing \n in output

ciao-controller/tenants.go
When deleting a tenant delete both the image metadata and the image data
itself.
=> ciao-controller: Delete image metadata and data

ciao-controller/internal/datastore/datastore.go
Log instance deleted events as event rather than errors.
Fixes: #1551
=> ciao-controller: Fix reporting level for instance deleted events

ciao-controller/api/api.go, ciao-controller/api/api_test.go, ciao-controller/client.go, ciao-controller/command.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/memorydb.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/internal/datastore/sqlite3db_test.go, ciao-controller/quotas.go, ciao-controller/types/types.go, ciao-controller/workload.go
Copy the methodology used for images onto workloads allowing us to remove the pseudo-tenant "public". Workloads gain a visibility field which is persisted into the database and the cache is modified to have slices of IDs for workloads associated with a given tenant or which are public.
Fixes: #1328
=> Remove "public" tenant

testutil/semaphore/build.sh
Consolidate all build commands into a single script which can also be
run outside of semaphore for greater reproducibility.
=> testutil: Add a semaphore build script

qemu/qmp.go
Add ability to hotplug a pci device bound to
vfio-pci driver.
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>
=> qemu: Add function to hotplug vfio device

ciao-controller/client.go, ciao-controller/cnci.go, ciao-controller/command.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/types/types.go, payloads/stats.go
When a node is deleted from the database mark the instance as missing
and reset the node ID associated with the instance. If the node comes
back then the instance will be transitioned to active again by the
stats being received.
=>  ciao-controller: Mark instances as missing when node is deleted

ciao-controller/internal/datastore/datastore.go
This commit fixes a small bug in which images and workloads were corrupted in
the controller cache after a service restart.  The workloads were being added
to the images slice by mistake.
Fixes: https://github.com/ciao-project/ciao/issues/1576
=> ciao-controller: Initialise workloads correctly on restart

ciao-controller/main.go, ciao-launcher/main.go, ciao-scheduler/scheduler.go
If our daemons panic we should capture the panic backtrace and send it
to glog. It is important to flush glog otherwise the output may not get
written to the files.
Fixes: #1571
=> ciao-{controller,launcher,scheduler}: log panics to glog

ciao-deploy/deploy/cnci.go, ciao-deploy/deploy/utils.go
Rather than use a custom image, just use the latest clear release
as a base image and install the packages we need.
=> ciao-deploy: use a generic base clear image for building cnci.

ciao-launcher/delete_instance.go, ciao-launcher/docker_network.go, ciao-launcher/hard_reset.go, ciao-launcher/instance.go, ciao-launcher/main.go, ciao-launcher/overseer.go, ciao-launcher/process_stats.go, ciao-launcher/start_instance.go
This PR fixes a number of small issues with launcher.
1. There was a nasty race condition when deleting VNICs of instances.
2. Hard-reset was not cleaning all the files and directories created launcher.
3. There were a few little issues with logs scatter throughout the code.
=> ciao-launcher: Fix hard-reset, a race condition and some logs

_release/bat/quotas_bat/quotas_bat_test.go
This test was creating and deleting instances but was not waiting for the
instances to be fully deleted before terminating.  This led to a race
condition in which instances could still be alive when the subsequent
test started.  As this test assumed no instances on start this race led
to an occasional failure of the following test (TestInstanceUsageAfterDenial).
This commit fixes the problem by ensuring that all instances have been
fully deleted before TestInstanceLimited terminates.
=> BAT: Fix a race condition in TestInstanceLimited

osprepare/osprepare.go
osprepare was installing or at least attempting to install cephfs as a
core dependency.  We no longer use cephfs and haven't for over a year.
=> osprepare: Remove cephfs as a core dependency

ciao-controller/main.go, ciao-deploy/cmd/setup.go, ciao-deploy/deploy/nodes.go, ciao-deploy/deploy/setup.go, ciao-deploy/deploy/utils.go, ciao-deploy/scripts/cleanup.sh, ciao-launcher/README.md, ciao-launcher/docker.go, ciao-launcher/instance_test.go, ciao-launcher/main.go, ciao-launcher/network.go, ciao-launcher/qemu.go, ciao-launcher/simulation.go, ciao-launcher/start_instance.go, ciao-launcher/tests/ciao-launcher-server/server.go, ciao-launcher/virtualizer.go, ciao-scheduler/scheduler.go, configuration/README.md, configuration/configuration_test.go, networking/libsnnet/cn.go, networking/libsnnet/network.go, networking/libsnnet/vnic.go, payloads/configure.go, payloads/configure_test.go, qemu/examples_test.go, qemu/image.go, qemu/qemu.go, testutil/payloads.go
This is a large PR designed to improve the security of ciao ( and fix a number of other bugs in the process ).  Essentially, it modifies ciao-deploy and the ciao services to ensure that these services run with lower privileges than before.   ciao-scheduler and ciao-controller now run as non-root (under a new user called ciao).  ciao-launcher still runs as root but with reduced capabilities.  The majority of the processes spawned by ciao-launcher now also run as the ciao user with no special privileges.  This means that the qemu instances that support VM workloads no longer run as root.
This PR also modifies the way in which ciao's dependencies are installed.  It creates a new set of services ciao-[service-name]-prepare that runs the services as root passing an -oprepare flag.  The …
=> Reduce capabilities of ciao services and their children

_release/bat/workload_bat/workload_bat_test.go, bat/workload.go, ciao-cli/examples/fedora_cloud.yaml, ciao-cli/examples/fedora_cloud_disk.yaml, ciao-cli/image.go, ciao-cli/instance.go, ciao-cli/workload.go, ciao-controller/compute.go, ciao-controller/controller_test.go, ciao-controller/image.go, ciao-controller/instance.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/internal/datastore/sqlite3db.go, ciao-controller/types/types.go, ciao-controller/workload.go, ciao-deploy/deploy/cnci.go, ciao-deploy/deploy/workloads.go, k8s/kubicle/cloudinit.go
This PR enables the use of image names (and enforces some rules on them) in workload definitions as part of the storage sources.
The name is resolved at workload creation time to an ID and that is what is preserved in the database. The PR also makes some cleanups related to the code adjacent to this change.
=> Use image names in workload definition

ciao-controller/controller_test.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-controller/main.go, ciao-deploy/cmd/setup.go, ciao-deploy/deploy/setup.go, configuration/configuration_test.go, payloads/configure.go, testutil/payloads.go, testutil/singlevm/setup.sh
Remove admin password for CNCI. The admin can provide an SSH key and get passwordless sudo anyway. This fixes a security issue where not specifying a password would set it to "ciao" and allow access.
=> Remove CNCI admin password

ciao-controller/main.go, ciao-launcher/main.go, ciao-scheduler/scheduler.go
This reverts commit 702b3312fa7b0d3c4b5306ecc8326255eceba173.
Unfortunately this only works on panic()s from the main goroutine which
makes it generally unhelpful. For consistency stop logging any panics to
the glog. As they are reported on stderr they can be found in the
systemd logs.
=> Revert "ciao-{controller,launcher,scheduler}: log panics to glog"

_release/bat/workload_bat/workload_bat_test.go
Add a test to create a workload with a docker container using the
default registry and another one with the registry explicitly
specified.
=> workload_bat: Add container workload tests

testutil/singlevm/verify.sh
Verify is frequently failing on semaphore due to event counts not
matching up. Until we get synchronous operations in ciao the best thing
we can do is bump up the event retry count and the sleep times.
=> testutil: Bump sleep times in verify.sh

ciao-controller/api/api.go, ciao-controller/controller_test.go, ciao-controller/instance.go, ciao-controller/volume.go
The paths to create volumes for an instance and to create volumes
explicitly duplicated lot of code which this commit consolidates.
=> ciao-controller: remove duplicate volume creation paths

qemu/qmp.go
This patch adds a new function to hot plug VFIO devices on PCI(E) bridges,
This change allows to hot plug N VFIO devices in Qemu PC and Q35
Signed-off-by: Julio Montes <julio.montes@intel.com>
=> qmp: Add support for hot plugging VFIO devices on PCI(E) bridges

_release/bat/workload_bat/workload_bat_test.go, ciao-controller/image.go, ciao-controller/internal/datastore/datastore.go, ciao-controller/internal/datastore/datastore_test.go, ciao-deploy/deploy/workloads.go
The original code for implementing image name resolution inadvertently
enforced a restriction of image name uniqueness across the whole cluster
rather than per-tenant. Adopt the same algorithm that instance name
resolution uses so that the uniqueness is only per tenant.
=> ciao-controller: support same image name for multiple tenants

ciao-deploy/deploy/cnci.go, ciao-deploy/deploy/utils.go
It turns out that the "latest" file that is located on clearlinux.org
only refers to the latest generated image, but that image may not
necessarily end up in download.clearlinux.org/image if it does not
pass QA for some reason. Therefore, any cloud image located in
clearlinux.org/image is the last known good image and should be
used. Modify getCNCIURL() to download the images listing and look
for the cloud image filename to use from there.
=> ciao-deploy: do not use latest for cnci version, use last known good

_release/bat/workload_bat/workload_bat_test.go, bat/compute.go
Originally workload_bat called ciao-cli directly to get the details of
compute nodes in order to get hostname for scheduling. Instead switch to
use bat.GetComputeNodes() after adding the hostname to the
datastructure.
=> workload_bat: switch to use bat.GetComputeNodes()

_release/bat/base_bat/base_bat_test.go, bat/compute.go, ciao-cli/node.go, ciao-controller/api.go, ciao-controller/compute_test.go, ciao-controller/legacy_api.go, ciao-controller/types/types.go, client/legacy.go
Remove legacy API for node summary and "ciao-cli node status" command that uses it along with BAT testing functionality relating to it.
=> Remove node status API and command

qemu/qmp.go, qemu/qmp_test.go
This patch adds a new function to hot add CPUs in a QEMU instance
Signed-off-by: Julio Montes <julio.montes@intel.com>
=> qemu: add function to hotplug CPUs

qemu/qemu.go, qemu/qemu_test.go
Add ability to add a vhostuser device to the
QEMU commandline.  We expect two different types of devices
to be connected through a vhostuser socket: SCSI and network.
Signed-off-by: Eric Ernst <eric.ernst@intel.com>
=> qemu: introduce vhost-user handling

packages.json, vendor/github.com/intel/tfortools/defaults.go, vendor/github.com/intel/tfortools/funcs.go, vendor/github.com/intel/tfortools/tfortools.go
This adds a number of new functions:
- tocsv outputs a collection of structs in CSV format
- totable converts a slice of a slice strings into a slice of structs
- htable, htablex, htablealt, htablexalt output slices of structs as a sequence of tables.
=> 3rd party: Revendor tfortools to v0.2.0

networking/ciao-cnci-agent/network.go
There was a bug in the CNCI agent which was incorrectly computing the
number of ip addresses in a subnet.  The result being that it was
impossible to ssh into the last instance in a subnet.
Fixes: https://github.com/ciao-project/ciao/issues/1615
=> networking: Enable ssh for the last instance in a subnet

ciao-vendor/ciao-vendor.go, packages.json, vendor/github.com/intel/govmm/COPYING, vendor/github.com/intel/govmm/README.md, vendor/github.com/intel/tfortools/COPYING, vendor/golang.org/x/sys/AUTHORS, vendor/golang.org/x/sys/CONTRIBUTORS, vendor/golang.org/x/sys/LICENSE, vendor/golang.org/x/sys/PATENTS, vendor/golang.org/x/sys/README.md
Documents were missing for three of the vendored packages.  This was partly due to a bug in ciao vendor and partly due to a mistake in the way in which certain packages were vendored.  This PR adds the missing documents and patches ciao-vendor.
=> Add missing vendored documents

k8s/kubicle/kubicle.go
This commit updates the default version of k8s used by kubicle.  There was a
race condition in the old default version, that could cause kubeadm to fail
randomly.
=> kubicle: Update default k8s version to 1.8.4

ciao-controller/client.go, ciao-controller/client_wrapper_test.go, ciao-controller/cnci.go, ciao-controller/main.go, ciao-deploy/cmd/setup.go, ciao-deploy/deploy/setup.go, ciao-scheduler/scheduler.go, configuration/configuration_test.go, networking/ciao-cnci-agent/client.go, networking/ciao-cnci-agent/network.go, networking/libsnnet/cn.go, networking/libsnnet/cn_test.go, networking/libsnnet/cnci.go, networking/libsnnet/cnci_test.go, networking/libsnnet/fuzz_test.go, networking/libsnnet/gre.go, networking/libsnnet/gre_test.go, networking/libsnnet/gretun.go, networking/libsnnet/internal_test.go, networking/libsnnet/network.go, networking/libsnnet/utils.go, payloads/concentratorinstancerefresh.go, payloads/concentratorinstancerefresh_test.go, payloads/configure.go, payloads/configure_test.go, ssntp/ssntp.go, testutil/payloads.go
This PR implements the remainder of the support for per subnet CNCIs. Each tenant will now have a set of CNCIs, one per subnet. When a new CNCI is added or removed, as indicated by a ConcentratorInstanceAdded event, the controller will send each CNCI a list of the current CNCIs for that tenant. Each CNCI will have an IP allocated to it which will become a GRE tunnel endpoint. Each CNCI will create a point to multipoint GRE tunnel to direct traffic to the appropriate CNCI as necessary.
=> send cnci refresh command
