CONTRIBUTING.md
ciao-cli/README.md
ciao-controller/README.md
ciao-controller/internal/datastore/datastore.go
ciao-launcher/README.md
ciao-scheduler/README.md
networking/cnci_agent/README.md
networking/cnci_agent/test_cnci_server/README.md
networking/libsnnet/benchmark_test.go
networking/libsnnet/cn.go
networking/libsnnet/cn_container_test.go
networking/libsnnet/cn_test.go
networking/libsnnet/cnci.go
networking/libsnnet/docker_plugin.go
ssntp/README.md
ssntp/forward.go

Came across goreportcard.com and misspell and decided to give it a go (ah!).

20160427 typos

---

.travis.yml

travis: Create SSNTP certs and run SSNTP tests

---

.travis.yml

travis: Enable ciao-controller unit tests

---

.travis.yml
networking/libsnnet/cn.go
networking/libsnnet/cn_container_test.go
networking/libsnnet/cn_test.go
networking/libsnnet/cnci.go
networking/libsnnet/firewall_test.go
networking/libsnnet/net_release.go
networking/libsnnet/net_test.go

- Added docker support to travis CI
- Update the docker on travis CI to the latest
- Create dummy interface to test networking
- Added explicit travis CI awareness to code (revisit this later)

Networking: Travis CI Support

---

ciao-controller/internal/datastore/sqlite3db.go

Address issue #81
Go uses prepared statements for you under the covers... unless you
override this by using Sprintf.  Since prepared statements are
more secure, only use Sprintf if you have a very good reason - which
I didn't.

ciao-controller: datastore: use prepared statements rather than Sprintf

---

test-cases/test-cases.go

This should make it easier to visually identify which tests have failed
in a Travis CI build.  Note that the tabwriter package does not work properly
with ANSI escape sequences so we needed to write our own custom table
ouput function to make this work.

test-cases: Failed tests are now coloured red

---

ciao-launcher/docker_network.go
ciao-launcher/instance.go
ciao-launcher/main.go
ciao-launcher/network.go
ciao-launcher/overseer.go
ciao-launcher/qemu.go
ciao-launcher/tests/examples/start_efi.yaml
ciao-launcher/tests/examples/start_legacy.yaml
ciao-launcher/tests/examples/stress/efi.sh
ciao-launcher/tests/examples/stress/legacy.sh

This PR fixes
1. All issues reported by errcheck in ciao-launcher.
2. All but one gocyclo error in launcher.
3. Some problems with example yaml files used to test ciao-launcher locally.
The gocylco fixes address some of the problems reported in #10

ciao-launcher: Fix errcheck, gocyclo and example yaml files

---

.travis.yml

run ciao-controller/internal/datastore tests
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

travis: run ciao-controller/internal/datastore tests

---

ciao-scheduler/doc.go
ciao-scheduler/export_test.go
ciao-scheduler/scheduler.go
ciao-scheduler/scheduler_internal_test.go

This series enables go test of scheduler and fixes a couple issues observed when running the test.

ciao-scheduler: add first unit test and benchmark

---

ciao-launcher/overseer.go

overseer.processCommand was too long.  It's now been split into
multiple functions.  Splitting it was quite easy as it didn't
have any local variables.

ciao-launcher: Fix remaining gocyclo issue.

---

networking/ciao-cnci-agent/scripts/README.md
networking/ciao-cnci-agent/scripts/generate_cnci_cloud_image.sh

- Fix a reference to cnci-agent in README.md
- Fix $cnci-agent var in generate_cnci_cloud_image.sh

network: Fix bugs introduced in 2293e2

---

networking/libsnnet/tests/cncicli/cncicli.go
networking/libsnnet/tests/cncli/cncli.go

Reduce the cyclomatic complexity of the test tools used to
manually setup networking interfaces.

Networking: Tests: Reduce cyclomatic complexity

---

ciao-vendor/ciao-vendor.go

The code that computes the packages that need to be copied
from each synced repo has been split out into a separate function
called computeSubPackages.  Previously this code was part
of vendor.

ciao-vendor: Fix gocyclo issue

---

ciao-scheduler/export_test.go
ciao-scheduler/scheduler.go
ciao-scheduler/scheduler_internal_test.go
ssntp/forward.go

This PR is for an scheduler unit test enhancement to cover workload starting.

ciao-scheduler: Unittests

---

ciao-controller/controller_test.go
ciao-controller/main.go
testutil/identity.go
testutil/identity_test.go

@mcastelino moved PR #139 to your branch

add identity service to single machine setup

---

README.md

Ciao is documented on godoc, let's show that.

README: One more badge

---

payloads/compute.go

Introduced when implementing the flavors/detail endpoint.

payloads: Fix misspelling

---

ciao-vendor/ciao-vendor.go

The ciao-vendor uses command now accepts a -d option.  When specified
uses only outputs the packages that directly import a given package.
Fixes: #199

ciao-vendor: Add -d option to uses command

---

configuration/README.md

With an architectural overview and a couple of configuration
YAML examples.
A link to the configuration wiki will be added.
Fixes #227

configuration: Add README

---

ciao-cli/README.md
ciao-cli/event.go
ciao-cli/identity.go
ciao-cli/instance.go
ciao-cli/main.go
ciao-cli/node.go
ciao-cli/tenant.go
ciao-cli/trace.go
ciao-cli/workload.go

ciao-cli instance [add list delete restart stop]
ciao-cli workload [list]
ciao-cli tenant [list]
ciao-cli event [list delete]

ciao-cli: Implement subcommands

---

networking/ciao-cnci-agent/scripts/generate_cnci_cloud_image.sh
testutil/singlevm/setup.sh

This commit fixes https://github.com/01org/ciao/issues/249
The qemu-nbd command sporadically fails. This is a bug in qemu-nbd
See https://bugzilla.redhat.com/show_bug.cgi?id=1111635
This is due to udev taking an unpredictable time to run
As a workaround the test calls "udevadm settle"  and retries the mount
a few times which fixes the issue.
This commit also fixes https://github.com/01org/ciao/issues/248
The SSH connectivity test failed sporadically. This was due to the
fact that the VM's may take long time to boot as the VM's are running
on two levels of virtualization.
The test now retries the SSH connetivity multiple times. However on
really slow hardware this test may not succeed and has to be run manually.

Single VM Dev: Use the new ciao-cli logic + Bug fixes

---

ciao-launcher/tests/ciao-launcher-server/server.go

This commit updates ciao-server-launcher to work with the new
ciao cluster configuration framework.  This update is necessary
to fully test launcher in isolation of the other ciao components.
Without this change it isn't possible to specify the management
network of the launchers under test, for example.
Fixes #283

ciao-launcher: Cluster config update for ciao-server-launcher

---

ciao-controller/controller_test.go
testutil/agent.go
testutil/agent_test.go
testutil/client_server_test.go
testutil/controller.go
testutil/controller_test.go
testutil/server.go
testutil/server_test.go
testutil/testutil.go

This PR includes some refactoring, comments, additional helper functions and test coverage examples for how to implement forced failure scenarios.

testutil: more test coverage

---

_release/bat/README
_release/bat/release_test.py

Add an "\_release" directory to the ciao project. The "\_" prefix
tells the go compiler to ignore this directory. This directory
will contain code related to the ciao release process. This commit
adds a "bat" subdirectory under the _release directory with a single
python test script. This test script is documented with python
docstring in the code so that pydoc can be used to extract the
latest documentation. A README file is also included for
convenience, which contains the output of pydoc.

release: Add ciao BAT tests

---

ciao-cli/instance.go

Provides a way to list details about an specific
instance
Fixes #309

ciao-cli: implement instance show -instance UUID

---

ciao-cli/image.go

- Add the support of modifying the following image properties:
- visibility
- name
- tags
*The visibility modification depends on this PR https://github.com/sameo/gophercloud/pull/3 in order to work.

ciao-cli: Add image modification support via the modify subcommand

---

ciao-launcher/main.go

ciao-launcher: Fix typo

---

ciao-cli/image.go
ciao-cli/main.go
ciao-vendor/packages.json
vendor/github.com/rackspace/gophercloud/openstack/auth_env.go
vendor/github.com/rackspace/gophercloud/openstack/client.go
vendor/github.com/rackspace/gophercloud/openstack/identity/v3/tokens/errors.go
vendor/github.com/rackspace/gophercloud/openstack/identity/v3/tokens/requests.go
vendor/github.com/rackspace/gophercloud/openstack/imageservice/v2/images/fixtures.go
vendor/github.com/rackspace/gophercloud/openstack/imageservice/v2/images/requests.go
vendor/github.com/rackspace/gophercloud/openstack/imageservice/v2/images/results.go
vendor/github.com/rackspace/gophercloud/openstack/imageservice/v2/images/types.go
vendor/github.com/rackspace/gophercloud/openstack/imageservice/v2/images/urls.go
vendor/github.com/rackspace/gophercloud/provider_client.go
vendor/github.com/rackspace/gophercloud/testhelper/client/fake.go
vendor/github.com/rackspace/gophercloud/testhelper/convenience.go
vendor/github.com/rackspace/gophercloud/testhelper/doc.go
vendor/github.com/rackspace/gophercloud/testhelper/http_responses.go

With this PR, we can create, delete, modify, upload, download, list and show Glance images.
The PR also includes the gophercloud vendoring upgrade.

ciao-cli: Add Glance support

---

ciao-controller/client.go
ciao-controller/controller_test.go
ciao-controller/internal/datastore/datastore.go
ciao-controller/openstack_volume.go
ciao-controller/types/types.go
ciao-scheduler/scheduler.go
ciao-scheduler/scheduler_internal_test.go
openstack/block/api.go
payloads/storage.go
payloads/storage_test.go
testutil/payloads.go
testutil/server.go
testutil/testutil.go

This pull request adds support to the ciao-controller for the AttachVolume command from the block API. The scheduler was also modified to route the attach volume ssntp command to the correct agent.

Topic/storage pull request: add AttachVolume to controller & scheduler

---

ciao-controller/internal/datastore/datastore.go
ciao-controller/internal/datastore/datastore_test.go
ciao-controller/internal/datastore/sqlite3db.go
ciao-controller/internal/datastore/sqlite3db_test.go
ciao-launcher/overseer.go
networking/libsnnet/cn_test.go

Add sql needed to store block data persistently. Correct some misspelling issues.

Topic/storage pull request: add persistent storage for block data

---

.travis.yml
ciao-controller/controller_test.go
ciao-launcher/attachvolume_instance.go
ciao-launcher/detachvolume_instance.go
ciao-launcher/docker.go
ciao-launcher/instance.go
ciao-launcher/instance_test.go
ciao-launcher/overseer.go
ciao-launcher/payload.go
ciao-launcher/qemu.go
ciao-launcher/qemu_test.go
ciao-launcher/simulation.go
ciao-launcher/tests/ciaolc/ciaolc.go
ciao-launcher/tests/ciaolc/start_container.yaml
ciao-launcher/virtualizer.go
ciao-storage/block.go
ciao-storage/ceph.go
ciao-storage/noop.go
payloads/stats.go
testutil/payloads.go

These commits add basic support for Attaching and Detaching Volumes to VM instances.
They also fix the travis build.

ciao-launcher: Add support for Attach and Detach Volume

---

ciao-controller/client.go
ciao-controller/controller_test.go
ciao-controller/internal/datastore/datastore.go
ciao-controller/internal/datastore/datastore_test.go
testutil/agent.go
testutil/client_server_test.go
testutil/server.go

Make modifications needed to handle AttachVolumeFailure ssntp payloads.

Topic/storage pull request: add AttachVolume failure handling to ciao-controller

---

ciao-controller/compute_test.go

This pull requests has a series of commits to increase/improve the code coverage for ciao-controller.
Fixes #349

ciao-controller: increase code coverage

---

configuration/README.md

Fix sample configuration in configuration/README.md
- Missing ports on identity,image service urls
- IP addres instead of the expected CIDR

Configuration

---

.travis.yml
networking/libsnnet/docker_plugin.go

Add a workaround in the network plugin to fix https://github.com/01org/ciao/issues/420

Topic/docker 1.12

---

ciao-controller/internal/datastore/datastore.go
ciao-controller/internal/datastore/datastore_test.go
ciao-controller/internal/datastore/sqlite3db.go
ciao-controller/types/types.go

This PR is not yet ready to be merged into topic/storage. It is lacking unit tests and likely doesn't pass our travis checks yet. It's here in case you need early access to this code.

topic/storage pull request: add support for attachments

---

ciao-image/service/service.go
openstack/image/api.go

ciao-image: Fix service UploadImage

---

ciao-image/main.go
ciao-image/service/service.go

ciao-image: Minor fixes

---

ciao-cli/volume.go

This PR adds support for the volume detach command and also fixes a small typo in the help for the attach command.

ciao-cli: Add volume detach and fix a typo

---

testutil/agent.go
testutil/client_server_test.go
testutil/controller.go
testutil/server.go

I think this is the last of my cleanups.  I've learned a few things about ssntp, and with these tweeks here I've yet to see a failure.

testutil: more race/deadlock hunting

---

ciao-cli/identity.go

The getTenant function was evaluating single cases while it could have
a base to validate with a more structure scenarios as proposed below.
First validation: ensure the user has at least one project
Second validation: if the user has two or more project and not project
is specified, then print the projects the user has.
Third validation: iterate through all projects and see if the given
tentantID matches any project of the user.
If no condition matches, then it would return with the last instruction
in the function.

ciao-cli: code refactory of getTenant function

---

ciao-controller/controller_test.go
ciao-controller/internal/datastore/datastore.go
ciao-controller/internal/datastore/datastore_test.go
ciao-controller/internal/datastore/sqlite3db.go
ciao-controller/internal/datastore/sqlite3db_test.go
ciao-controller/openstack_volume.go

Modify ciao-controller to implement the interface for the openstack DeleteVolume, ShowVolumeDetail and ListVolumeDetails endpoints.

Complete implementation of the OpenStack block api interface in ciao-controller

---

ciao-controller/compute_test.go
ciao-controller/internal/datastore/datastore.go
ciao-controller/internal/datastore/datastore_test.go
ciao-controller/internal/datastore/sqlite3db.go

Fix issues with ineffectual assignments.

ciao-controller: fix ineffassign errors

---

networking/libsnnet/cn.go
networking/libsnnet/cn_container_test.go
networking/libsnnet/firewall_test.go
networking/libsnnet/tests/docker/plugin/plugin.go
networking/libsnnet/tests/parallel/parallel_test.go

Networking: Fix issues identifed by ineffassign

---

ciao-controller/compute_test.go
ciao-controller/internal/datastore/datastore.go
ciao-controller/internal/datastore/datastore_test.go
ciao-controller/internal/datastore/sqlite3db.go
networking/libsnnet/cn.go
networking/libsnnet/cn_container_test.go
networking/libsnnet/cnci.go
networking/libsnnet/firewall_test.go
networking/libsnnet/tests/docker/plugin/plugin.go
networking/libsnnet/tests/parallel/parallel_test.go
qemu/qmp.go
ssntp/ssntp.go

ineffassign has changed and caught some new errors. This PR addresses those errors so that travis will pass.

fix travis errors for ineffassign

---

testutil/singlevm/configuration.yaml
testutil/singlevm/dnsmasq.conf.macvlan0
testutil/singlevm/setup.sh

This change adds the following features to Single VM:
Auto ``macvlan`` interface creation with ip command
DHCP Server setup with ``dnsmasq``
This will help to accomplish #334 and will fix #446

singlevm : Add networking automation (macvlan and DHCP Server)

---

README.md

This makes easier for newcomers to catch a starting point from
the main documentation of the ciao repo.

Add contribution paragraph in main README.

---

ciao-launcher/overseer.go
ciao-launcher/overseer_test.go

These status messages are defined to have a zero length payload
associated with them. Let's avoid the overhead of creating the payload
when sending ssntp messages of these types.
Additionally this change makes sendStatusCommand report an error
message if an unsupported status type is used.
Fixes: #11

ciao-launcher: Don't send payload for ssntp.FULL/OFFLINE status messages

---

.travis.yml
openstack/image/api_test.go

Enable unit testing for the openstack/image service. The image package had broken unit tests, so fix them. Also add an additional test to bring coverage up over 70%.

Enable unit testing for openstack image package

---

test-cases/test-cases.go

test-cases contained some uncessary code for handling the list of packages
passed to it on the command line.  This code was unnecessary as go list
already does this processing for us, and it does it better.  So this patch
simply removes the custom handling, and test-cases now behaves like all
the other go tools, which is what users expect.
The commit also updates the usage message to explain how to specify packages
on the test-cases command line.

test-cases: Fix package list

---

ciao-launcher/doc.go
ciao-launcher/main.go

This change addresses the deadlock in #591. Tested via singlevm & and ciao-launcher-server/ciaolc

Fix launcher deadlock

---

ciao-controller/main.go
ciao-launcher/instance.go
ciao-launcher/main.go
ciao-launcher/tests/ciao-launcher-server/server.go
ciao-storage/ceph.go
ciao-storage/ceph_test.go
configuration/README.md
configuration/configuration.go
configuration/configuration_test.go
payloads/configure.go
payloads/configure_test.go
testutil/payloads.go

This PR will handle some issues im facing with ceph storage

ciao-storage: Fix a couple of issues.

---

qemu/qemu.go
qemu/qemu_test.go

This PR enables support for qemu socket based consoles and daemonization.
It also cleans some dead code up.

Support for qemu daemonization and socket based consoles

---

networking/libsnnet/docker_database.go
networking/libsnnet/docker_plugin.go

Move to generic database implementation for the docker plugin database.
This allows for the reuse of this implementation to store any in memory
key value database to persistent store implemented with boltDb+gob

Networking: Cleanup the docker plugin database implementation

---

ciao-cert/main.go
ssntp/certs/certs.go
ssntp/certs/certs_test.go

This PR forms part of the pre-work of a simpler deployment methodology. Through the commits in this PR the code for creating certificates is refactored out from ciao-cert and into the ssntp/certs package.

Refactor ciao certificate generation

---

testutil/singlevm/tables/workload_template.csv
testutil/singlevm/verify.sh
testutil/singlevm/workloads/docker-debian.yaml

Check docker network connectivity vs running the performance
benchmark. This matches what we do for virtual machines.
Fix some issues in the verify script where it was not reporting
failures with an exit code.

Single VM: Check docker network connectivity

---

ciao-cli/volume.go

This change takes advantage of the CreatedAt already populated in the
volume details as part of the openstack API.
Fixes: #689

ciao-cli: Report volumes in creation time order

---

ciao-cli/instance.go
ciao-controller/instance.go
ciao-controller/internal/datastore/sqlite3db.go
ciao-controller/openstack_compute.go
ciao-controller/types/types.go

Order instances in ciao-cli by creation time

---

ciao-cli/volume.go
ciao-controller/controller_test.go
ciao-controller/instance.go
ciao-controller/openstack_volume.go
ciao-controller/types/types.go
ciao-launcher/docker_test.go
ciao-storage/block.go
ciao-storage/ceph.go
ciao-storage/noop.go

Make changes necessary to support creation of bootable volumes from the command line and via the workload templates.

support creation of volumes from images

---

ciao-launcher/docker_network.go

This commit fixes #763, an issue that was introduced by some poor optimization.
When we create a container on a subnet on a CN for the first time we need
to create a new docker network.  This network needs to be created after the vnic
but before the container is created.  It follows that we need to be careful when
creating multiple containers in parallel.  The docker network will be created
during the creation of one of these containers.  The instance go routines
controlling the creation of the other containers need to block until the network
has been created, otherwise they will fail.  The optimisation deleted by this PR
was trying to reduce the amount of time the lock would be held for.
Unfortunately, the code did not consider the case that when instances are
deleted, the final instance …

ciao-launcher: Fix docker network locks

---

testutil/singlevm/setup.sh

Truncate demo.sh at each run vs appending.
Fixes issue https://github.com/01org/ciao/issues/769 

Single VM: Truncate demo.sh at each run

---

ciao-launcher/docker_network.go
ciao-launcher/network.go

There were two issues here.  Commit 54d8e50 introduced a bug which
lead to a new docker network being created with every container,
which is not what we want.  The intended behaviour is to create a
new docker network for each new subnet.  This creation of extra
networks lead to a leak as they were not getting deleted as they
were not supposed to exist.
There was an existing bug which could result in docker network
leaks when you created a container, a VM, deleted the container
and then the VM in that order.
Both these issues have now been fixed.
Fixes #768

ciao-launcher: Stop leaking docker networks

---

networking/ciao-cnci-agent/scripts/generate_cnci_cloud_image.sh

This implements a loop device based CNCI image mounting/handling
for CNCI certs and binary injection.
It removes `qemu*` dependencies, `losetup` and loop devices tools are
available by default on most of Linux distributions
Signed-off-by: Munoz, Obed N obed.n.munoz@intel.com

singlevm: Remove use of qemu-nbd to use loop device mountpoints

---

ciao-cert/README.md

We're seeing users not understanding the implications of hostnames in
certificates.  This commit attempts to be more explicit about the security
trade offs and the deployment choices for generic keys versus machine
specific keys.

ciao-cert: hostname clarifications for README.md

---

testutil/singlevm/verify.sh

Ensure that no ciao network artifacts are left behind when all instances have been deleted.
Note: Similar logic needs to be in place for storage other artifacts.
This will help catch regressions of the type https://github.com/01org/ciao/issues/768

Single VM: Ensure no ciao network artifacts are left behind

---

.travis.yml
_DeploymentAndDistroPackaging/ansible/tests/hosts

Add a test in travis to check ansible playbook syntax
Fixes #790

travis: Test ansible playbook

---

ciao-launcher/main.go
ciao-launcher/qemu.go
ciao-vendor/ciao-vendor.go
networking/libsnnet/docker_plugin.go
ssntp/client.go
ssntp/ssntp.go
testutil/agent.go
testutil/controller.go
testutil/server.go

golint has updated and has exciting new requirements for us. Remove all newlines and punctuation from error strings.

fixes for travis golint upgrade

---

ciao-controller/openstack_image.go

In order to improve debugging, we need more logging in ciao-image service. Below the main events that are planned to be logged.
- Init information
- Errors reporting
- Basic information on image CRUD operations
It fixes #779

ciao-image: Add more logging information

---

ciao-cli/image.go

@markdryan found some resource issues with ciao-cli image commands in #662 this PR addresses those by not loading the entire image into memory when uploading and downloading.

Fix resource issues with ciao-cli image

---

testutil/singlevm/cleanup.sh

Fix a couple of nits left over from the integration of the images as volumes work.

Minor SingleVM fixes

---

testutil/singlevm/setup.sh

Single VM was broken by #850 as it was not updated to reflect the new
controller paths introduced by that PR.  This patch modifies Single VM
to use these paths.  The BAT tests pass in Single VM with this patch applied.

Single VM: Fix Single VM

---

ciao-controller/internal/datastore/sqlite3db.go
ciao-controller/main.go

Make a few cleanups to persistentStore after #850: 
a.) delete some unnecessary directory creations.
b.) treat the URI member as a URI

Persistent store cleanup

---

_DeploymentAndDistroPackaging/ansible/roles/ciao-common/README.md
_DeploymentAndDistroPackaging/ansible/roles/ciao-common/defaults/main.yml
_DeploymentAndDistroPackaging/ansible/roles/ciao-compute/tasks/images.yml
_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/README.md
_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/defaults/main.yml
_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/tasks/main.yml
_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/tasks/upload_images.yml
_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/templates/admin-ciaorc.j2
_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/templates/demo-ciaorc.j2
_DeploymentAndDistroPackaging/ansible/roles/ciao-network/tasks/images.yml
ciao-cli/README.md
ciao-controller/tables/workload_template.csv
testutil/singlevm/tables/workload_template.csv

First commit Fix #841
The rest are improvements

ansible: Upload images to ciao-image

---

testutil/singlevm/setup.sh
testutil/singlevm/verify.sh

Setup the cloud-init in the controller data directory vs the cache.
Fixes https://github.com/01org/ciao/issues/925

Single VM: Bugfix: Setup the cloud-init in the right location

---

ciao-storage/ceph.go

Report the output from rbd commands in the log if the command errors
out (non-zero exit code.)
Fixes: #642

ciao-storage: Improve error logging from rbd commands

---

ciao-cli/image.go

This PR addresses #684 and #681 by removing unused functionality from ciao-cli image.

ciao-cli image cleanup

---

testutil/ciao-down/ciao_down.go
testutil/ciao-down/vm.go

The status and the connect commands now handle the case where the VM is running
but has not yet booted and so cannot be connected to via SSH.  ciao-down
connect will now wait until the VM has booted before attempting to SSH into the
guest VM.
Fixes #956

ciao-down: Update connect and status to handle booting VMs

---

packages.json
vendor/github.com/boltdb/bolt/README.md
vendor/github.com/boltdb/bolt/bolt_386.go
vendor/github.com/boltdb/bolt/bolt_amd64.go
vendor/github.com/boltdb/bolt/bolt_arm.go
vendor/github.com/boltdb/bolt/bolt_arm64.go
vendor/github.com/boltdb/bolt/bolt_ppc64.go
vendor/github.com/boltdb/bolt/bolt_ppc64le.go
vendor/github.com/boltdb/bolt/bolt_s390x.go
vendor/github.com/boltdb/bolt/bolt_unix.go
vendor/github.com/boltdb/bolt/bolt_windows.go
vendor/github.com/boltdb/bolt/bucket.go
vendor/github.com/boltdb/bolt/db.go
vendor/github.com/boltdb/bolt/errors.go
vendor/github.com/boltdb/bolt/freelist.go
vendor/github.com/boltdb/bolt/node.go
vendor/github.com/boltdb/bolt/page.go
vendor/github.com/boltdb/bolt/tx.go

This commit updates boltdb to revision a705895.  All BAT tests pass
with this new version.

vendor: boltdb: Update boltdb to version a705895

---

ciao-controller/client.go
ciao-controller/internal/datastore/datastore.go
ciao-controller/internal/datastore/datastore_test.go
ciao-controller/internal/datastore/sqlite3db.go
packages.json
vendor/github.com/pkg/errors/LICENSE
vendor/github.com/pkg/errors/README.md
vendor/github.com/pkg/errors/errors.go
vendor/github.com/pkg/errors/stack.go

This PR starts enhancing our error logging in controller. As well as couple of minor fixes the bulk of the work is the addition and use of errors package from https://github.com/pkg/errors and some improvements to the way errors are logged from the client code when controller receives events via SSNTP.

Start improving error reporting in controller

---

ciao-cli/template.go

Add support for generic regexp matching. This allows the use of
textual regular expressions as supported by the go regexp package.
This makes some of the other functions redundant, but they are
retained for simplicity.

ciao-cli: Add support for regexp matching

---

ciao-controller/api/api.go

Use the new uuid.Regex constant to do input validation for
uuid4 in routes.

ciao-controller: switch api to use regex in uuid package.

---

ciao-cli/identity.go

The ciao-cli's identity code that handles tokens is never returning an
error.  These leads to strange runtime behaviors in the face of a bad
identity service:  A token related command would fail, but the function
would return a nil error.  The caller would then carry on with
uninitialized "" string variables, which of course led to more failures.
This obfuscates the root issue.
There is an errorf (in some cases of questionable quality) present into
the code adjacent to the nil return.  For simplicity, I've just moved
these existing messages into the errors.Wrap() in addition to the err
itself.  At that point we get the benefit of annotated errors in the
call stack and a non-nil error return so that callers don't carry on
thinking there was no error.
Fixes: #1068
Signed-off-by: Tim Pepper …

ciao-cli: identity: return wrapped errors

---

openstack/identity/identity.go

This commit reduces 2 Keystone service calls per request.
Basically, it will initialize token-based client information at the
moment a request comes to the service and will add it to the main
handler to be re-used on all the identity corresponding custo functions.
At the end, it boosts the performance with the removal of non-required API calls.
Below is an example of Keystone service logs with a simple instance listing call ``ciao-cli instance list``.
```
➜  docker-ciao git:(master) ✗ docker-compose exec  ciao-keystone tail -f /var/log/nginx-access.log -n 0
172.18.0.1 - - [19/Jan/2017:18:26:28 +0000] "POST /v3/auth/tokens HTTP/2.0" 201 719 "-""gophercloud/1.0.0"
172.18.0.1 - - [19/Jan/2017:18:26:28 +0000] "POST /v3/auth/tokens HTTP/2.0" 201 2638 "-" "gophercloud/1.0.0"
172.18.0.1 - - …
```

openstack: Reduce number of Keystone requests

---

DeveloperQuickStart.md

Placeholder file to review documentation for issue #1055 
We could consider moving wiki content directly into the ciao git as .md files and use the wiki just for navigation. That will make review process easier, and also ensure our documentation is not in the github wiki git repo but in the code git repo.

Documentation Update: Update Developer Documentation to reflect ciao-down based setup

---

DeveloperQuickStart.md

- Fix formatting issues with the Single Machine Documentation.
- Change the name of the bridge interface to ciao_br, to reflect code changes
- Move the cluster external access setup instructions
- Ensure that the user sources the environment variables in all places

Documentation: Documentation update

---

testutil/singlevm/setup.sh

A few bits to support singlevm(bare metal) on archlinux host systems.

Singlevm archlinux support

---

testutil/ciao-down/ciao_down.go
testutil/ciao-down/cloudinit.go
testutil/ciao-down/host_linux.go
testutil/ciao-down/vm.go
testutil/singlevm/setup.sh

This PR fixes a few small issues with ciao-down:
1. Values in the /etc/environment file were not quoted.
2. No limit was placed on the default values for CPU and memory usage.
3. ciao-down connect and ciao-down status did not work when ciao-down prepare was running.
4. apt-get upgrade was hanging.

Ciao down fixes

---

_DeploymentAndDistroPackaging/ansible/cleanup/ciao.yml
_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/tasks/main.yml
_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/templates/admin-ciaorc.j2
_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/templates/bat-ciaorc.j2
_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/templates/demo-ciaorc.j2
_DeploymentAndDistroPackaging/ansible/roles/keystone/templates/clouds.yaml.j2
_DeploymentAndDistroPackaging/ansible/roles/keystone/templates/openrc.j2
bat/compute.go

Some changes to make it easier to run BAT against an ansible built cluster.

Ansible BAT improvements

---

testutil/ciao-down/cloudinit.go

Add the packages needed to build clear container binaries
from sources

ciao-down: Add support for clear containers development

---

ciao-controller/api.go
ciao-controller/internal/datastore/memorydb.go
ciao-controller/internal/quotas/quotas.go

On #1160 I report out some unused/unreachable code sections in our tree. This PR fixes a small subset of those issues focusing on ciao-controller and datastore.

Ciao controller unused code removal

---

_release/bat/quotas_bat/quotas_bat_test.go

This change fixes an issue where if the container workload was not found
then the restoration of the quotas will not occur as t.Skip() was
called. By using a defer we can ensure that the cleanup always happens
and we're not left with dangling quotas.

bat: Use a defer for quota cleanup in BAT tests

---

_DeploymentAndDistroPackaging/ansible/cleanup/ciao.yml
_DeploymentAndDistroPackaging/ansible/roles/docker/tasks/install_fedora.yml
_DeploymentAndDistroPackaging/ansible/roles/docker/tasks/install_ubuntu.yml
_DeploymentAndDistroPackaging/ansible/roles/docker/tasks/main.yml

docker-engine has been renamed to docker-ce
Fixes #1223

ansible: Update docker role to install docker-ce

---

_DeploymentAndDistroPackaging/ansible/roles/ciao-webui/templates/docker-ciao-webui.service.j2
_DeploymentAndDistroPackaging/ansible/roles/docker/defaults/main.yml
_DeploymentAndDistroPackaging/ansible/roles/docker/tasks/install_clearlinux.yml
_DeploymentAndDistroPackaging/ansible/roles/keystone/templates/docker-keystone.service.j2

- Due to recent changes in the clearlinux's containers-basic bundle
the changes introduced in the commit https://github.com/01org/ciao/commit/3617ee31f378226fff6d00bf223a8dd65f3af158
need to be reverted.

Deployment: Revert changes to docker service in clearlinux.

---

ciao-cert/main.go
ssntp/certs/certs.go
ssntp/certs/certs_test.go

This PR provides the certificate request and signing framework that enables the new deployment tooling. Although the deployment tooling is still complete the commits herein are mature enough to be ready to merge in preparation. The functionality is covered by a newly added unit test.

ssntp/certs: Add handling for certificate requests

---

ciao-cli/external-ips.go
ciao-controller/api/api.go

Whilst I was looking into #1289 I found a few other minor issues which are fixed in this PR along with a fix for #1289.

Minor pool bug fixes

---

testutil/ciao-down/ciao_down.go
testutil/ciao-down/instance.go
testutil/ciao-down/workload.go

A few ciao-down trivial patches

---

ciao-controller/controller_test.go
ciao-controller/internal/datastore/datastore.go
ciao-controller/internal/datastore/datastore_test.go
ciao-controller/internal/datastore/sqlite3db.go
ciao-controller/internal/datastore/sqlite3db_test.go
ciao-controller/main.go

Remove the transient database to resolve issues that present themselves when controller gets restarted.

Remove transient database

---

_release/bat/storage_bat/ceph_test.go

If we use the ciao cluster configuration file to retrieve the cephID,
then we don't have to hardcode it.
Fixes: #1472

ceph_bat: Use system configuration file to determine cephID

---

testutil/agent.go

agent.go:367:32: func (*SsntpTestClient).handleStop is unused (U1000)
agent.go:396:32: func (*SsntpTestClient).handleRestart is unused (U1000)
agent.go:775:32: func (*SsntpTestClient).sendStopFailure is unused (U1000)
agent.go:792:32: func (*SsntpTestClient).sendRestartFailure is unused (U1000)
These functions were made unused by
ab276fc3df0a433281a87ed7ce3e62c85269596f

testutil: Remove unused code

---

ciao-deploy/deploy/nodes.go

If any step during a "ciao-deploy unjoin" fails print an error and keep
going.
Fixes: #1488

ciao-deploy: Keep going if any unjoin step fails

---

_release/bat/storage_bat/storage_bat_test.go

Since it is no longer possible to detach from an active instance
ciao-cli should generate an error.  Ensure that this error occurs when
trying to detach from an active instance by creating a new BAT test.

storage_bat: Test that detaching from active instance fails

---

ciao-controller/workload.go

Check the the volume or image specified in the workload creation request
is valid (including accessible to the current tenant.)
Fixes: #1224

ciao-controller: as part of workload validation check image/volume

---

ciao-controller/api.go
ciao-controller/api/api.go
ciao-controller/client.go
ciao-controller/cnci.go
ciao-controller/command.go
ciao-controller/compute.go
ciao-controller/compute_test.go
ciao-controller/controller_test.go
ciao-controller/image.go
ciao-controller/instance.go
ciao-controller/internal/datastore/datastore_test.go
ciao-controller/internal/datastore/sqlite3db.go
ciao-controller/internal/datastore/sqlite3db_test.go
ciao-controller/legacy_api.go
ciao-controller/main.go
ciao-controller/node.go
ciao-controller/volume.go

Make ciao-controller "errcheck clean" but also also improve the logging so that we get messages in the log whenever we service a HTTP request that generates an error.

Tweak error handling in ciao-controller

---

ciao-controller/image.go
ciao-controller/main.go

add a couple additional log output lines when encountering errors during image upload. Also make sure log is actually written on exit from controller.

ciao-controller: improve logging a tiny bit

---

qemu/qemu.go

Add vhost fd support. This is needed in the case of multi queue.

Networking: Add vhost fd support

---

ciao-controller/api.go
ciao-controller/command.go
ciao-controller/server.go
ciao-controller/volume.go
ciao-controller/workload.go
ciao-deploy/deploy/workloads.go

We don't create the workloads as admin so we shouldn't create the
images as admin.

ciao-deploy: Don't upload images as admin for BAT

---

ciao-vendor/ciao-vendor.go

This commit updates ciao-vendor to copy assembly language files in
vendored packages if present.

ciao-vendor: Copy assembly language files

---

_release/bat/base_bat/base_bat_test.go
_release/bat/workload_bat/workload_bat_test.go
bat/workload.go
ciao-cli/examples/fedora_cloud.yaml
ciao-cli/examples/fedora_cloud_disk.yaml
ciao-cli/examples/ubuntu_latest.yaml
ciao-cli/workload.go
ciao-controller/api/api_test.go
ciao-controller/client.go
ciao-controller/controller_test.go
ciao-controller/instance.go
ciao-controller/internal/datastore/datastore.go
ciao-controller/internal/datastore/datastore_test.go
ciao-controller/internal/datastore/sqlite3db.go
ciao-controller/internal/datastore/sqlite3db_test.go
ciao-controller/quotas.go
ciao-controller/types/types.go
ciao-deploy/deploy/workloads.go
ciao-launcher/overseer.go
ciao-scheduler/scheduler.go
k8s/kubicle/cloudinit.go
payloads/ready.go
payloads/ready_test.go
payloads/start.go
testutil/payloads.go

This PR adds support for routing workloads by hostname or workload requirements. It is based off #1578 that exposes the new workload requirement struct to the user.

Workload routing by node ID or hostname requirements

---

ciao-deploy/deploy/cnci.go
ciao-deploy/deploy/utils.go

Reverts ciao-project/ciao#1567 due to #1586

Revert "ciao-deploy: use a generic base clear image for building cnci."

---

testutil/singlevm/verify.sh

Verify.sh contained a number of hardcoded values and race conditions that
meant that it would only execute successfully on prestine clusters, i.e.,
clusters that had just been created but had not been used for any other
purpose.  This patch addresses these issues.
Fixes: http://github.com/ciao-project/ciao/issues/1565

SingleVM: Make verify.sh run on non-prestine clusters

---

_release/bat/tenant_bat/tenant_bat_test.go
_release/bat/workload_bat/workload_bat_test.go
bat/tenant.go
bat/workload.go
ciao-cli/tenant.go
ciao-cli/workload.go
ciao-controller/api/api_test.go
ciao-controller/command.go
ciao-controller/internal/datastore/datastore.go
ciao-controller/internal/datastore/memorydb.go
ciao-controller/internal/datastore/sqlite3db.go
ciao-controller/internal/datastore/sqlite3db_test.go
ciao-controller/tenants.go
ciao-controller/types/types.go
ciao-launcher/docker.go
ciao-launcher/docker_test.go
ciao-launcher/payload.go
ciao-launcher/vmconfig.go
client/tenants.go
payloads/start.go

Add support for privileged containers. This necessitated adding a mechanism to give tenants permissions so that is also implemented in this PR.

Add support for privileged containers

---

ciao-controller/command.go

Controller was crashing if one or more of the instances launched in a bulk
instance start request failed to launch correctly.  This commit fixes
the issue by ensuring that we don't return nil pointers to failed instances.

ciao-controller: Fix a crash in instance creation

---

ciao/cmd/create.go
ciao/cmd/list.go
ciao/cmd/show.go

Minor template tweaks to the output from ciao to make it more readable and user friendly.

Follow-up CLI tweaks

---

ciao/cmd/create.go
ciao/cmd/list.go
ciao/cmd/root.go
ciao/cmd/show.go

Put template usage information in the usage output of commands in ciao that use tfortools for output.

ciao: Add templating usage to command
